// words/easy.js — Easy difficulty word bank (54 cards)
// Simple everyday items — great for kids aged 8+

const WORDS_EASY = [
  { word: "CRICKET",      taboo: ["bat", "ball", "wicket", "India", "pitch"] },
  { word: "MANGO",        taboo: ["fruit", "yellow", "summer", "sweet", "king"] },
  { word: "ELEPHANT",     taboo: ["trunk", "grey", "big", "zoo", "wild"] },
  { word: "TRAIN",        taboo: ["track", "engine", "railway", "station", "ticket"] },
  { word: "TEMPLE",       taboo: ["god", "prayer", "bell", "worship", "priest"] },
  { word: "CHAI",         taboo: ["tea", "hot", "milk", "cup", "drink"] },
  { word: "SCHOOL",       taboo: ["study", "teacher", "class", "learn", "homework"] },
  { word: "RAIN",         taboo: ["water", "cloud", "wet", "umbrella", "pour"] },
  { word: "BICYCLE",      taboo: ["wheel", "pedal", "ride", "cycle", "two"] },
  { word: "FLOWER",       taboo: ["petal", "rose", "garden", "smell", "bloom"] },
  { word: "BOOK",         taboo: ["read", "page", "story", "library", "author"] },
  { word: "DOG",          taboo: ["bark", "tail", "pet", "bite", "woof"] },
  { word: "MOON",         taboo: ["night", "sky", "round", "glow", "crater"] },
  { word: "SUN",          taboo: ["hot", "bright", "yellow", "shine", "day"] },
  { word: "RICE",         taboo: ["white", "cook", "eat", "grain", "bowl"] },
  { word: "KITE",         taboo: ["fly", "string", "wind", "paper", "sky"] },
  { word: "PENCIL",       taboo: ["write", "draw", "eraser", "sharp", "school"] },
  { word: "FISH",         taboo: ["swim", "sea", "fins", "catch", "water"] },
  { word: "BOAT",         taboo: ["sail", "row", "river", "float", "oar"] },
  { word: "ICE CREAM",    taboo: ["cold", "sweet", "cone", "lick", "flavour"] },
  { word: "BIRTHDAY",     taboo: ["cake", "candle", "party", "celebrate", "gift"] },
  { word: "FOOTBALL",     taboo: ["kick", "goal", "team", "field", "round"] },
  { word: "MONKEY",       taboo: ["tree", "banana", "jump", "wild", "swing"] },
  { word: "MIRROR",       taboo: ["reflect", "glass", "face", "look", "silver"] },
  { word: "UMBRELLA",     taboo: ["rain", "open", "wet", "protect", "shade"] },
  { word: "CAMERA",       taboo: ["photo", "click", "picture", "lens", "capture"] },
  { word: "PHONE",        taboo: ["call", "mobile", "ring", "screen", "talk"] },
  { word: "CLOCK",        taboo: ["time", "tick", "hour", "alarm", "hand"] },
  { word: "EGG",          taboo: ["chicken", "cook", "round", "yolk", "shell"] },
  { word: "BREAD",        taboo: ["slice", "toast", "butter", "wheat", "loaf"] },
  { word: "DOCTOR",       taboo: ["hospital", "medicine", "sick", "cure", "stethoscope"] },
  { word: "BUS",          taboo: ["road", "seat", "stop", "driver", "wheels"] },
  { word: "APPLE",        taboo: ["red", "fruit", "juice", "tree", "crunch"] },
  { word: "BALLOON",      taboo: ["air", "float", "party", "blow", "pop"] },
  { word: "CANDLE",       taboo: ["light", "wax", "flame", "burn", "dark"] },
  { word: "CHAIR",        taboo: ["sit", "furniture", "wood", "legs", "rest"] },
  { word: "SHOE",         taboo: ["foot", "wear", "walk", "lace", "leather"] },
  { word: "BANANA",       taboo: ["yellow", "peel", "fruit", "bunch", "ripe"] },
  { word: "COW",          taboo: ["milk", "holy", "farm", "horn", "moo"] },
  { word: "PARROT",       taboo: ["green", "bird", "talk", "cage", "colourful"] },
  { word: "SOAP",         taboo: ["wash", "clean", "foam", "bath", "bubble"] },
  { word: "RAINBOW",      taboo: ["colour", "sky", "rain", "arc", "seven"] },
  { word: "BUTTERFLY",    taboo: ["wings", "fly", "colourful", "flower", "insect"] },
  { word: "TORCH",        taboo: ["light", "dark", "battery", "beam", "hold"] },
  { word: "LADDER",       taboo: ["climb", "step", "rung", "height", "reach"] },
  { word: "PILLOW",       taboo: ["sleep", "soft", "bed", "head", "rest"] },
  { word: "GARDEN",       taboo: ["plant", "flower", "grow", "water", "green"] },
  { word: "LION",         taboo: ["roar", "mane", "wild", "cat", "Africa"] },
  { word: "SNAKE",        taboo: ["slither", "poison", "long", "scales", "hiss"] },
  { word: "PEACOCK",      taboo: ["feather", "dance", "colourful", "national", "bird"] },
  { word: "TIGER",        taboo: ["stripes", "jungle", "roar", "cat", "wild"] },
  { word: "NEWSPAPER",    taboo: ["daily", "read", "news", "print", "reporter"] },
  { word: "WATERFALL",    taboo: ["water", "fall", "hill", "nature", "spray"] },
  { word: "CHOCOLATE",    taboo: ["sweet", "brown", "cocoa", "melt", "candy"] },

  // ── 100 additional easy words ──────────────────────────────────────────
  { word: "CAT",           taboo: ["meow", "fur", "pet", "purr", "scratch"] },
  { word: "RABBIT",        taboo: ["hop", "ear", "fur", "carrot", "fast"] },
  { word: "HORSE",         taboo: ["ride", "gallop", "mane", "stable", "run"] },
  { word: "FROG",          taboo: ["jump", "pond", "croak", "green", "wet"] },
  { word: "SPIDER",        taboo: ["web", "eight", "legs", "crawl", "insect"] },
  { word: "BEE",           taboo: ["honey", "sting", "yellow", "flower", "hive"] },
  { word: "ANT",           taboo: ["small", "colony", "carry", "black", "red"] },
  { word: "OWL",           taboo: ["night", "wise", "hoot", "feather", "dark"] },
  { word: "PENGUIN",       taboo: ["cold", "black", "white", "fish", "ice"] },
  { word: "DOLPHIN",       taboo: ["swim", "smart", "sea", "jump", "friendly"] },
  { word: "SAMOSA",        taboo: ["crispy", "fried", "triangle", "snack", "potato"] },
  { word: "CHAPATI",       taboo: ["round", "flat", "wheat", "eat", "bread"] },
  { word: "PAKORA",        taboo: ["fried", "snack", "onion", "crispy", "batter"] },
  { word: "JALEBI",        taboo: ["sweet", "orange", "spiral", "crispy", "syrup"] },
  { word: "LADDOO",        taboo: ["sweet", "round", "yellow", "festival", "gram"] },
  { word: "CHUTNEY",       taboo: ["sauce", "green", "spicy", "coconut", "dip"] },
  { word: "PICKLE",        taboo: ["sour", "spicy", "jar", "mango", "preserve"] },
  { word: "PURI",          taboo: ["round", "fried", "puffed", "wheat", "eat"] },
  { word: "ROTI",          taboo: ["flat", "wheat", "round", "eat", "bread"] },
  { word: "DAL",           taboo: ["lentil", "yellow", "cook", "eat", "soup"] },
  { word: "POHA",          taboo: ["flattened", "rice", "breakfast", "yellow", "snack"] },
  { word: "KHICHDI",       taboo: ["rice", "lentil", "soft", "simple", "comfort"] },
  { word: "TOMATO",        taboo: ["red", "vegetable", "sauce", "cook", "round"] },
  { word: "POTATO",        taboo: ["vegetable", "fry", "underground", "starchy", "cook"] },
  { word: "ONION",         taboo: ["vegetable", "peel", "cry", "smell", "round"] },
  { word: "CARROT",        taboo: ["orange", "vegetable", "sweet", "crunch", "rabbit"] },
  { word: "GRAPES",        taboo: ["purple", "fruit", "bunch", "sweet", "vine"] },
  { word: "WATERMELON",    taboo: ["big", "green", "red", "sweet", "summer"] },
  { word: "GUAVA",         taboo: ["pink", "fruit", "sour", "sweet", "vitamin"] },
  { word: "ORANGE",        taboo: ["citrus", "round", "peel", "juice", "vitamin"] },
  { word: "LEMON",         taboo: ["yellow", "sour", "citrus", "juice", "squeeze"] },
  { word: "CHILLI",        taboo: ["spicy", "red", "hot", "cook", "pepper"] },
  { word: "SPINACH",       taboo: ["green", "leaf", "vegetable", "iron", "cook"] },
  { word: "GINGER",        taboo: ["root", "spicy", "chai", "cook", "brown"] },
  { word: "GARLIC",        taboo: ["clove", "smell", "cook", "white", "peel"] },
  { word: "PEN",           taboo: ["write", "ink", "cap", "blue", "ballpoint"] },
  { word: "RULER",         taboo: ["measure", "straight", "line", "length", "flat"] },
  { word: "SCISSORS",      taboo: ["cut", "sharp", "two", "blade", "craft"] },
  { word: "CRAYON",        taboo: ["colour", "wax", "draw", "child", "art"] },
  { word: "ERASER",        taboo: ["rub", "pencil", "mistake", "white", "remove"] },
  { word: "NOTEBOOK",      taboo: ["write", "pages", "line", "cover", "school"] },
  { word: "SCHOOL BAG",    taboo: ["carry", "book", "zip", "heavy", "strap"] },
  { word: "GLOBE",         taboo: ["round", "earth", "spin", "country", "model"] },
  { word: "DOLL",          taboo: ["toy", "girl", "dress", "hair", "play"] },
  { word: "CARROM",        taboo: ["board", "coin", "strike", "finger", "family"] },
  { word: "LUDO",          taboo: ["dice", "colour", "board", "token", "play"] },
  { word: "CHESS",         taboo: ["board", "king", "queen", "think", "strategy"] },
  { word: "MARBLES",       taboo: ["glass", "round", "roll", "play", "colour"] },
  { word: "BADMINTON",     taboo: ["shuttle", "racket", "net", "court", "sport"] },
  { word: "KABADDI",       taboo: ["tag", "hold", "breath", "team", "touch"] },
  { word: "KHO KHO",       taboo: ["run", "touch", "team", "outdoor", "sport"] },
  { word: "SWING",         taboo: ["play", "park", "push", "hang", "fun"] },
  { word: "SPINNING TOP",  taboo: ["spin", "toy", "play", "fast", "round"] },
  { word: "FLAG",          taboo: ["wave", "colour", "pole", "country", "national"] },
  { word: "STAR",          taboo: ["sky", "night", "shine", "five", "point"] },
  { word: "MOUNTAIN",      taboo: ["tall", "snow", "climb", "peak", "steep"] },
  { word: "BEACH",         taboo: ["sand", "sea", "wave", "swim", "holiday"] },
  { word: "CLOUD",         taboo: ["sky", "float", "white", "grey", "fluffy"] },
  { word: "ROCK",          taboo: ["hard", "stone", "heavy", "grey", "climb"] },
  { word: "SAND",          taboo: ["beach", "fine", "yellow", "castle", "hot"] },
  { word: "DOOR",          taboo: ["open", "close", "knock", "lock", "enter"] },
  { word: "WINDOW",        taboo: ["glass", "open", "light", "look", "frame"] },
  { word: "PLATE",         taboo: ["eat", "round", "flat", "food", "serve"] },
  { word: "SPOON",         taboo: ["stir", "scoop", "soup", "silver", "eat"] },
  { word: "CUP",           taboo: ["tea", "drink", "hot", "handle", "sip"] },
  { word: "BROOM",         taboo: ["sweep", "clean", "floor", "stick", "dust"] },
  { word: "MAT",           taboo: ["floor", "sit", "prayer", "weave", "flat"] },
  { word: "BASKET",        taboo: ["weave", "carry", "fruit", "handle", "wicker"] },
  { word: "BUCKET",        taboo: ["water", "plastic", "fill", "carry", "pour"] },
  { word: "BLANKET",       taboo: ["warm", "soft", "cover", "sleep", "cosy"] },
  { word: "BELL",          taboo: ["ring", "sound", "door", "temple", "school"] },
  { word: "KEY",           taboo: ["open", "lock", "metal", "door", "find"] },
  { word: "LOCK",          taboo: ["secure", "key", "metal", "door", "shut"] },
  { word: "WALLET",        taboo: ["money", "pocket", "leather", "card", "thin"] },
  { word: "ALARM CLOCK",   taboo: ["wake", "ring", "morning", "set", "beep"] },
  { word: "CURTAIN",       taboo: ["window", "cloth", "hang", "block", "light"] },
  { word: "FAN",           taboo: ["cool", "spin", "blade", "summer", "electric"] },
  { word: "LIGHT BULB",    taboo: ["glow", "electric", "round", "bright", "socket"] },
  { word: "DUSTBIN",       taboo: ["throw", "waste", "plastic", "rubbish", "lid"] },
  { word: "CALENDAR",      taboo: ["date", "month", "year", "hang", "plan"] },
  { word: "WATCH",         taboo: ["wrist", "time", "wear", "tick", "dial"] },
  { word: "STAMP",         taboo: ["post", "letter", "stick", "mail", "picture"] },
  { word: "ENVELOPE",      taboo: ["letter", "seal", "mail", "paper", "address"] },
  { word: "BUTTER",        taboo: ["yellow", "spread", "milk", "bread", "melt"] },
  { word: "HONEY",         taboo: ["sweet", "bee", "jar", "thick", "golden"] },
  { word: "GHEE",          taboo: ["clarified", "butter", "Indian", "cook", "golden"] },
  { word: "OIL",           taboo: ["cook", "fry", "liquid", "bottle", "pour"] },
  { word: "SALT",          taboo: ["white", "taste", "food", "sea", "sprinkle"] },
  { word: "SUGAR",         taboo: ["sweet", "white", "tea", "spoon", "cube"] },
  { word: "FLOUR",         taboo: ["wheat", "white", "powder", "knead", "cook"] },
  { word: "COMB",          taboo: ["hair", "teeth", "smooth", "plastic", "groom"] },
  { word: "TOOTHBRUSH",    taboo: ["teeth", "clean", "paste", "morning", "bristle"] },
  { word: "TOWEL",         taboo: ["dry", "bath", "soft", "wipe", "hang"] },
  { word: "NEEM",          taboo: ["tree", "bitter", "medicine", "leaf", "India"] },
  { word: "TULSI",         taboo: ["plant", "holy", "India", "leaf", "medicine"] },
  { word: "BAMBOO",        taboo: ["tall", "hollow", "strong", "forest", "green"] },
  { word: "FOREST",        taboo: ["tree", "wild", "green", "animal", "dark"] },
  { word: "RIVER",         taboo: ["water", "flow", "long", "bank", "fish"] },
  { word: "HIDE AND SEEK", taboo: ["hide", "find", "count", "children", "game"] },
  { word: "TUG OF WAR",    taboo: ["rope", "pull", "team", "strength", "game"] },
  { word: "PINEAPPLE",     taboo: ["tropical", "yellow", "spiky", "sweet", "fruit"] },
  { word: "POMEGRANATE",   taboo: ["red", "seeds", "fruit", "sweet", "juice"] },
  { word: "HOPSCOTCH",     taboo: ["jump", "chalk", "square", "children", "game"] },

  // ── 300 additional easy words (Indian context) ─────────────────────────

  // Animals & Birds
  { word: "COBRA",           taboo: ["hood", "venom", "charmer", "dangerous", "sway"] },
  { word: "CROCODILE",       taboo: ["snap", "scaly", "reptile", "sharp teeth", "long"] },
  { word: "DEER",            taboo: ["antlers", "gentle", "forest", "graceful", "brown"] },
  { word: "BUFFALO",         taboo: ["farm", "black", "horn", "heavy", "strong"] },
  { word: "CAMEL",           taboo: ["hump", "desert", "thirst", "sand", "Rajasthan"] },
  { word: "BEAR",            taboo: ["honey", "cave", "fur", "growl", "forest"] },
  { word: "SQUIRREL",        taboo: ["tree", "nut", "bushy", "small", "jump"] },
  { word: "CROW",            taboo: ["caw", "black", "clever", "city", "common"] },
  { word: "SPARROW",         taboo: ["tweet", "nest", "small", "city", "brown"] },
  { word: "EAGLE",           taboo: ["soar", "sharp", "large", "hunt", "sky"] },
  { word: "FLAMINGO",        taboo: ["pink", "wading", "graceful", "flock", "water"] },
  { word: "KOEL",            taboo: ["cuckoo", "sing", "summer", "sweet", "call"] },
  { word: "HERON",           taboo: ["wade", "white", "long neck", "fishing", "tall"] },
  { word: "KINGFISHER",      taboo: ["blue", "river", "dive", "fish", "colourful"] },
  { word: "MONGOOSE",        taboo: ["fight", "fast", "brown", "thin", "clever"] },
  { word: "TORTOISE",        taboo: ["shell", "slow", "hard", "long lived", "crawl"] },
  { word: "LIZARD",          taboo: ["wall", "tail", "quick", "reptile", "scaly"] },
  { word: "MYNA",            taboo: ["talk", "black", "yellow beak", "common", "India"] },
  { word: "CRANE",           taboo: ["tall", "white", "dance", "water", "graceful"] },
  { word: "DUCK",            taboo: ["quack", "pond", "waddle", "swim", "white"] },
  { word: "OSTRICH",         taboo: ["large", "run", "egg", "neck", "flightless"] },
  { word: "CHEETAH",         taboo: ["fast", "spot", "Africa", "run", "big cat"] },
  { word: "GORILLA",         taboo: ["large", "fur", "jungle", "strong", "knuckle"] },
  { word: "FOX",             taboo: ["cunning", "red", "bushy", "sly", "tail"] },
  { word: "JACKAL",          taboo: ["howl", "cunning", "scavenger", "wild", "thin"] },
  { word: "DRAGONFLY",       taboo: ["wings", "hover", "water", "colourful", "insect"] },
  { word: "FIREFLY",         taboo: ["glow", "night", "tiny", "blink", "magic"] },
  { word: "GRASSHOPPER",     taboo: ["jump", "green", "field", "chirp", "insect"] },
  { word: "LADYBIRD",        taboo: ["red", "spot", "small", "garden", "fly"] },
  { word: "EARTHWORM",       taboo: ["soil", "wriggle", "soft", "pink", "rain"] },
  { word: "CRAB",            taboo: ["sideways", "pinch", "sea", "red", "shell"] },
  { word: "GOLDFISH",        taboo: ["orange", "bowl", "swim", "small", "pet"] },
  { word: "WILD BOAR",       taboo: ["tusk", "black", "forest", "charge", "snout"] },
  { word: "PEACOCK FEATHER", taboo: ["blue", "green", "eye", "collect", "pretty"] },
  { word: "PORCUPINE",       taboo: ["quill", "sharp", "poke", "small", "nocturnal"] },
  { word: "PANGOLIN",        taboo: ["scale", "curl", "ant", "armour", "India"] },
  { word: "HORNBILL",        taboo: ["large beak", "colourful", "India", "forest", "rare"] },
  { word: "PIGEON",          taboo: ["grey", "coo", "city", "flock", "message"] },
  { word: "BULLFROG",        taboo: ["large", "croak", "pond", "loud", "leaping"] },
  { word: "PELICAN",         taboo: ["pouch", "beak", "large", "water", "fish"] },

  // Indian Food & Drink
  { word: "PARATHA",         taboo: ["stuffed", "wheat", "flat", "butter", "breakfast"] },
  { word: "KULFI",           taboo: ["frozen", "sweet", "stick", "mango", "Indian"] },
  { word: "RASGULLA",        taboo: ["Bengali", "round", "spongy", "white", "syrup"] },
  { word: "BARFI",           taboo: ["milk", "festival", "sweet", "flat", "silver leaf"] },
  { word: "HALWA",           taboo: ["semolina", "sweet", "ghee", "festival", "soft"] },
  { word: "KHEER",           taboo: ["rice", "milk", "dessert", "creamy", "festival"] },
  { word: "UTTAPAM",         taboo: ["thick", "toppings", "crispy", "South", "rice"] },
  { word: "UPMA",            taboo: ["semolina", "breakfast", "South", "morning", "stir"] },
  { word: "RASAM",           taboo: ["pepper", "thin", "South", "tangy", "soup"] },
  { word: "SAMBHAR",         taboo: ["lentil", "vegetable", "spicy", "eat with idli", "South"] },
  { word: "MURUKKU",         taboo: ["spiral", "fried", "South", "crunchy", "snack"] },
  { word: "DHOKLA",          taboo: ["Gujarat", "spongy", "steam", "yellow", "snack"] },
  { word: "KACHORI",         taboo: ["round", "fried", "stuffed", "crispy", "Rajasthan"] },
  { word: "PANIPURI",        taboo: ["hollow", "crispy", "spicy water", "street", "round"] },
  { word: "BHELPURI",        taboo: ["puffed rice", "Mumbai", "tangy", "mix", "street"] },
  { word: "DAHI VADA",       taboo: ["yogurt", "fried", "tangy", "soft", "snack"] },
  { word: "ALOO TIKKI",      taboo: ["potato", "fried", "flat", "Delhi", "chaat"] },
  { word: "CHOLE",           taboo: ["chickpea", "spicy", "North", "curry", "gravy"] },
  { word: "BUTTERMILK",      taboo: ["cool", "yogurt", "drink", "sour", "summer"] },
  { word: "COCONUT WATER",   taboo: ["fresh", "cool", "sweet", "drink", "summer"] },
  { word: "SUGARCANE JUICE", taboo: ["sweet", "fresh", "press", "green", "drink"] },
  { word: "NIMBU PANI",      taboo: ["lemon", "drink", "fresh", "cool", "summer"] },
  { word: "AAMRAS",          taboo: ["mango", "sweet", "pulp", "Gujarat", "summer"] },
  { word: "SHRIKHAND",       taboo: ["thick", "sweet", "yogurt", "Gujarat", "dessert"] },
  { word: "MODAK",           taboo: ["Ganesh", "sweet", "steam", "Maharashtra", "festival"] },
  { word: "PEDA",            taboo: ["milk", "sweet", "round", "flat", "festival"] },
  { word: "CHIKKI",          taboo: ["peanut", "sweet", "hard", "sesame", "brittle"] },
  { word: "REWARI",          taboo: ["sesame", "sweet", "winter", "crispy", "North"] },
  { word: "GAJAR HALWA",     taboo: ["carrot", "sweet", "winter", "red", "cook"] },
  { word: "FALOODA",         taboo: ["rose", "milk", "sweet", "cold", "drink"] },
  { word: "NAAN",            taboo: ["bread", "tandoor", "soft", "North", "flat"] },
  { word: "KULCHA",          taboo: ["bread", "Punjab", "stuffed", "soft", "bake"] },
  { word: "BHATURA",         taboo: ["fried", "puffy", "North", "eat with chole", "bread"] },
  { word: "APPAM",           taboo: ["Kerala", "soft", "round", "coconut", "breakfast"] },
  { word: "VADA",            taboo: ["South", "fried", "donut shape", "crispy", "sambhar"] },
  { word: "THEPLA",          taboo: ["Gujarat", "flat", "thin", "travel", "spiced"] },
  { word: "PURAN POLI",      taboo: ["Maharashtra", "sweet", "flat", "festival", "stuffed"] },
  { word: "PESARATTU",       taboo: ["green", "moong", "South", "crispy", "pancake"] },
  { word: "BISI BELE BATH",  taboo: ["Karnataka", "rice", "lentil", "spicy", "hot"] },
  { word: "CURD RICE",       taboo: ["South", "white", "cool", "yogurt", "soft"] },
  { word: "LEMON RICE",      taboo: ["yellow", "tangy", "South", "tempered", "eat"] },
  { word: "TAMARIND",        taboo: ["sour", "brown", "pod", "tangy", "cook"] },
  { word: "TURMERIC",        taboo: ["yellow", "spice", "health", "powder", "cook"] },
  { word: "CARDAMOM",        taboo: ["spice", "green", "smell", "sweet", "cook"] },
  { word: "CINNAMON",        taboo: ["brown", "bark", "spice", "sweet", "roll"] },
  { word: "CLOVE",           taboo: ["small", "dark", "strong", "spice", "toothache"] },
  { word: "PEPPER",          taboo: ["black", "spice", "round", "hot", "grind"] },
  { word: "MUSTARD SEED",    taboo: ["tiny", "black", "spice", "fry", "tempering"] },
  { word: "FENNEL",          taboo: ["green", "mouth freshener", "seed", "sweet", "after meal"] },
  { word: "DRUMSTICK",       taboo: ["long", "vegetable", "South", "soup", "thin"] },
  { word: "BITTER GOURD",    taboo: ["bitter", "green", "vegetable", "healthy", "lumpy"] },
  { word: "LADY FINGER",     taboo: ["green", "sticky", "vegetable", "slender", "cook"] },
  { word: "BRINJAL",         taboo: ["purple", "vegetable", "cook", "soft", "curry"] },

  // Household Items
  { word: "PRESSURE COOKER", taboo: ["whistle", "kitchen", "steam", "cook", "fast"] },
  { word: "MIXER GRINDER",   taboo: ["blend", "electric", "kitchen", "spin", "grind"] },
  { word: "STEEL GLASS",     taboo: ["drink", "water", "shiny", "kitchen", "silver"] },
  { word: "CLAY POT",        taboo: ["water", "cool", "mud", "round", "village"] },
  { word: "AGARBATTI",       taboo: ["incense", "smoke", "smell", "temple", "burn"] },
  { word: "DIYA",            taboo: ["flame", "clay", "oil", "Diwali", "small"] },
  { word: "TAWA",            taboo: ["flat", "cook", "chapati", "hot", "kitchen"] },
  { word: "KADAI",           taboo: ["deep", "cook", "fry", "round", "kitchen"] },
  { word: "LADLE",           taboo: ["serve", "soup", "long", "stir", "kitchen"] },
  { word: "ROLLING PIN",     taboo: ["roll", "kitchen", "chapati", "round", "flat"] },
  { word: "MORTAR PESTLE",   taboo: ["grind", "stone", "spice", "heavy", "kitchen"] },
  { word: "MATCHBOX",        taboo: ["fire", "light", "small", "red", "strike"] },
  { word: "LANTERN",         taboo: ["light", "glass", "oil", "hang", "glow"] },
  { word: "SEWING MACHINE",  taboo: ["stitch", "cloth", "electric", "needle", "sew"] },
  { word: "SPINNING WHEEL",  taboo: ["charkha", "Gandhi", "cotton", "spin", "round"] },
  { word: "KNIFE",           taboo: ["sharp", "cut", "kitchen", "blade", "handle"] },
  { word: "GAS STOVE",       taboo: ["cook", "flame", "kitchen", "turn", "blue fire"] },
  { word: "FRIDGE",          taboo: ["cold", "store", "electric", "white", "kitchen"] },
  { word: "TELEVISION",      taboo: ["watch", "screen", "programme", "remote", "serials"] },
  { word: "MOSQUITO NET",    taboo: ["sleep", "protect", "hang", "mesh", "bite"] },
  { word: "IRON BOX",        taboo: ["press", "cloth", "hot", "flat", "crease"] },
  { word: "SOFA",            taboo: ["sit", "comfort", "living room", "soft", "cushion"] },
  { word: "WARDROBE",        taboo: ["store", "clothes", "wood", "door", "hang"] },
  { word: "BOOKSHELF",       taboo: ["books", "wood", "tall", "arrange", "library"] },
  { word: "WASHING MACHINE", taboo: ["wash", "electric", "clothes", "spin", "drum"] },
  { word: "WATER BOTTLE",    taboo: ["drink", "carry", "plastic", "school", "fill"] },
  { word: "JUTE BAG",        taboo: ["carry", "natural", "woven", "green", "shop"] },
  { word: "WOOL",            taboo: ["knit", "warm", "soft", "ball", "sheep"] },
  { word: "THREAD",          taboo: ["sew", "thin", "spool", "colour", "needle"] },
  { word: "NEEDLE",          taboo: ["sew", "sharp", "thin", "eye", "stitch"] },
  { word: "SAFETY PIN",      taboo: ["sharp", "hold", "small", "silver", "clip"] },
  { word: "RUBBER BAND",     taboo: ["stretch", "hold", "bundle", "thin", "snap"] },

  // Clothing & Accessories
  { word: "DHOTI",           taboo: ["white", "wrap", "man", "traditional", "legs"] },
  { word: "KURTA",           taboo: ["loose", "Indian", "wear", "cotton", "top"] },
  { word: "DUPATTA",         taboo: ["cloth", "drape", "woman", "head", "light"] },
  { word: "SALWAR",          taboo: ["bottom", "wear", "loose", "trouser", "India"] },
  { word: "ANKLET",          taboo: ["foot", "wear", "jingle", "woman", "silver"] },
  { word: "NOSE RING",       taboo: ["nose", "wear", "woman", "India", "pierce"] },
  { word: "NECKLACE",        taboo: ["neck", "wear", "gold", "chain", "jewellery"] },
  { word: "SHAWL",           taboo: ["shoulder", "warm", "wrap", "soft", "Kashmir"] },
  { word: "PAGDI",           taboo: ["head", "wrap", "colour", "Rajasthan", "cloth"] },
  { word: "SANDAL",          taboo: ["foot", "open", "wear", "flat", "strap"] },
  { word: "FLIP FLOPS",      taboo: ["foot", "rubber", "flat", "simple", "slippers"] },
  { word: "MOJRI",           taboo: ["leather", "foot", "pointed", "Rajasthan", "decorated"] },
  { word: "KURTI",           taboo: ["short", "woman", "India", "cotton", "colourful"] },
  { word: "WAISTBAND",       taboo: ["waist", "cloth", "wrap", "colour", "Indian"] },

  // Transport
  { word: "MOTOR BIKE",      taboo: ["two wheel", "engine", "fast", "ride", "road"] },
  { word: "TRACTOR",         taboo: ["farm", "engine", "pull", "loud", "field"] },
  { word: "CYCLE RICKSHAW",  taboo: ["pedal", "three wheel", "carry", "city", "passenger"] },
  { word: "FISHING BOAT",    taboo: ["sea", "small", "net", "catch", "sailor"] },
  { word: "HOUSEBOAT",       taboo: ["Kashmir", "float", "live", "water", "Dal Lake"] },
  { word: "METRO TRAIN",     taboo: ["city", "fast", "electric", "underground", "stop"] },
  { word: "CABLE CAR",       taboo: ["mountain", "hang", "travel", "scenic", "pull"] },
  { word: "FERRY",           taboo: ["river", "large", "carry", "water", "cross"] },
  { word: "HAND CART",       taboo: ["push", "sell", "road", "vendor", "goods"] },

  // Sports & Games
  { word: "POLO",            taboo: ["horse", "stick", "ball", "goal", "sport"] },
  { word: "ARCHERY",         taboo: ["bow", "arrow", "aim", "target", "shoot"] },
  { word: "MALLAKHAMB",      taboo: ["pole", "gym", "traditional", "India", "climb"] },
  { word: "SKIPPING ROPE",   taboo: ["jump", "skip", "play", "count", "children"] },
  { word: "SACK RACE",       taboo: ["bag", "jump", "hop", "fun", "play"] },
  { word: "GILLI DANDA",     taboo: ["stick", "hit", "play", "outdoor", "village"] },
  { word: "PITTOO",          taboo: ["stone", "stack", "hit", "ball", "children"] },
  { word: "CRICKET BAT",     taboo: ["wood", "flat", "hit", "play", "willow"] },
  { word: "HOCKEY STICK",    taboo: ["hockey", "hit", "curved", "play", "sport"] },
  { word: "STUMPS",          taboo: ["cricket", "wicket", "three", "hit", "wood"] },
  { word: "SWIMSUIT",        taboo: ["swim", "pool", "wear", "water", "tight"] },
  { word: "RACING CAR",      taboo: ["fast", "motor", "track", "compete", "driver"] },
  { word: "WRESTLING MAT",   taboo: ["fight", "hold", "throw", "sport", "flat"] },

  // Nature & Places
  { word: "PADDY FIELD",     taboo: ["rice", "grow", "water", "green", "farm"] },
  { word: "COCONUT GROVE",   taboo: ["Kerala", "tall", "beach", "tree", "fruit"] },
  { word: "VILLAGE WELL",    taboo: ["water", "round", "deep", "draw", "village"] },
  { word: "POND",            taboo: ["small", "water", "fish", "lotus", "still"] },
  { word: "HILL STATION",    taboo: ["cool", "mountain", "travel", "misty", "India"] },
  { word: "SALT FLAT",       taboo: ["white", "Gujarat", "vast", "dry", "bright"] },
  { word: "VALLEY",          taboo: ["low", "between hills", "river", "green", "peaceful"] },
  { word: "CLIFF",           taboo: ["steep", "high", "rock", "fall", "edge"] },
  { word: "LIGHTHOUSE",      taboo: ["tall", "sea", "light", "ship", "guide"] },
  { word: "WHEAT FARM",      taboo: ["yellow", "harvest", "Punjab", "grain", "grow"] },
  { word: "ORCHARD",         taboo: ["fruit", "tree", "grow", "pick", "garden"] },
  { word: "TEA PLANTATION",  taboo: ["Assam", "green", "hill", "Darjeeling", "pick"] },
  { word: "WATERMILL",       taboo: ["water", "grind", "old", "village", "turn"] },
  { word: "CANAL",           taboo: ["water", "dug", "flat", "irrigate", "long"] },
  { word: "DAM",             taboo: ["water", "block", "river", "tall", "concrete"] },
  { word: "RAILWAY STATION", taboo: ["train", "platform", "crowd", "ticket", "arrive"] },
  { word: "HARBOUR",         taboo: ["ship", "water", "dock", "port", "coast"] },
  { word: "HOT SPRING",      taboo: ["warm", "water", "natural", "mineral", "bathe"] },
  { word: "DELTA",           taboo: ["river mouth", "flat", "fertile", "India", "fish"] },
  { word: "PLATEAU",         taboo: ["flat", "high", "land", "Deccan", "India"] },

  // Famous Indian Things & Symbols
  { word: "CHARKHA",         taboo: ["spin", "Gandhi", "cotton", "wheel", "freedom"] },
  { word: "TRICOLOUR",       taboo: ["three", "flag", "saffron", "green", "Ashoka"] },
  { word: "MARIGOLD",        taboo: ["orange", "garland", "temple", "flower", "India"] },
  { word: "HIBISCUS",        taboo: ["red", "tropical", "large", "flower", "Kerala"] },
  { word: "BOUGAINVILLEA",   taboo: ["colourful", "thorny", "climbing", "flower", "bright"] },
  { word: "ONE-HORNED RHINO",taboo: ["Assam", "thick", "horn", "large", "grey"] },
  { word: "SNOW LEOPARD",    taboo: ["mountain", "white", "spot", "Himalaya", "rare"] },
  { word: "ROYAL BENGAL TIGER",taboo:["stripe", "national", "Bengal", "big cat", "forest"] },
  { word: "GREAT INDIAN BUSTARD",taboo:["bird", "large", "Rajasthan", "rare", "ground"] },

  // School & Education
  { word: "EXAM",            taboo: ["study", "write", "test", "marks", "nervous"] },
  { word: "BLACKBOARD",      taboo: ["write", "chalk", "class", "green", "teacher"] },
  { word: "CHALK",           taboo: ["white", "write", "board", "powder", "stick"] },
  { word: "COMPASS",         taboo: ["draw", "circle", "sharp", "point", "geometry"] },
  { word: "PROTRACTOR",      taboo: ["angle", "measure", "half circle", "geometry", "flat"] },
  { word: "ATLAS",           taboo: ["maps", "countries", "book", "geography", "look"] },
  { word: "ABACUS",          taboo: ["count", "beads", "old", "calculate", "frame"] },
  { word: "REPORT CARD",     taboo: ["marks", "school", "grade", "parent", "result"] },
  { word: "SPORTS DAY",      taboo: ["school", "race", "run", "compete", "annual"] },
  { word: "SCHOOL UNIFORM",  taboo: ["wear", "same", "dress", "school", "neat"] },

  // Body Parts (simple)
  { word: "THUMB",           taboo: ["hand", "press", "five", "print", "up"] },
  { word: "ELBOW",           taboo: ["bend", "arm", "lean", "joint", "point"] },
  { word: "KNEE",            taboo: ["bend", "leg", "joint", "hurt", "walk"] },
  { word: "FINGERNAIL",      taboo: ["grow", "cut", "paint", "hand", "sharp"] },
  { word: "SHOULDER",        taboo: ["arm", "carry", "shrug", "top", "body"] },

  // Miscellaneous Everyday Places
  { word: "PHARMACY",        taboo: ["medicine", "buy", "shop", "pill", "chemist"] },
  { word: "BANK",            taboo: ["money", "save", "loan", "account", "ATM"] },
  { word: "POST OFFICE",     taboo: ["letter", "stamp", "send", "mail", "post"] },
  { word: "LIBRARY",         taboo: ["books", "read", "quiet", "borrow", "shelf"] },
  { word: "MUSEUM",          taboo: ["history", "exhibit", "old", "display", "art"] },
  { word: "ZOO",             taboo: ["animal", "cage", "visit", "keeper", "wild"] },
  { word: "AQUARIUM",        taboo: ["fish", "water", "glass", "tank", "swim"] },
  { word: "PLAYGROUND",      taboo: ["children", "play", "outdoor", "fun", "run"] },
  { word: "STADIUM",         taboo: ["match", "large", "crowd", "seats", "sport"] },
  { word: "CINEMA",          taboo: ["movie", "screen", "ticket", "dark", "watch"] },
  { word: "HOTEL",           taboo: ["stay", "room", "eat", "travel", "sleep"] },
  { word: "TENT",            taboo: ["camp", "outdoor", "sleep", "adventure", "canvas"] },

  // More Fruits & Vegetables
  { word: "JACKFRUIT",       taboo: ["big", "spiky", "yellow", "India", "tropical"] },
  { word: "PAPAYA",          taboo: ["orange", "tropical", "soft", "sweet", "oblong"] },
  { word: "CUSTARD APPLE",   taboo: ["creamy", "sweet", "soft", "seeds", "green"] },
  { word: "SAPOTA",          taboo: ["brown", "sweet", "soft", "chiku", "fruit"] },
  { word: "STAR FRUIT",      taboo: ["star shape", "yellow", "sour", "tropical", "fruit"] },
  { word: "ASH GOURD",       taboo: ["white", "large", "India", "vegetable", "green"] },
  { word: "RIDGE GOURD",     taboo: ["long", "ridged", "green", "vegetable", "India"] },
  { word: "CLUSTER BEANS",   taboo: ["green", "thin", "India", "vegetable", "cook"] },
  { word: "RAW BANANA",      taboo: ["green", "cook", "vegetable", "South", "unripe"] },
  { word: "LOTUS STEM",      taboo: ["river", "hollow", "vegetable", "flower", "Indian"] },

  // More Outdoor Nature Items
  { word: "ANTHILL",         taboo: ["ant", "mound", "sand", "small", "colony"] },
  { word: "BEEHIVE",         taboo: ["bee", "honey", "wax", "hang", "comb"] },
  { word: "SPIDER WEB",      taboo: ["sticky", "spider", "trap", "fine", "silk"] },
  { word: "BIRD NEST",       taboo: ["bird", "egg", "twig", "build", "tree"] },
  { word: "MUD",             taboo: ["wet", "soil", "dirty", "stick", "brown"] },
  { word: "PEBBLE",          taboo: ["small", "smooth", "stone", "river", "round"] },
  { word: "SHELL",           taboo: ["sea", "spiral", "hard", "beach", "inside"] },
  { word: "LEAF",            taboo: ["tree", "green", "fall", "flat", "plant"] },
  { word: "THORN",           taboo: ["prick", "rose", "sharp", "plant", "hurt"] },
  { word: "SEED",            taboo: ["plant", "grow", "small", "sow", "soil"] },
  { word: "MUSHROOM",        taboo: ["umbrella shape", "forest", "fungi", "cook", "grow"] },
  { word: "BAMBOO SHOOT",    taboo: ["young", "eat", "Northeast", "bamboo", "cook"] },

  // More Games & Activities
  { word: "RANGOLI",         taboo: ["floor", "colour", "design", "festival", "draw"] },
  { word: "ORIGAMI",         taboo: ["fold", "paper", "Japan", "shape", "art"] },
  { word: "PUPPET SHOW",     taboo: ["puppet", "string", "hand", "story", "perform"] },
  { word: "MAGIC SHOW",      taboo: ["trick", "disappear", "hat", "rabbit", "wow"] },
  { word: "TREASURE HUNT",   taboo: ["find", "clue", "hide", "team", "prize"] },
  { word: "DRAWING",         taboo: ["pencil", "paper", "colour", "sketch", "art"] },
  { word: "PAINTING",        taboo: ["brush", "colour", "canvas", "art", "draw"] },
  { word: "DANCE",           taboo: ["move", "music", "step", "rhythm", "perform"] },
  { word: "SINGING",         taboo: ["voice", "song", "tune", "melody", "perform"] },
  { word: "STORYTELLING",    taboo: ["tale", "tell", "listen", "imagination", "characters"] },

  // More Indian Symbols / Culture
  { word: "KOLAM",           taboo: ["floor", "white", "South", "pattern", "morning"] },
  { word: "DEEPAM",          taboo: ["lamp", "South", "oil", "flame", "festival"] },
  { word: "TILAK",           taboo: ["forehead", "paste", "red", "Hindu", "ceremony"] },
  { word: "KUMKUM",          taboo: ["red", "powder", "forehead", "woman", "India"] },
  { word: "CONCH SHELL",     taboo: ["temple", "blow", "white", "worship", "sound"] },
  { word: "DHOOP",           taboo: ["incense", "smoke", "thick", "temple", "smell"] },
  { word: "CAMPHOR",         taboo: ["burn", "aarti", "white", "smell", "flame"] },
  { word: "SANDALWOOD",      taboo: ["paste", "smell", "temple", "yellow", "Karnataka"] },
  { word: "VERMILION",       taboo: ["red", "powder", "Hindu", "married", "forehead"] },

  // More Simple Famous Places
  { word: "GATEWAY",         taboo: ["arch", "entrance", "Mumbai", "large", "British"] },
  { word: "FORT",            taboo: ["stone", "wall", "tall", "protect", "old"] },
  { word: "PALACE",          taboo: ["king", "large", "royal", "beautiful", "old"] },
  { word: "GHAT",            taboo: ["steps", "river", "bathe", "holy", "Varanasi"] },
  { word: "MANGROVE",        taboo: ["coastal", "roots", "tree", "water", "Sundarbans"] },
  { word: "HOT AIR BALLOON", taboo: ["float", "air", "basket", "sky", "colourful"] },
  { word: "WINDMILL",        taboo: ["wind", "spin", "energy", "tall", "blades"] },
  { word: "WATER TANK",      taboo: ["store", "water", "roof", "large", "supply"] },

  // More Simple Objects
  { word: "MAGNIFYING GLASS",taboo: ["large", "look", "small things", "inspect", "burn"] },
  { word: "BINOCULARS",      taboo: ["far", "look", "birds", "two lenses", "nature"] },
  { word: "COMPASS DIAL",    taboo: ["direction", "North", "magnetic", "navigate", "hike"] },
  { word: "TELESCOPE",       taboo: ["star", "far", "sky", "big", "astronomer"] },
  { word: "THERMOMETER",     taboo: ["temperature", "fever", "measure", "degree", "sick"] },
  { word: "STETHOSCOPE",     taboo: ["doctor", "heart", "listen", "beat", "hospital"] },
  { word: "BANDAGE",         taboo: ["wrap", "wound", "white", "heal", "sticky"] },
  { word: "INJECTION",       taboo: ["needle", "medicine", "doctor", "pain", "syringe"] },
  { word: "PILL",            taboo: ["medicine", "round", "swallow", "sick", "tablet"] },
  { word: "FIRST AID BOX",   taboo: ["red cross", "emergency", "medicine", "kit", "help"] },
  { word: "TORCH BATTERY",   taboo: ["power", "small", "cylinder", "charge", "cell"] },
  { word: "POWER SOCKET",    taboo: ["electric", "plug", "wall", "charge", "hole"] },
  { word: "LIGHT SWITCH",    taboo: ["on off", "wall", "click", "electric", "button"] },
  { word: "FIRE EXTINGUISHER",taboo:["red", "spray", "fire", "emergency", "foam"] },
  { word: "DUSTPAN",         taboo: ["sweep", "collect", "dirt", "flat", "broom"] },
  { word: "MOP",             taboo: ["wet", "floor", "clean", "push", "bucket"] },
  { word: "COLANDER",        taboo: ["drain", "holes", "pasta", "wash", "kitchen"] },
  { word: "PEELER",          taboo: ["skin", "vegetable", "peel", "thin", "strip"] },
  { word: "GRATER",          taboo: ["grate", "cheese", "vegetable", "holes", "rub"] },
  { word: "TONGS",           taboo: ["pick", "hot", "grip", "BBQ", "two arms"] },
  { word: "MEASURING CUP",   taboo: ["cook", "quantity", "fill", "liquid", "bake"] },
  { word: "APRON",           taboo: ["kitchen", "protect", "tie", "cook", "front"] },
  { word: "OVEN GLOVES",     taboo: ["hot", "protect", "oven", "kitchen", "pair"] },
  { word: "RECIPE BOOK",     taboo: ["cook", "instructions", "kitchen", "read", "dish"] },
  { word: "SHOPPING CART",   taboo: ["push", "supermarket", "buy", "wheel", "groceries"] },
  { word: "PRICE TAG",       taboo: ["amount", "cost", "stick", "shop", "label"] },
  { word: "RECEIPT",         taboo: ["buy", "pay", "print", "amount", "shop"] },
  { word: "QUEUE",           taboo: ["line", "wait", "stand", "turn", "India"] },
  { word: "VEGETABLE MARKET",taboo: ["fresh", "buy", "green", "sell", "vegetables"] },
  { word: "FLOWER MARKET",   taboo: ["sell", "colourful", "smell", "fresh", "morning"] },
  { word: "AUTO STAND",      taboo: ["wait", "rickshaw", "hire", "road", "city"] },
  { word: "PETROL PUMP",     taboo: ["fuel", "fill", "car", "station", "queue"] },
  { word: "TRAFFIC LIGHT",   taboo: ["red", "green", "stop", "road", "signal"] },
  { word: "SPEED BREAKER",   taboo: ["slow", "road", "hump", "bump", "drive"] },
  { word: "CROSSING",        taboo: ["road", "pedestrian", "zebra", "cross", "stripes"] },
];
