// words/hard.js — Hard difficulty word bank (52 cards)
// Abstract and complex concepts — for adults and competitive players

const WORDS_HARD = [
  { word: "DEMOCRACY",            taboo: ["vote", "election", "government", "people", "republic"] },
  { word: "CONSTITUTION",         taboo: ["law", "rights", "document", "India", "fundamental"] },
  { word: "INDEPENDENCE",         taboo: ["freedom", "1947", "British", "partition", "August"] },
  { word: "SECULARISM",           taboo: ["religion", "equal", "state", "neutral", "faith"] },
  { word: "JUDICIARY",            taboo: ["court", "law", "judge", "justice", "supreme"] },
  { word: "PHOTOSYNTHESIS",       taboo: ["plant", "sun", "food", "chlorophyll", "oxygen"] },
  { word: "GRAVITY",              taboo: ["fall", "weight", "Newton", "earth", "force"] },
  { word: "EVOLUTION",            taboo: ["Darwin", "species", "adapt", "change", "survival"] },
  { word: "INFLATION",            taboo: ["price", "rise", "economy", "money", "rate"] },
  { word: "GLOBALISATION",        taboo: ["world", "trade", "connect", "international", "economy"] },
  { word: "ECOSYSTEM",            taboo: ["nature", "balance", "food chain", "environment", "life"] },
  { word: "BUREAUCRACY",          taboo: ["government", "office", "process", "file", "rule"] },
  { word: "PARTITION",            taboo: ["1947", "divide", "India", "Pakistan", "border"] },
  { word: "SOVEREIGNTY",          taboo: ["power", "independent", "country", "authority", "rule"] },
  { word: "GREEN REVOLUTION",     taboo: ["wheat", "farm", "India", "food", "production"] },
  { word: "NUCLEAR ENERGY",       taboo: ["atom", "power", "reactor", "radiation", "bomb"] },
  { word: "ARTIFICIAL INTELLIGENCE", taboo: ["machine", "computer", "smart", "robot", "learn"] },
  { word: "CLIMATE CHANGE",       taboo: ["global", "warm", "carbon", "environment", "crisis"] },
  { word: "BIODIVERSITY",         taboo: ["species", "nature", "variety", "ecosystem", "life"] },
  { word: "QUANTUM PHYSICS",      taboo: ["atom", "particle", "energy", "science", "wave"] },
  { word: "COLONIALISM",          taboo: ["British", "rule", "empire", "exploit", "history"] },
  { word: "RENAISSANCE",          taboo: ["art", "Europe", "rebirth", "culture", "history"] },
  { word: "MYTHOLOGY",            taboo: ["god", "story", "ancient", "legend", "epic"] },
  { word: "ARCHAEOLOGY",          taboo: ["dig", "ancient", "artefact", "history", "fossil"] },
  { word: "PHILOSOPHY",           taboo: ["think", "wisdom", "life", "truth", "question"] },
  { word: "CARTOGRAPHY",          taboo: ["map", "draw", "geography", "explore", "chart"] },
  { word: "EPIDEMIOLOGY",         taboo: ["disease", "spread", "study", "outbreak", "health"] },
  { word: "GEOPOLITICS",          taboo: ["country", "power", "border", "politics", "world"] },
  { word: "INDUSTRIALISATION",    taboo: ["factory", "machine", "produce", "growth", "urban"] },
  { word: "URBANISATION",         taboo: ["city", "migrate", "grow", "rural", "population"] },
  { word: "FEMINISM",             taboo: ["women", "equal", "rights", "movement", "gender"] },
  { word: "LIBERALISATION",       taboo: ["open", "economy", "1991", "reform", "India"] },
  { word: "PRIVATISATION",        taboo: ["company", "sell", "government", "private", "economy"] },
  { word: "RESERVATION SYSTEM",   taboo: ["caste", "quota", "college", "job", "India"] },
  { word: "WELFARE STATE",        taboo: ["government", "care", "provide", "citizen", "service"] },
  { word: "FEDERALISM",           taboo: ["state", "central", "power", "government", "share"] },
  { word: "RECESSION",            taboo: ["money", "fall", "jobs", "crisis", "GDP"] },
  { word: "SUSTAINABLE DEVELOPMENT", taboo: ["future", "green", "resource", "balance", "grow"] },
  { word: "NANOTECHNOLOGY",       taboo: ["tiny", "science", "machine", "atom", "future"] },
  { word: "BIOTECHNOLOGY",        taboo: ["gene", "science", "medicine", "DNA", "life"] },
  { word: "NATIONALISM",          taboo: ["country", "pride", "identity", "patriot", "love"] },
  { word: "CASTE SYSTEM",         taboo: ["hierarchy", "India", "birth", "social", "varna"] },
  { word: "FUNDAMENTAL RIGHTS",   taboo: ["constitution", "freedom", "India", "guarantee", "citizen"] },
  { word: "PANCHAYATI RAJ",       taboo: ["village", "self", "govern", "rural", "India"] },
  { word: "NON-COOPERATION",      taboo: ["Gandhi", "British", "resist", "peaceful", "movement"] },
  { word: "SWADESHI",             taboo: ["Indian", "goods", "boycott", "independence", "Gandhi"] },
  { word: "SEPOY MUTINY",         taboo: ["1857", "British", "soldier", "revolt", "India"] },
  { word: "TECTONIC PLATES",      taboo: ["earth", "move", "earthquake", "crust", "geography"] },
  { word: "ZERO",                 taboo: ["number", "India", "nothing", "mathematics", "Aryabhata"] },
  { word: "AYURVEDA",             taboo: ["ancient", "medicine", "herb", "India", "natural"] },
  { word: "MONSOON ECONOMY",      taboo: ["rain", "farm", "India", "depend", "season"] },
  { word: "SPACE RESEARCH",       taboo: ["ISRO", "rocket", "satellite", "moon", "orbit"] },
];
