// words/hard.js — Hard difficulty word bank (52 cards)
// Abstract and complex concepts — for adults and competitive players

const WORDS_HARD = [
  { word: "DEMOCRACY",            taboo: ["vote", "election", "government", "people", "republic"] },
  { word: "CONSTITUTION",         taboo: ["law", "rights", "document", "India", "fundamental"] },
  { word: "INDEPENDENCE",         taboo: ["freedom", "1947", "British", "partition", "August"] },
  { word: "SECULARISM",           taboo: ["religion", "equal", "state", "neutral", "faith"] },
  { word: "JUDICIARY",            taboo: ["court", "law", "judge", "justice", "supreme"] },
  { word: "PHOTOSYNTHESIS",       taboo: ["plant", "sun", "food", "chlorophyll", "oxygen"] },
  { word: "GRAVITY",              taboo: ["fall", "weight", "Newton", "earth", "force"] },
  { word: "EVOLUTION",            taboo: ["Darwin", "species", "adapt", "change", "survival"] },
  { word: "INFLATION",            taboo: ["price", "rise", "economy", "money", "rate"] },
  { word: "GLOBALISATION",        taboo: ["world", "trade", "connect", "international", "economy"] },
  { word: "ECOSYSTEM",            taboo: ["nature", "balance", "food chain", "environment", "life"] },
  { word: "BUREAUCRACY",          taboo: ["government", "office", "process", "file", "rule"] },
  { word: "PARTITION",            taboo: ["1947", "divide", "India", "Pakistan", "border"] },
  { word: "SOVEREIGNTY",          taboo: ["power", "independent", "country", "authority", "rule"] },
  { word: "GREEN REVOLUTION",     taboo: ["wheat", "farm", "India", "food", "production"] },
  { word: "NUCLEAR ENERGY",       taboo: ["atom", "power", "reactor", "radiation", "bomb"] },
  { word: "ARTIFICIAL INTELLIGENCE", taboo: ["machine", "computer", "smart", "robot", "learn"] },
  { word: "CLIMATE CHANGE",       taboo: ["global", "warm", "carbon", "environment", "crisis"] },
  { word: "BIODIVERSITY",         taboo: ["species", "nature", "variety", "ecosystem", "life"] },
  { word: "QUANTUM PHYSICS",      taboo: ["atom", "particle", "energy", "science", "wave"] },
  { word: "COLONIALISM",          taboo: ["British", "rule", "empire", "exploit", "history"] },
  { word: "RENAISSANCE",          taboo: ["art", "Europe", "rebirth", "culture", "history"] },
  { word: "MYTHOLOGY",            taboo: ["god", "story", "ancient", "legend", "epic"] },
  { word: "ARCHAEOLOGY",          taboo: ["dig", "ancient", "artefact", "history", "fossil"] },
  { word: "PHILOSOPHY",           taboo: ["think", "wisdom", "life", "truth", "question"] },
  { word: "CARTOGRAPHY",          taboo: ["map", "draw", "geography", "explore", "chart"] },
  { word: "EPIDEMIOLOGY",         taboo: ["disease", "spread", "study", "outbreak", "health"] },
  { word: "GEOPOLITICS",          taboo: ["country", "power", "border", "politics", "world"] },
  { word: "INDUSTRIALISATION",    taboo: ["factory", "machine", "produce", "growth", "urban"] },
  { word: "URBANISATION",         taboo: ["city", "migrate", "grow", "rural", "population"] },
  { word: "FEMINISM",             taboo: ["women", "equal", "rights", "movement", "gender"] },
  { word: "LIBERALISATION",       taboo: ["open", "economy", "1991", "reform", "India"] },
  { word: "PRIVATISATION",        taboo: ["company", "sell", "government", "private", "economy"] },
  { word: "RESERVATION SYSTEM",   taboo: ["caste", "quota", "college", "job", "India"] },
  { word: "WELFARE STATE",        taboo: ["government", "care", "provide", "citizen", "service"] },
  { word: "FEDERALISM",           taboo: ["state", "central", "power", "government", "share"] },
  { word: "RECESSION",            taboo: ["money", "fall", "jobs", "crisis", "GDP"] },
  { word: "SUSTAINABLE DEVELOPMENT", taboo: ["future", "green", "resource", "balance", "grow"] },
  { word: "NANOTECHNOLOGY",       taboo: ["tiny", "science", "machine", "atom", "future"] },
  { word: "BIOTECHNOLOGY",        taboo: ["gene", "science", "medicine", "DNA", "life"] },
  { word: "NATIONALISM",          taboo: ["country", "pride", "identity", "patriot", "love"] },
  { word: "CASTE SYSTEM",         taboo: ["hierarchy", "India", "birth", "social", "varna"] },
  { word: "FUNDAMENTAL RIGHTS",   taboo: ["constitution", "freedom", "India", "guarantee", "citizen"] },
  { word: "PANCHAYATI RAJ",       taboo: ["village", "self", "govern", "rural", "India"] },
  { word: "NON-COOPERATION",      taboo: ["Gandhi", "British", "resist", "peaceful", "movement"] },
  { word: "SWADESHI",             taboo: ["Indian", "goods", "boycott", "independence", "Gandhi"] },
  { word: "SEPOY MUTINY",         taboo: ["1857", "British", "soldier", "revolt", "India"] },
  { word: "TECTONIC PLATES",      taboo: ["earth", "move", "earthquake", "crust", "geography"] },
  { word: "ZERO",                 taboo: ["number", "India", "nothing", "mathematics", "Aryabhata"] },
  { word: "AYURVEDA",             taboo: ["ancient", "medicine", "herb", "India", "natural"] },
  { word: "MONSOON ECONOMY",      taboo: ["rain", "farm", "India", "depend", "season"] },
  { word: "SPACE RESEARCH",       taboo: ["ISRO", "rocket", "satellite", "moon", "orbit"] },

  // ── 100 additional hard words ──────────────────────────────────────────
  { word: "EXISTENTIALISM",           taboo: ["philosophy", "existence", "meaning", "Sartre", "choice"] },
  { word: "UTILITARIANISM",           taboo: ["greatest", "good", "happiness", "philosophy", "ethics"] },
  { word: "MARXISM",                  taboo: ["class", "worker", "revolution", "communism", "Karl"] },
  { word: "CAPITALISM",               taboo: ["profit", "market", "private", "wealth", "free"] },
  { word: "COMMUNISM",                taboo: ["equal", "class", "state", "revolution", "Karl"] },
  { word: "SOCIALISM",                taboo: ["equal", "share", "government", "welfare", "people"] },
  { word: "FASCISM",                  taboo: ["authoritarian", "extreme", "nation", "control", "leader"] },
  { word: "TOTALITARIANISM",          taboo: ["absolute", "control", "state", "freedom", "dictator"] },
  { word: "THEOCRACY",                taboo: ["god", "rule", "religion", "state", "law"] },
  { word: "OLIGARCHY",                taboo: ["few", "rule", "power", "elite", "group"] },
  { word: "MERITOCRACY",              taboo: ["merit", "talent", "deserve", "earn", "position"] },
  { word: "SEPARATION OF POWERS",     taboo: ["legislature", "executive", "judiciary", "balance", "government"] },
  { word: "CHECKS AND BALANCES",      taboo: ["power", "limit", "government", "branch", "control"] },
  { word: "REFERENDUM",               taboo: ["people", "vote", "direct", "question", "democracy"] },
  { word: "GERRYMANDERING",           taboo: ["boundary", "manipulate", "vote", "unfair", "district"] },
  { word: "COLD WAR",                 taboo: ["USA", "USSR", "tension", "nuclear", "ideology"] },
  { word: "GLASNOST",                 taboo: ["openness", "Soviet", "Gorbachev", "reform", "transparency"] },
  { word: "PERESTROIKA",              taboo: ["reform", "Soviet", "Gorbachev", "economy", "restructure"] },
  { word: "HEGEMONY",                 taboo: ["dominant", "power", "influence", "control", "leader"] },
  { word: "SOFT POWER",               taboo: ["culture", "influence", "attract", "diplomacy", "non-military"] },
  { word: "REALPOLITIK",              taboo: ["practical", "power", "politics", "interest", "national"] },
  { word: "BALANCE OF POWER",         taboo: ["equal", "nations", "prevent", "dominate", "system"] },
  { word: "DETERRENCE",               taboo: ["prevent", "threaten", "military", "nuclear", "attack"] },
  { word: "ARMS RACE",                taboo: ["weapon", "compete", "build", "Cold War", "military"] },
  { word: "DISARMAMENT",              taboo: ["reduce", "weapon", "military", "peace", "treaty"] },
  { word: "SANCTIONS",                taboo: ["punish", "country", "trade", "restrict", "economy"] },
  { word: "EMBARGO",                  taboo: ["block", "trade", "export", "punish", "restrict"] },
  { word: "TARIFF",                   taboo: ["tax", "import", "trade", "protect", "border"] },
  { word: "FREE TRADE",               taboo: ["no barrier", "import", "export", "global", "WTO"] },
  { word: "PROTECTIONISM",            taboo: ["protect", "domestic", "tariff", "industry", "trade"] },
  { word: "KEYNESIAN ECONOMICS",      taboo: ["government", "spend", "recession", "stimulate", "Keynes"] },
  { word: "FISCAL POLICY",            taboo: ["government", "tax", "spend", "budget", "economy"] },
  { word: "MONETARY POLICY",          taboo: ["RBI", "interest", "inflation", "money", "supply"] },
  { word: "STAGFLATION",              taboo: ["stagnant", "inflation", "economy", "problem", "growth"] },
  { word: "TRADE DEFICIT",            taboo: ["import", "more", "export", "less", "balance"] },
  { word: "FOREIGN DIRECT INVESTMENT",taboo: ["company", "invest", "another", "country", "business"] },
  { word: "HUMAN DEVELOPMENT INDEX",  taboo: ["education", "health", "income", "country", "rank"] },
  { word: "GINI COEFFICIENT",         taboo: ["inequality", "income", "measure", "distribution", "society"] },
  { word: "SOCIAL CONTRACT",          taboo: ["people", "government", "agree", "rights", "Rousseau"] },
  { word: "CIVIL DISOBEDIENCE",       taboo: ["law", "refuse", "peaceful", "Gandhi", "protest"] },
  { word: "SATYAGRAHA",               taboo: ["truth", "force", "Gandhi", "nonviolent", "resistance"] },
  { word: "AHIMSA",                   taboo: ["nonviolence", "Gandhi", "harm", "principle", "life"] },
  { word: "SWARAJ",                   taboo: ["self", "rule", "independence", "Gandhi", "India"] },
  { word: "DANDI MARCH",              taboo: ["salt", "Gandhi", "sea", "walk", "protest"] },
  { word: "QUIT INDIA MOVEMENT",      taboo: ["British", "leave", "India", "Gandhi", "1942"] },
  { word: "ROWLATT ACT",              taboo: ["British", "suppress", "India", "law", "protest"] },
  { word: "JALLIANWALA BAGH",         taboo: ["massacre", "Amritsar", "British", "1919", "General Dyer"] },
  { word: "HOME RULE MOVEMENT",       taboo: ["Tilak", "Besant", "India", "govern", "British"] },
  { word: "LUCKNOW PACT",             taboo: ["Congress", "League", "unity", "1916", "Hindu Muslim"] },
  { word: "POONA PACT",               taboo: ["Ambedkar", "Gandhi", "1932", "separate", "electorate"] },
  { word: "MOUNTBATTEN PLAN",         taboo: ["1947", "partition", "independence", "British", "India"] },
  { word: "INTEGRATION OF PRINCELY STATES", taboo: ["Patel", "unite", "India", "state", "five hundred"] },
  { word: "EMERGENCY 1975",           taboo: ["Indira", "suspend", "rights", "1975", "press"] },
  { word: "MANDAL COMMISSION",        taboo: ["OBC", "reservation", "1990", "India", "caste"] },
  { word: "ECONOMIC REFORMS 1991",    taboo: ["liberalise", "IMF", "India", "open", "economy"] },
  { word: "PREAMBLE",                 taboo: ["constitution", "introduction", "India", "begin", "words"] },
  { word: "DIRECTIVE PRINCIPLES",     taboo: ["constitution", "guide", "state", "policy", "rights"] },
  { word: "AMENDMENT",                taboo: ["change", "constitution", "law", "modify", "parliament"] },
  { word: "PARLIAMENTARY SYSTEM",     taboo: ["PM", "cabinet", "majority", "govern", "Westminster"] },
  { word: "PRESIDENTIAL SYSTEM",      taboo: ["president", "executive", "USA", "separate", "elect"] },
  { word: "BICAMERALISM",             taboo: ["two", "house", "parliament", "Rajya Sabha", "Lok Sabha"] },
  { word: "UNIVERSAL ADULT FRANCHISE",taboo: ["every", "adult", "vote", "election", "right"] },
  { word: "CIVIL SERVICES",           taboo: ["IAS", "IPS", "government", "officer", "exam"] },
  { word: "RTI ACT",                  taboo: ["information", "right", "government", "ask", "India"] },
  { word: "JUDICIAL REVIEW",          taboo: ["court", "check", "law", "constitution", "power"] },
  { word: "PUBLIC INTEREST LITIGATION",taboo: ["court", "public", "petition", "India", "law"] },
  { word: "SEDITION",                 taboo: ["against", "government", "law", "speech", "punish"] },
  { word: "SOVEREIGNTY OF PARLIAMENT",taboo: ["supreme", "law", "parliament", "authority", "constitution"] },
  { word: "RADIOACTIVITY",            taboo: ["atom", "decay", "radiation", "nuclear", "energy"] },
  { word: "ELECTROMAGNETIC SPECTRUM", taboo: ["light", "wave", "radio", "X-ray", "frequency"] },
  { word: "THERMODYNAMICS",           taboo: ["heat", "energy", "law", "physics", "transfer"] },
  { word: "RELATIVITY",               taboo: ["Einstein", "space", "time", "speed", "light"] },
  { word: "DARK MATTER",              taboo: ["space", "invisible", "mass", "universe", "mystery"] },
  { word: "BLACK HOLE",               taboo: ["space", "gravity", "pull", "light", "star"] },
  { word: "CELL THEORY",              taboo: ["biology", "basic", "unit", "life", "Schwann"] },
  { word: "DNA",                      taboo: ["gene", "heredity", "double", "helix", "biological"] },
  { word: "CHROMOSOME",               taboo: ["gene", "cell", "DNA", "number", "biological"] },
  { word: "OSMOSIS",                  taboo: ["water", "membrane", "pass", "concentration", "plant"] },
  { word: "PLATE TECTONICS",          taboo: ["earth", "crust", "move", "earthquake", "continental"] },
  { word: "CARBON CYCLE",             taboo: ["carbon", "dioxide", "plant", "absorb", "atmosphere"] },
  { word: "WATER CYCLE",              taboo: ["evaporate", "rain", "cloud", "river", "nature"] },
  { word: "FOOD CHAIN",               taboo: ["predator", "prey", "eat", "energy", "ecosystem"] },
  { word: "DEFORESTATION",            taboo: ["tree", "cut", "forest", "destroy", "environment"] },
  { word: "ACID RAIN",                taboo: ["pollution", "sulphur", "rain", "damage", "chemical"] },
  { word: "OZONE LAYER",              taboo: ["atmosphere", "protect", "UV", "sun", "deplete"] },
  { word: "GREENHOUSE EFFECT",        taboo: ["carbon", "warm", "trap", "gas", "earth"] },
  { word: "RENEWABLE ENERGY",         taboo: ["solar", "wind", "clean", "infinite", "future"] },
  { word: "BLOCKCHAIN",               taboo: ["crypto", "digital", "chain", "record", "secure"] },
  { word: "MACHINE LEARNING",         taboo: ["computer", "learn", "data", "AI", "pattern"] },
  { word: "INTERNET OF THINGS",       taboo: ["device", "connect", "internet", "smart", "sensor"] },
  { word: "CYBERSECURITY",            taboo: ["hack", "protect", "data", "online", "threat"] },
  { word: "VIRTUAL REALITY",          taboo: ["headset", "digital", "immerse", "game", "simulate"] },
  { word: "GENETIC ENGINEERING",      taboo: ["DNA", "modify", "gene", "science", "organism"] },
  { word: "STEM CELLS",               taboo: ["biology", "regenerate", "medicine", "embryo", "research"] },
  { word: "ANTIBIOTIC RESISTANCE",    taboo: ["bacteria", "drug", "resist", "medicine", "overuse"] },
  { word: "PANDEMIC",                 taboo: ["disease", "global", "spread", "COVID", "outbreak"] },
  { word: "HERD IMMUNITY",            taboo: ["population", "immune", "vaccine", "protect", "disease"] },
  { word: "DEMOGRAPHIC DIVIDEND",     taboo: ["young", "population", "India", "work", "economy"] },
  { word: "BRAIN DRAIN",              taboo: ["skilled", "leave", "country", "migrate", "talent"] },

  // ── 300 additional hard words (Indian context) ──────────────────────────

  // Indian Space & Science
  { word: "CHANDRAYAAN",              taboo: ["moon", "India", "ISRO", "lunar", "mission"] },
  { word: "MANGALYAAN",               taboo: ["Mars", "ISRO", "India", "orbit", "first attempt"] },
  { word: "GAGANYAAN",                taboo: ["human", "space", "India", "ISRO", "crewed"] },
  { word: "PSLV",                     taboo: ["launch vehicle", "polar", "rocket", "reliable", "ISRO"] },
  { word: "GSLV",                     taboo: ["heavy", "geo", "rocket", "ISRO", "cryogenic"] },
  { word: "ASAT",                     taboo: ["anti-satellite", "India", "weapon", "space", "test"] },
  { word: "BARC",                     taboo: ["nuclear", "atomic", "Bhabha", "research", "Mumbai"] },
  { word: "TEJAS FIGHTER",            taboo: ["jet", "HAL", "India", "light", "indigenously built"] },
  { word: "BRAHMOS",                  taboo: ["supersonic", "missile", "India", "Russia", "joint"] },
  { word: "AGNI MISSILE",             taboo: ["ballistic", "India", "DRDO", "long range", "capable"] },
  { word: "INS VIKRANT",              taboo: ["aircraft carrier", "Indian Navy", "large", "made in India", "warship"] },
  { word: "BOSE-EINSTEIN CONDENSATE", taboo: ["new state", "matter", "extreme cold", "quantum", "Bose"] },
  { word: "SATYENDRA NATH BOSE",      taboo: ["physicist", "Bengal", "boson", "Einstein", "quantum"] },
  { word: "RAMANUJAN NUMBER",          taboo: ["1729", "taxi", "two cubes", "Hardy", "interesting"] },
  { word: "BINARY SYSTEM INDIA",      taboo: ["zero", "one", "computer", "Pingala", "ancient"] },
  { word: "PLACE VALUE SYSTEM",       taboo: ["number", "position", "India", "zero", "mathematics"] },
  { word: "ARYABHATA",                taboo: ["zero", "mathematician", "ancient", "India", "astronomer"] },

  // Indian Economic Policies
  { word: "MAKE IN INDIA",            taboo: ["manufacture", "government", "initiative", "domestic", "Modi"] },
  { word: "DIGITAL INDIA",            taboo: ["technology", "government", "initiative", "internet", "connect"] },
  { word: "STARTUP INDIA",            taboo: ["entrepreneur", "new company", "innovation", "fund", "unicorn"] },
  { word: "ATMANIRBHAR BHARAT",        taboo: ["self-reliant", "India", "domestic", "initiative", "vocal for local"] },
  { word: "GOODS AND SERVICES TAX",   taboo: ["uniform", "India", "replace", "one nation", "indirect tax"] },
  { word: "DEMONETISATION",           taboo: ["currency", "withdraw", "Modi", "2016", "cash banned"] },
  { word: "JAN DHAN YOJANA",          taboo: ["bank", "account", "poor", "financial inclusion", "India"] },
  { word: "MNREGA",                   taboo: ["employment", "rural", "guarantee", "hundred days", "scheme"] },
  { word: "PM KISAN",                 taboo: ["farmer", "direct transfer", "six thousand", "scheme", "India"] },
  { word: "DRAIN OF WEALTH",          taboo: ["British", "extract", "India", "Dadabhai Naoroji", "economy"] },
  { word: "WHITE REVOLUTION",         taboo: ["milk", "Amul", "Gujarat", "Verghese Kurien", "cooperatives"] },
  { word: "OPERATION FLOOD",          taboo: ["milk", "Kurien", "cooperatives", "India", "rural dairy"] },
  { word: "FISCAL FEDERALISM",        taboo: ["finance", "share", "centre", "state", "grants"] },
  { word: "FINANCE COMMISSION",       taboo: ["recommend", "tax share", "centre", "state", "India"] },
  { word: "COOPERATIVE FEDERALISM",   taboo: ["centre", "state", "work together", "NITI Aayog", "India"] },
  { word: "COMPETITIVE FEDERALISM",   taboo: ["state", "compete", "better", "performance", "federal"] },
  { word: "REPO RATE",                taboo: ["RBI", "interest", "bank", "borrow", "monetary"] },
  { word: "CASH RESERVE RATIO",       taboo: ["bank", "keep cash", "RBI", "mandatory", "percentage"] },
  { word: "STATUTORY LIQUIDITY RATIO",taboo: ["liquid", "reserve", "banks", "RBI", "government securities"] },
  { word: "CURRENT ACCOUNT DEFICIT",  taboo: ["import more", "export less", "balance", "economy", "forex"] },
  { word: "FOREIGN EXCHANGE RESERVES",taboo: ["country", "dollars", "hold", "trade", "RBI"] },
  { word: "PURCHASING POWER PARITY",  taboo: ["compare", "economy", "price", "equal basket", "different country"] },
  { word: "HUMAN CAPITAL THEORY",     taboo: ["education", "skill", "people", "economy", "invest"] },

  // Indian Historical Events
  { word: "BATTLE OF PLASSEY",        taboo: ["1757", "Siraj", "Clive", "Bengal", "British control"] },
  { word: "BATTLE OF BUXAR",          taboo: ["1764", "Mir Qasim", "British", "India", "decisive"] },
  { word: "BATTLE OF PANIPAT",        taboo: ["1526", "1556", "1761", "decisive", "India"] },
  { word: "BATTLE OF HALDIGHATI",     taboo: ["Mewar", "Rana Pratap", "Akbar", "Rajasthan", "1576"] },
  { word: "PERMANENT SETTLEMENT",     taboo: ["Bengal", "land revenue", "zamindars", "1793", "British"] },
  { word: "RYOTWARI SYSTEM",          taboo: ["farmer", "direct tax", "British", "South India", "Munro"] },
  { word: "ZAMINDARI SYSTEM",         taboo: ["landlord", "collect rent", "farmer", "British", "exploit"] },
  { word: "BENGAL FAMINE",            taboo: ["1943", "British", "death", "food shortage", "India"] },
  { word: "CHAMPARAN SATYAGRAHA",     taboo: ["Gandhi", "Bihar", "indigo", "farmer", "1917"] },
  { word: "KHILAFAT MOVEMENT",        taboo: ["Muslim", "Congress", "1920", "Turkey", "Hindu Muslim unity"] },
  { word: "SIMON COMMISSION",         taboo: ["British", "1927", "India", "protest", "boycott"] },
  { word: "CABINET MISSION",          taboo: ["1946", "British", "India", "plan", "before partition"] },
  { word: "OPERATION BLUE STAR",      taboo: ["1984", "Golden Temple", "Amritsar", "military", "Sikh"] },
  { word: "BHOPAL GAS TRAGEDY",       taboo: ["1984", "Union Carbide", "gas", "death", "Bhopal"] },
  { word: "BABRI MASJID DEMOLITION",  taboo: ["Ayodhya", "1992", "demolish", "mosque", "dispute"] },
  { word: "KARGIL WAR",               taboo: ["1999", "Pakistan", "India", "Kashmir", "victory"] },
  { word: "POKHRAN NUCLEAR TEST",     taboo: ["nuclear", "1998", "India", "Vajpayee", "bomb"] },
  { word: "INDO-CHINA WAR 1962",      taboo: ["China", "defeat", "India", "border", "Himalaya"] },
  { word: "INDO-PAK WAR 1971",        taboo: ["Bangladesh", "liberation", "India", "Pakistan", "Indira"] },
  { word: "BANK NATIONALISATION",     taboo: ["1969", "Indira", "banks", "public", "India"] },
  { word: "GREEN REVOLUTION INDIA",   taboo: ["wheat", "production", "Punjab", "HYV", "irrigation"] },
  { word: "HARAPPAN CIVILISATION",    taboo: ["ancient", "Indus", "2600 BC", "city", "India"] },
  { word: "MAURYA EMPIRE",            taboo: ["ancient", "Ashoka", "Chandragupta", "Bihar", "large"] },
  { word: "GUPTA GOLDEN AGE",         taboo: ["golden", "ancient", "India", "culture", "science"] },
  { word: "DELHI SULTANATE",          taboo: ["Muslim", "ruler", "North India", "before Mughal", "sultanate"] },
  { word: "MUGHAL EMPIRE",            taboo: ["Babur", "large", "India", "culture", "art"] },
  { word: "MARATHA EMPIRE",           taboo: ["Shivaji", "Maharashtra", "horsemen", "expand", "kingdom"] },
  { word: "VIJAYANAGARA EMPIRE",      taboo: ["South", "large", "Hampi", "Hindu", "Karnataka"] },
  { word: "CHOLA EMPIRE",             taboo: ["Tamil", "naval", "ancient", "bronze", "south"] },
  { word: "DELHI SULTANATE SLAVERY",  taboo: ["Qutubuddin", "slave dynasty", "first", "Delhi", "medieval"] },
  { word: "REORGANISATION OF STATES", taboo: ["1956", "language", "states", "India", "linguistic"] },

  // Philosophy (Indian & Western)
  { word: "KARMA",                    taboo: ["action", "result", "Hindu", "cycle", "consequence"] },
  { word: "DHARMA",                   taboo: ["duty", "right", "Hindu", "path", "moral"] },
  { word: "MOKSHA",                   taboo: ["liberation", "soul", "Hindu", "goal", "cycle ends"] },
  { word: "SAMSARA",                  taboo: ["cycle", "birth", "death", "Hindu", "rebirth"] },
  { word: "MAYA",                     taboo: ["illusion", "Hindu", "philosophy", "world", "Vedanta"] },
  { word: "NIRVANA",                  taboo: ["Buddhist", "liberation", "peace", "end", "suffering"] },
  { word: "BRAHMAN",                  taboo: ["universal", "Hindu", "supreme", "philosophy", "Vedanta"] },
  { word: "ATMAN",                    taboo: ["self", "soul", "Hindu", "individual", "spirit"] },
  { word: "ADVAITA VEDANTA",          taboo: ["non-dual", "Shankaracharya", "philosophy", "Hindu", "one"] },
  { word: "DVAITA VEDANTA",           taboo: ["dual", "Madhvacharya", "philosophy", "Hindu", "devotion"] },
  { word: "VISHISHTADVAITA",          taboo: ["Ramanuja", "philosophy", "qualified", "non-dual", "Hindu"] },
  { word: "EPISTEMOLOGY",             taboo: ["knowledge", "theory", "justify", "what we know", "philosophy"] },
  { word: "METAPHYSICS",              taboo: ["reality", "existence", "beyond physics", "nature", "philosophy"] },
  { word: "ONTOLOGY",                 taboo: ["study of being", "existence", "what is", "branch", "philosophy"] },
  { word: "AESTHETICS",              taboo: ["beauty", "art", "philosophy", "judgement", "theory"] },
  { word: "DIALECTICS",              taboo: ["thesis", "antithesis", "synthesis", "Hegel", "argument"] },
  { word: "EMPIRICISM",              taboo: ["experience", "knowledge", "senses", "Locke", "Hume"] },
  { word: "RATIONALISM",             taboo: ["reason", "knowledge", "Descartes", "Kant", "innate"] },
  { word: "PRAGMATISM",              taboo: ["practical", "truth", "consequences", "James", "Dewey"] },
  { word: "POSTMODERNISM",           taboo: ["deconstruct", "narrative", "Foucault", "relative", "meta"] },
  { word: "PHENOMENOLOGY",           taboo: ["experience", "conscious", "Husserl", "appear", "study"] },
  { word: "ABSURDISM",               taboo: ["meaning", "meaningless", "Camus", "revolt", "philosophy"] },
  { word: "HERMENEUTICS",            taboo: ["interpretation", "text", "meaning", "understanding", "philosophy"] },
  { word: "STRUCTURALISM",           taboo: ["underlying structure", "Saussure", "language", "pattern", "sign"] },

  // Political Concepts (Advanced)
  { word: "VETO POWER",              taboo: ["UN", "security", "block", "permanent", "P5"] },
  { word: "G20 PRESIDENCY",          taboo: ["twenty", "economy", "summit", "global", "India hosted"] },
  { word: "BRICS",                   taboo: ["Brazil", "Russia", "India", "China", "South Africa"] },
  { word: "SAARC",                   taboo: ["South Asia", "association", "cooperation", "India", "regional"] },
  { word: "NON-ALIGNED MOVEMENT",    taboo: ["Nehru", "cold war", "neutral", "neither side", "India"] },
  { word: "SOUTH-SOUTH COOPERATION", taboo: ["developing", "countries", "India", "Africa", "technical aid"] },
  { word: "DOCTRINE OF BASIC STRUCTURE",taboo:["constitution", "parliament cannot amend", "Keshavananda", "India", "fundamental"] },
  { word: "JUDICIAL ACTIVISM",       taboo: ["court", "go beyond", "interpret", "expand", "PIL"] },
  { word: "JUDICIAL RESTRAINT",      taboo: ["court", "limit itself", "constitution", "defer", "legislature"] },
  { word: "COLLEGIUM SYSTEM",        taboo: ["judge", "appoint", "Supreme Court", "India", "criticism"] },
  { word: "HABEAS CORPUS",           taboo: ["body", "produce", "court", "illegal", "detention"] },
  { word: "ARTICLE 370",             taboo: ["Kashmir", "special status", "abrogated", "2019", "constitution"] },
  { word: "PREAMBLE OF INDIA",       taboo: ["constitution", "introduction", "India", "sovereign", "words"] },
  { word: "CONSTITUTIONAL MORALITY", taboo: ["Ambedkar", "constitution", "values", "uphold", "principle"] },
  { word: "RULE OF LAW",             taboo: ["Dicey", "equal", "law", "no arbitrary", "supreme"] },
  { word: "ULTRA VIRES",             taboo: ["beyond power", "authority", "invalid", "act", "legal"] },
  { word: "SEDITION LAW",            taboo: ["against government", "law", "speech", "punish", "India"] },

  // Science Concepts (Physics)
  { word: "ENTROPY",                 taboo: ["disorder", "increase", "thermodynamics", "time", "irreversible"] },
  { word: "MOMENTUM",                taboo: ["mass", "velocity", "motion", "Newton", "conserved"] },
  { word: "REFRACTION",              taboo: ["bend", "light", "medium", "angle", "lens"] },
  { word: "DIFFRACTION",             taboo: ["bend", "wave", "obstacle", "spread", "light"] },
  { word: "INTERFERENCE",            taboo: ["overlap", "wave", "pattern", "constructive", "destructive"] },
  { word: "RESONANCE",               taboo: ["frequency match", "vibrate", "sound", "amplify", "sympathetic"] },
  { word: "DOPPLER EFFECT",          taboo: ["sound source", "moving", "frequency change", "ambulance", "red shift"] },
  { word: "BERNOULLI PRINCIPLE",     taboo: ["pressure", "fluid", "fast", "low", "aeroplane wing"] },
  { word: "ARCHIMEDES PRINCIPLE",    taboo: ["buoyancy", "fluid", "displace", "object", "float"] },
  { word: "OHMS LAW",                taboo: ["current", "voltage", "resistance", "proportional", "circuit"] },
  { word: "FARADAYS LAW",            taboo: ["electromagnetic", "induction", "flux change", "Faraday", "coil"] },
  { word: "QUANTUM ENTANGLEMENT",    taboo: ["two particle", "linked", "instant", "distance", "spooky"] },
  { word: "WAVE-PARTICLE DUALITY",   taboo: ["light", "both", "wave", "particle", "nature"] },
  { word: "HEISENBERG UNCERTAINTY",  taboo: ["position", "momentum", "cannot", "both know", "quantum"] },
  { word: "SCHRODINGER CAT",         taboo: ["alive", "dead", "quantum", "both", "box"] },
  { word: "PHOTOELECTRIC EFFECT",    taboo: ["light", "electron", "Einstein", "Nobel", "metal"] },
  { word: "NUCLEAR FISSION",         taboo: ["split", "uranium", "energy", "bomb", "chain reaction"] },
  { word: "NUCLEAR FUSION",          taboo: ["combine", "hydrogen", "energy", "sun", "clean"] },
  { word: "RADIOACTIVE DECAY",       taboo: ["unstable", "nucleus", "emit", "radiation", "half-life"] },
  { word: "HIGGS BOSON",             taboo: ["God particle", "mass", "LHC", "CERN", "particle physics"] },
  { word: "STANDARD MODEL",          taboo: ["particle", "physics", "quarks", "bosons", "fermions"] },
  { word: "STRING THEORY",           taboo: ["tiny string", "dimension", "physics", "unify", "theoretical"] },

  // Science Concepts (Biology & Chemistry)
  { word: "EPIGENETICS",             taboo: ["gene", "expression", "environment", "change", "heritable"] },
  { word: "CRISPR",                  taboo: ["gene editing", "scissors", "DNA", "molecular", "therapy"] },
  { word: "MRNA VACCINE",            taboo: ["COVID", "mRNA", "spike protein", "instructions", "immune"] },
  { word: "OSMOTIC PRESSURE",        taboo: ["solute", "concentration", "membrane", "water", "equilibrium"] },
  { word: "ENZYME KINETICS",         taboo: ["enzyme", "substrate", "rate", "Michaelis", "catalysis"] },
  { word: "KREBS CYCLE",             taboo: ["citric acid", "mitochondria", "energy", "ATP", "respiration"] },
  { word: "CELL DIVISION",           taboo: ["mitosis", "meiosis", "replicate", "chromosome", "growth"] },
  { word: "PROTEIN SYNTHESIS",       taboo: ["ribosome", "mRNA", "amino acid", "translation", "gene"] },
  { word: "ECOSYSTEM SERVICES",      taboo: ["nature", "benefit", "pollination", "clean water", "free"] },

  // Environment & Geography
  { word: "EL NINO",                 taboo: ["Pacific", "warm", "weather", "affect India", "monsoon"] },
  { word: "LA NINA",                 taboo: ["Pacific", "cool", "opposite El Nino", "weather", "monsoon"] },
  { word: "INDIAN OCEAN DIPOLE",     taboo: ["Indian Ocean", "east west", "warm cool", "monsoon", "climate"] },
  { word: "INTERTROPICAL CONVERGENCE",taboo:["equatorial", "convergence", "low pressure", "tropical", "rain zone"] },
  { word: "OROGRAPHIC RAINFALL",     taboo: ["mountain", "force air", "rise", "cool", "rain"] },
  { word: "CONVECTIONAL RAINFALL",   taboo: ["heat", "rise", "cool", "thunder", "equatorial"] },
  { word: "CARBON SEQUESTRATION",    taboo: ["absorb CO2", "forest", "ocean", "store", "climate"] },
  { word: "DESERTIFICATION",         taboo: ["fertile land", "become desert", "degradation", "overgrazing", "drought"] },
  { word: "WETLAND CONSERVATION",    taboo: ["marshes", "biodiversity", "protect", "Ramsar", "water"] },
  { word: "CORAL BLEACHING",         taboo: ["heat", "ocean", "coral", "die", "white"] },
  { word: "PERMAFROST",              taboo: ["permanently frozen", "ground", "Arctic", "Himalaya", "thaw"] },
  { word: "AQUIFER",                 taboo: ["underground", "water stored", "porous", "extract", "bore well"] },
  { word: "WATERSHED",               taboo: ["divide water", "flow", "basin", "catchment", "separate"] },
  { word: "ENVIRONMENTAL IMPACT ASSESSMENT",taboo:["project", "study", "harm environment", "approval", "clearance"] },
  { word: "ECOTOURISM",              taboo: ["nature travel", "conservation", "sustainable", "green", "wildlife"] },

  // Indian Administrative / Legal
  { word: "ARTICLE 356",             taboo: ["president's rule", "state", "emergency", "Governor", "India"] },
  { word: "ARTICLE 21",             taboo: ["life", "liberty", "fundamental right", "constitution", "expanded"] },
  { word: "ARTICLE 32",             taboo: ["constitutional remedy", "Supreme Court", "fundamental", "writ", "move"] },
  { word: "MANDAMUS",               taboo: ["command", "public duty", "court", "writ", "perform"] },
  { word: "CERTIORARI",             taboo: ["review", "lower court", "writ", "jurisdiction", "higher court"] },
  { word: "QUO WARRANTO",           taboo: ["authority", "by what right", "office", "writ", "challenge"] },
  { word: "DOCTRINE OF ECLIPSE",    taboo: ["pre-constitution", "fundamental rights", "dormant", "revival", "law"] },
  { word: "DOCTRINE OF SEVERABILITY",taboo:["separate bad part", "law", "valid remain", "constitution", "legal"] },
  { word: "DOCTRINE OF PITH",       taboo: ["essential character", "legislation", "subject matter", "state", "centre"] },
  { word: "LEGITIMATE EXPECTATION", taboo: ["promise", "government", "court enforce", "expectation", "administrative"] },
  { word: "PARLIAMENTARY PRIVILEGE", taboo: ["MP", "speech", "immunity", "parliament", "outside court"] },
  { word: "PROROGATION",            taboo: ["parliament", "end session", "President", "India", "not dissolve"] },
  { word: "DISSOLUTION",            taboo: ["Lok Sabha", "end", "President", "parliament", "new election"] },

  // Economics (Advanced)
  { word: "LAFFER CURVE",            taboo: ["tax", "revenue", "optimal rate", "decrease", "supply side"] },
  { word: "CREATIVE DESTRUCTION",    taboo: ["Schumpeter", "old replaced", "new", "capitalism", "innovation"] },
  { word: "COMPARATIVE ADVANTAGE",   taboo: ["trade", "specialise", "relative cost", "Ricardo", "opportunity"] },
  { word: "ECONOMIES OF SCALE",      taboo: ["produce more", "cost falls", "factory", "large", "efficiency"] },
  { word: "OPPORTUNITY COST",        taboo: ["give up", "alternative", "choose", "decision", "economics"] },
  { word: "GAME THEORY",             taboo: ["Nash equilibrium", "strategy", "prisoner", "dilemma", "interactive"] },
  { word: "PRISONERS DILEMMA",       taboo: ["cooperate", "betray", "both strategy", "Nash", "decision"] },
  { word: "MORAL HAZARD",            taboo: ["risk", "insurance", "behaviour change", "no consequence", "economics"] },
  { word: "ADVERSE SELECTION",       taboo: ["information", "market", "insurance problem", "Akerlof", "lemons"] },
  { word: "PRINCIPAL AGENT PROBLEM", taboo: ["incentive", "align", "corporation", "management", "conflict"] },
  { word: "SUPPLY SIDE ECONOMICS",   taboo: ["cut tax", "produce", "Reagan", "trickle down", "incentivise"] },
  { word: "CROWDING OUT",            taboo: ["government borrow", "private less", "investment", "interest rate", "fiscal"] },
  { word: "SOLOW GROWTH MODEL",      taboo: ["capital", "labour", "technology", "long-run", "steady state"] },
  { word: "CAPABILITY APPROACH",     taboo: ["Amartya Sen", "freedom", "what people can do", "poverty", "flourish"] },
  { word: "SOCIAL CHOICE THEORY",    taboo: ["Arrow", "collective", "decision", "individual preference", "impossibility"] },

  // Sociological Concepts
  { word: "PATRIARCHY",             taboo: ["male dominate", "system", "society", "hierarchy", "gender"] },
  { word: "INTERSECTIONALITY",      taboo: ["multiple identity", "overlap", "discrimination", "social", "Kimberlé"] },
  { word: "SOCIAL MOBILITY",        taboo: ["move class", "society", "upward", "opportunity", "aspiration"] },
  { word: "GLASS CEILING",          taboo: ["woman", "invisible barrier", "promotion", "work", "gender"] },
  { word: "AFFIRMATIVE ACTION",     taboo: ["positive discrimination", "correct historical", "remedy", "reservation", "diversity"] },
  { word: "ECHO CHAMBER",           taboo: ["opinion same", "reinforce", "media", "bubble", "confirm"] },
  { word: "FILTER BUBBLE",          taboo: ["algorithm", "internet", "personalise", "opinion", "narrow"] },
  { word: "PROPAGANDA",             taboo: ["manipulate", "opinion", "government", "media", "bias"] },
  { word: "CULTURAL APPROPRIATION", taboo: ["borrow", "another culture", "without respect", "controversy", "adopt"] },
  { word: "IMPLICIT BIAS",          taboo: ["unconscious", "attitude", "behaviour", "prejudice", "automatic"] },
  { word: "DOWRY SYSTEM",           taboo: ["woman", "marriage", "money given", "India", "illegal"] },
  { word: "ARRANGED MARRIAGE",      taboo: ["family decide", "match", "India", "traditional", "alliance"] },
  { word: "ENDOGAMY",               taboo: ["marry within", "same group", "community", "caste", "tradition"] },
  { word: "JOINT FAMILY SYSTEM",    taboo: ["together", "live", "extended", "India", "traditional"] },
  { word: "GOTRA EXOGAMY",          taboo: ["same lineage", "not marry", "Hindu", "tradition", "clan"] },
  { word: "GLASS ESCALATOR",        taboo: ["man", "woman dominated field", "faster", "promotion", "gender"] },
  { word: "TOKENISM",               taboo: ["symbol", "gesture", "minority", "inclusion", "shallow"] },
  { word: "SOCIAL CAPITAL",         taboo: ["trust", "network", "cooperate", "society", "Putnam"] },

  // Indian Freedom Struggle (detailed)
  { word: "SWADESHI MOVEMENT",      taboo: ["Indian goods", "boycott", "independence", "Gandhi", "domestic"] },
  { word: "NON-COOPERATION MOVEMENT",taboo:["Gandhi", "British", "resist", "peaceful", "1920"] },
  { word: "CONSTITUENT ASSEMBLY",   taboo: ["draft constitution", "India", "members", "elected", "Ambedkar"] },
  { word: "PARTITION OF INDIA",     taboo: ["1947", "divide", "Pakistan", "border", "Radcliffe"] },
  { word: "DOCTRINE OF LAPSE",      taboo: ["Dalhousie", "annexe", "no heir", "British", "policy"] },
  { word: "THIRD BATTLE OF PANIPAT",taboo: ["Marathas", "Afghans", "1761", "defeat", "India"] },

  // Technology & Modern
  { word: "DEEP LEARNING",          taboo: ["neural network", "layers", "AI", "image", "recognise"] },
  { word: "AUGMENTED REALITY",      taboo: ["real world", "overlay", "digital", "phone", "Pokemon Go"] },
  { word: "GENERATIVE AI",          taboo: ["create", "content", "text", "image", "model"] },
  { word: "QUANTUM COMPUTING",      taboo: ["qubit", "superposition", "faster", "solve", "encryption"] },
  { word: "FINTECH",                taboo: ["finance", "technology", "digital payment", "innovate", "UPI"] },
  { word: "UPI",                    taboo: ["digital", "payment", "India", "scan", "transfer"] },
  { word: "E-GOVERNANCE",           taboo: ["digital government", "service online", "citizen", "portal", "India"] },
  { word: "CRYPTOCURRENCY",         taboo: ["digital currency", "blockchain", "decentralised", "Bitcoin", "volatile"] },
  { word: "DARK WEB",               taboo: ["hidden", "internet", "anonymous", "illegal", "tor"] },
  { word: "NET NEUTRALITY",         taboo: ["internet", "equal", "no throttle", "ISP", "open"] },

  // ISRO Missions
  { word: "ARYABHATA SATELLITE",    taboo: ["first Indian", "satellite", "1975", "ISRO", "space"] },
  { word: "INSAT SYSTEM",           taboo: ["communication", "satellite", "weather", "India", "series"] },
  { word: "CHANDRAYAAN 3",          taboo: ["south pole", "moon land", "India", "Vikram", "2023"] },
  { word: "ADITYA L1",              taboo: ["sun", "solar", "India", "ISRO", "Lagrange point"] },

  // More Political Theory
  { word: "STATE OF NATURE",        taboo: ["no government", "Hobbes", "war all", "original", "condition"] },
  { word: "GENERAL WILL",           taboo: ["Rousseau", "collective", "people", "good", "democracy"] },
  { word: "CATEGORICAL IMPERATIVE", taboo: ["Kant", "universal", "act", "moral", "duty"] },
  { word: "VEIL OF IGNORANCE",      taboo: ["Rawls", "fairness", "don't know position", "justice", "design"] },
  { word: "DIFFERENCE PRINCIPLE",   taboo: ["Rawls", "benefit", "least advantaged", "justice", "inequality"] },
  { word: "UTILITY MAXIMISATION",   taboo: ["greatest", "happiness", "Bentham", "calculate", "pleasure"] },
  { word: "TROLLEY PROBLEM",        taboo: ["dilemma", "save five", "pull lever", "ethics", "moral"] },
  { word: "OVERTON WINDOW",         taboo: ["policy", "acceptable range", "shift", "public opinion", "politics"] },
  { word: "DEEP STATE",             taboo: ["hidden", "bureaucracy", "control", "elected", "conspiracy"] },
  { word: "POPULISM",               taboo: ["people vs elite", "simple answer", "leader", "movement", "anti establishment"] },
  { word: "TECHNOCRACY",            taboo: ["experts", "govern", "technical", "merit", "democratic deficit"] },

  // Environment (India Specific)
  { word: "TIGER RESERVE",          taboo: ["protect tiger", "India", "forest", "sanctuary", "buffer zone"] },
  { word: "BIOSPHERE RESERVE",      taboo: ["protect ecosystem", "UNESCO", "buffer zone", "core area", "India"] },
  { word: "NATIONAL ACTION PLAN",   taboo: ["climate", "India", "government", "plan", "eight missions"] },
  { word: "PARIS AGREEMENT",        taboo: ["climate", "temperature", "global", "1.5", "nations sign"] },
  { word: "KYOTO PROTOCOL",         taboo: ["greenhouse", "emission", "1997", "developed", "target"] },
  { word: "SUSTAINABLE DEVELOPMENT GOALS",taboo:["UN", "seventeen", "2030", "global", "SDG"] },
  { word: "CARRYING CAPACITY",      taboo: ["maximum", "population", "environment support", "limit", "resource"] },
  { word: "TROPHIC LEVEL",          taboo: ["food chain", "level", "energy", "producer", "consumer"] },
  { word: "NITROGEN CYCLE",         taboo: ["nitrogen", "bacteria", "fix", "atmosphere", "soil"] },
  { word: "PHOSPHORUS CYCLE",       taboo: ["phosphorus", "rock", "soil", "water", "nutrient"] },

  // ── Top-up additions (unique complex concepts) ─────────────────────────

  // Political Philosophy (new)
  { word: "ORIENTALISM",             taboo: ["Edward Said", "East", "West", "representation", "colonial bias"] },
  { word: "SUBALTERN STUDIES",       taboo: ["Spivak", "India", "history", "colonial", "suppressed voice"] },
  { word: "BIOPOWER",                taboo: ["Foucault", "government", "body", "population", "control"] },
  { word: "PANOPTICISM",             taboo: ["Foucault", "prison", "surveillance", "all see", "power"] },
  { word: "IDEOLOGICAL STATE APPARATUS",taboo:["Althusser", "school", "church", "media", "reproduce"] },
  { word: "HABITUS",                 taboo: ["Bourdieu", "practice", "social", "unconscious", "field"] },
  { word: "SYMBOLIC CAPITAL",        taboo: ["Bourdieu", "prestige", "recognition", "status", "non-economic"] },
  { word: "WORLD SYSTEMS THEORY",    taboo: ["Wallerstein", "core", "periphery", "unequal", "capitalism"] },
  { word: "DEPENDENCY THEORY",       taboo: ["core", "periphery", "develop", "underdevelop", "exploitation"] },
  { word: "POST-COLONIAL THEORY",    taboo: ["after colonial", "power", "identity", "Bhabha", "Said"] },
  { word: "ANOMIE",                  taboo: ["Durkheim", "normlessness", "rapid change", "society", "chaos"] },
  { word: "RATIONAL CHOICE THEORY",  taboo: ["individual", "decision", "maximise", "utility", "preference"] },
  { word: "MODERNISATION THEORY",    taboo: ["traditional", "modern", "development", "linear", "west"] },
  { word: "LIMINALITY",              taboo: ["threshold", "betwixt", "between", "transition", "rite of passage"] },
  { word: "SIMULACRA",               taboo: ["Baudrillard", "copy", "no original", "reality", "image"] },
  { word: "DIALECTICAL MATERIALISM", taboo: ["Marx", "history", "material", "class struggle", "Hegel"] },
  { word: "HISTORICAL MATERIALISM",  taboo: ["Marx", "past", "material", "production force", "class"] },

  // Indian Social Issues (complex)
  { word: "DALIT CONSCIOUSNESS",     taboo: ["caste", "oppression", "identity", "resistance", "Ambedkar"] },
  { word: "ANTI-DEFECTION LAW",      taboo: ["floor crossing", "party", "India", "constitutional", "tenth schedule"] },
  { word: "ELECTORAL BOND",          taboo: ["political", "fund", "India", "anonymous", "Supreme Court"] },
  { word: "UNIFORM CIVIL CODE",      taboo: ["personal law", "India", "one", "all religion", "Article 44"] },
  { word: "TRIPLE TALAQ",            taboo: ["Muslim", "instant divorce", "banned", "India", "unconstitutional"] },
  { word: "NATIONAL REGISTER OF CITIZENS",taboo:["Assam", "citizenship", "undocumented", "NRC", "controversial"] },
  { word: "CITIZENSHIP AMENDMENT ACT",taboo:["religion", "citizenship", "Pakistan", "Afghanistan", "Bangladesh"] },
  { word: "KHAP PANCHAYAT",          taboo: ["caste", "village", "honour", "illegal ruling", "Haryana"] },
  { word: "MANUAL SCAVENGING",       taboo: ["caste", "cleaning sewage", "India", "banned", "dignity"] },
  { word: "BONDED LABOUR",           taboo: ["debt", "India", "rural", "exploits", "illegal"] },
  { word: "FOREST RIGHTS ACT",       taboo: ["tribal", "forest land", "India", "2006", "recognition"] },
  { word: "LAND ACQUISITION ACT",    taboo: ["India", "government take land", "compensation", "project", "law"] },
  { word: "UAPA",                    taboo: ["unlawful activities", "India", "terrorist", "detention", "law"] },

  // Science (New Concepts)
  { word: "EPIGENOME",               taboo: ["all epigenetic marks", "DNA", "environment", "affect", "expression"] },
  { word: "MICROBIOME",              taboo: ["bacteria", "gut", "health", "trillions", "inside body"] },
  { word: "TELOMERE",                taboo: ["end", "chromosome", "aging", "shorten", "DNA cap"] },
  { word: "APOPTOSIS",               taboo: ["cell death", "programmed", "normal", "essential", "body"] },
  { word: "PROTEOMICS",              taboo: ["all proteins", "cell", "study", "biological", "function"] },
  { word: "GENOMICS",                taboo: ["all genes", "DNA", "sequence", "study", "genome"] },
  { word: "SYNTHETIC BIOLOGY",       taboo: ["design", "build", "biological", "new", "engineer"] },
  { word: "NEURAL INTERFACE",        taboo: ["brain", "computer", "signal", "implant", "future"] },
  { word: "PRION",                   taboo: ["misfolded", "protein", "disease", "mad cow", "brain"] },
  { word: "CRISPR CAS9",             taboo: ["gene editing", "scissors", "DNA", "precise", "therapy"] },
  { word: "MRNA TECHNOLOGY",         taboo: ["mRNA", "spike protein", "instructions", "immune", "vaccine"] },

  // Technology (New)
  { word: "ZERO TRUST SECURITY",     taboo: ["never trust", "verify always", "cyber", "access", "model"] },
  { word: "RANSOMWARE",              taboo: ["malware", "encrypt", "pay demand", "attack", "data"] },
  { word: "QUANTUM KEY DISTRIBUTION",taboo:["unbreakable", "cryptography", "quantum", "key", "secure"] },
  { word: "FEDERATED LEARNING",      taboo: ["train AI", "local data", "privacy", "no share", "model"] },
  { word: "EXPLAINABLE AI",          taboo: ["understand why", "AI decision", "transparent", "black box", "XAI"] },
  { word: "DIGITAL TWIN",            taboo: ["virtual copy", "real system", "monitor", "simulate", "mirror"] },
  { word: "SMART GRID",              taboo: ["electricity", "digital", "manage efficient", "two-way", "IoT"] },
  { word: "EDGE COMPUTING",          taboo: ["process data", "local", "near device", "fast", "cloud alternative"] },
  { word: "DEEP FAKE",               taboo: ["AI", "fake", "video", "face swap", "mislead"] },

  // Energy & Climate (New)
  { word: "GREEN HYDROGEN",          taboo: ["clean", "electrolysis", "water", "fuel", "zero carbon"] },
  { word: "CARBON NEUTRALITY",       taboo: ["emit", "remove", "balance", "zero net", "climate"] },
  { word: "NET ZERO",                taboo: ["balance emissions", "remove", "climate target", "2050", "global"] },
  { word: "BLUE ECONOMY",            taboo: ["ocean", "resources", "sustainable", "India", "coastal"] },
  { word: "CIRCULAR ECONOMY",        taboo: ["reuse", "recycle", "no waste", "sustainable", "loop"] },
  { word: "JUST TRANSITION",         taboo: ["fossil fuel", "clean energy", "workers", "fair", "climate"] },

  // ISRO & India Space (not yet covered in hard)

  // Economics (New)

  // Political Theory (New)

  // ── World Famous Places & Power Centres ──────────────────────────────────
  { word: "SILICON VALLEY",      taboo: ["tech", "California", "startup", "innovation", "companies"] },
  { word: "KREMLIN",             taboo: ["Russia", "Moscow", "government", "president", "power centre"] },
  { word: "PENTAGON",            taboo: ["USA", "defence", "five-sided", "military", "Virginia"] },
  { word: "WALL STREET",         taboo: ["USA", "finance", "New York", "stock", "trade"] },
  { word: "CAPITOL HILL",        taboo: ["USA", "congress", "Washington", "democracy", "senate"] },
  { word: "DAVOS",               taboo: ["Switzerland", "economic forum", "global", "leaders", "annual"] },

  // ── Historical Figures ────────────────────────────────────────────────────
  { word: "NAPOLEON BONAPARTE",  taboo: ["France", "emperor", "military", "exile", "Waterloo"] },
  { word: "MAO ZEDONG",          taboo: ["China", "communist", "revolution", "People's Republic", "Long March"] },
  { word: "JOSEPH STALIN",       taboo: ["Soviet Union", "dictator", "World War II", "communist", "purge"] },
  { word: "CHE GUEVARA",         taboo: ["revolution", "Cuba", "Argentina", "guerrilla", "Marxist"] },
  { word: "ABRAHAM LINCOLN",     taboo: ["USA", "president", "slavery", "Civil War", "assassinated"] },

  // ── Scientists & Thinkers ─────────────────────────────────────────────────
  { word: "ALBERT EINSTEIN",     taboo: ["relativity", "Nobel Prize", "Germany", "genius", "E equals mc squared"] },
  { word: "NIKOLA TESLA",        taboo: ["inventor", "electricity", "AC current", "Serbia", "visionary"] },
  { word: "MARIE CURIE",         taboo: ["scientist", "Poland", "radioactivity", "Nobel Prize", "radium"] },
  { word: "SIGMUND FREUD",       taboo: ["psychiatry", "Austria", "subconscious", "dreams", "analysis"] },
  { word: "CHARLES DARWIN",      taboo: ["evolution", "naturalist", "species", "Galapagos", "natural selection"] },
  { word: "STEPHEN HAWKING",     taboo: ["physicist", "black hole", "wheelchair", "universe", "Cambridge"] },

  // ── Legendary Singers ─────────────────────────────────────────────────────
  { word: "FREDDIE MERCURY",     taboo: ["Queen", "rock", "Bohemian Rhapsody", "charismatic", "British"] },
  { word: "BOB DYLAN",           taboo: ["folk", "USA", "protest songs", "Nobel Prize", "songwriter"] },
  { word: "LUCIANO PAVAROTTI",   taboo: ["opera", "Italian", "tenor", "classical", "Three Tenors"] },

  // ── More World Famous Places (hard) ─────────────────────────────────────
  { word: "PANAMA CANAL",           taboo: ["Central America", "ship", "shortcut", "Atlantic", "Pacific"] },
  { word: "STRAIT OF HORMUZ",       taboo: ["oil", "Persian Gulf", "Iran", "Oman", "strategic"] },
  { word: "LAKE BAIKAL",            taboo: ["Russia", "deepest", "freshwater", "Siberia", "ancient"] },
  { word: "BERMUDA TRIANGLE",       taboo: ["mystery", "disappear", "Atlantic", "ships", "planes"] },
  { word: "SILK ROAD",              taboo: ["ancient", "trade", "China", "Europe", "spices"] },
  { word: "KHYBER PASS",            taboo: ["Pakistan", "Afghanistan", "mountains", "historic", "pass"] },
  { word: "AMAZON BASIN",           taboo: ["South America", "river", "rainforest", "drainage", "vast"] },
  { word: "GOBI DESERT",            taboo: ["Mongolia", "China", "cold desert", "arid", "vast"] },
  { word: "ATACAMA DESERT",         taboo: ["Chile", "driest", "South America", "arid", "Mars-like"] },
  { word: "CAUCASUS MOUNTAINS",     taboo: ["Russia", "Georgia", "mountains", "range", "border"] },
  { word: "HINDU KUSH",             taboo: ["Afghanistan", "Pakistan", "mountains", "pass", "ancient"] },
  { word: "CHALLENGER DEEP",        taboo: ["Mariana", "deepest", "ocean", "11 km", "Pacific"] },
  { word: "GREAT RIFT VALLEY",      taboo: ["Africa", "tectonic", "Kenya", "Ethiopia", "valley"] },
  { word: "SARGASSO SEA",           taboo: ["Atlantic", "no land border", "seaweed", "eels", "mystery"] },
  { word: "URAL MOUNTAINS",         taboo: ["Russia", "Europe-Asia border", "range", "ancient", "Siberia"] },
  { word: "MEKONG RIVER",           taboo: ["Southeast Asia", "rice", "Vietnam", "Laos", "Cambodia"] },
  { word: "FERTILE CRESCENT",       taboo: ["Iraq", "ancient", "farming", "Mesopotamia", "civilization"] },
  { word: "BOSPORUS STRAIT",        taboo: ["Turkey", "Istanbul", "connects", "Black Sea", "Marmara"] },
  { word: "LAKE TANGANYIKA",        taboo: ["Africa", "Tanzania", "Congo", "deep", "freshwater"] },
  { word: "APPALACHIAN MOUNTAINS",  taboo: ["USA", "eastern", "old", "hiking", "trail"] },
  { word: "GULF STREAM",            taboo: ["ocean current", "warm", "Atlantic", "Europe", "climate"] },
  { word: "RING OF FIRE",           taboo: ["Pacific", "volcanoes", "earthquakes", "tectonic", "arc"] },
  { word: "MID-ATLANTIC RIDGE",     taboo: ["underwater", "volcano", "tectonic", "Atlantic", "ridge"] },
  { word: "KALAHARI DESERT",        taboo: ["Africa", "Botswana", "semi-arid", "Bushmen", "savanna"] },
  { word: "NAMIB DESERT",           taboo: ["Namibia", "oldest", "coastal", "dunes", "Africa"] },
  { word: "PYRENEES",               taboo: ["France", "Spain", "border", "mountains", "range"] },
  { word: "SAHEL REGION",           taboo: ["Africa", "drought", "semi-arid", "south Sahara", "transition"] },
  { word: "ARCTIC CIRCLE",          taboo: ["north", "frozen", "midnight sun", "polar", "icy"] },
  { word: "INTERNATIONAL DATE LINE", taboo: ["Pacific", "time", "date change", "180 degrees", "calendar"] },
  { word: "STRAIT OF MALACCA",      taboo: ["Malaysia", "Singapore", "Indonesia", "shipping", "strategic"] },
  { word: "CONGO RAINFOREST",       taboo: ["Africa", "second largest", "Congo", "biodiversity", "basin"] },
  { word: "PRIME MERIDIAN",         taboo: ["Greenwich", "zero degrees", "longitude", "UK", "time zones"] },
  { word: "TIGRIS AND EUPHRATES",   taboo: ["Iraq", "rivers", "Mesopotamia", "ancient", "twin"] },
  { word: "GREAT PLAINS",           taboo: ["USA", "flat", "grassland", "prairies", "central"] },
  { word: "CASPIAN SEA",            taboo: ["largest lake", "Russia", "Iran", "landlocked", "oil"] },
  { word: "LAKE VICTORIA",          taboo: ["Africa", "freshwater", "Nile source", "Uganda", "Tanzania"] },

  // ── Cricket Players (hard) ───────────────────────────────────────────────
  { word: "ALASTAIR COOK",          taboo: ["England", "test runs", "left-hand", "opener", "Sir"] },
  { word: "GRAEME SMITH",           taboo: ["South Africa", "left-hand", "captain", "opener", "tough"] },
  { word: "DAVID WARNER",           taboo: ["Australia", "opener", "left-hand", "aggressive", "ban"] },
  { word: "STEVE SMITH",            taboo: ["Australia", "technical", "unusual stance", "Ashes", "prolific"] },
  { word: "PAT CUMMINS",            taboo: ["Australia", "fast bowler", "captain", "top-ranked", "red ball"] },
  { word: "MITCHELL STARC",         taboo: ["Australia", "left-arm", "yorker", "fast", "swings late"] },
  { word: "MATTHEW HAYDEN",         taboo: ["Australia", "big build", "opener", "aggressive", "left-hand"] },
  { word: "MICHAEL CLARKE",         taboo: ["Australia", "captain", "Pup", "tactical", "batsman"] },
  { word: "MARK TAYLOR",            taboo: ["Australia", "captain", "slip", "opener", "equal Bradman"] },
  { word: "RICHIE BENAUD",          taboo: ["Australia", "commentator", "leg spin", "cap", "iconic voice"] },
  { word: "DENNIS LILLEE",          taboo: ["Australia", "fast bowler", "aggressive", "pace", "moustache"] },
  { word: "JEFF THOMSON",           taboo: ["Australia", "slingy action", "pace", "feared", "extreme speed"] },
  { word: "SURYAKUMAR YADAV",       taboo: ["India", "T20", "360-degree", "SKY", "Mumbai"] },
  { word: "RISHABH PANT",           taboo: ["India", "wicket-keeper", "aggressive", "left-hand", "car accident"] },
  { word: "HARDIK PANDYA",          taboo: ["India", "all-rounder", "World Cup", "fitness", "pace"] },
  { word: "JAVED MIANDAD",          taboo: ["Pakistan", "last ball six", "Sharjah", "batsman", "gritty"] },
  { word: "YOUNIS KHAN",            taboo: ["Pakistan", "most test runs", "captain", "batsman", "Pashto"] },
  { word: "SAEED ANWAR",            taboo: ["Pakistan", "elegant", "194 ODI", "left-hand", "opener"] },
  { word: "INZAMAM-UL-HAQ",         taboo: ["Pakistan", "run outs", "batsman", "big frame", "captain"] },
  { word: "MISBAH-UL-HAQ",          taboo: ["Pakistan", "steady", "captain", "push-ups", "older"] },
  { word: "TAMIM IQBAL",            taboo: ["Bangladesh", "opening", "left-hand", "prolific", "runs"] },
  { word: "SHAKIB AL HASAN",        taboo: ["Bangladesh", "all-rounder", "best", "left-hand", "spin"] },
  { word: "CHAMINDA VAAS",          taboo: ["Sri Lanka", "left-arm swing", "bowling", "early wickets", "seam"] },
  { word: "ANGELO MATHEWS",         taboo: ["Sri Lanka", "all-rounder", "timed out", "captain", "fightback"] },
  { word: "GORDON GREENIDGE",       taboo: ["West Indies", "opener", "aggressive", "Barbados", "deadly"] },
  { word: "DESMOND HAYNES",         taboo: ["West Indies", "opener", "partner Greenidge", "Barbados", "stylish"] },
  { word: "MICHAEL HOLDING",        taboo: ["West Indies", "Whispering Death", "fast", "Jamaica", "graceful"] },
  { word: "CURTLY AMBROSE",         taboo: ["West Indies", "tall", "fast", "lethal", "Antigua"] },
  { word: "COURTNEY WALSH",         taboo: ["West Indies", "wickets", "tall", "fast", "Jamaica"] },
  { word: "DWAYNE BRAVO",           taboo: ["West Indies", "all-rounder", "T20", "Champion", "dancing"] },
  { word: "JASON HOLDER",           taboo: ["West Indies", "tall", "all-rounder", "captain", "seam"] },
  { word: "QUINTON DE KOCK",        taboo: ["South Africa", "wicket-keeper", "opener", "left-hand", "retiring"] },
  { word: "KAGISO RABADA",          taboo: ["South Africa", "fast bowler", "pace", "young", "lethal"] },
  { word: "TEMBA BAVUMA",           taboo: ["South Africa", "captain", "short", "prolific", "composed"] },
  { word: "GRAEME POLLOCK",         taboo: ["South Africa", "legend", "left-hand", "apartheid era", "batting"] },
  { word: "MARTIN CROWE",           taboo: ["New Zealand", "legend", "batsman", "technical", "1992 World Cup"] },
  { word: "DANIEL VETTORI",         taboo: ["New Zealand", "left-arm spin", "captain", "glasses", "all-rounder"] },
  { word: "ROSS TAYLOR",            taboo: ["New Zealand", "runs", "batsman", "right-hand", "Pacific"] },
  { word: "TIM SOUTHEE",            taboo: ["New Zealand", "swing", "seam", "right-arm", "consistent"] },
  { word: "TRENT BOULT",            taboo: ["New Zealand", "left-arm", "swing", "new ball", "opening"] },
  { word: "FRED TRUEMAN",           taboo: ["England", "Fiery Fred", "first 300 wickets", "fast", "Yorkshire"] },
  { word: "GEOFF BOYCOTT",          taboo: ["England", "defensive", "opener", "Yorkshire", "commentator"] },
  { word: "DAVID GOWER",            taboo: ["England", "elegant", "left-hand", "Ashes", "blond"] },
  { word: "IAN HEALY",              taboo: ["Australia", "wicket-keeper", "record stumpings", "Queensland", "gritty"] },
  { word: "GARFIELD SOBERS",        taboo: ["West Indies", "greatest all-rounder", "six sixes", "Sir", "Barbados"] },
  { word: "ZAHEER KHAN",            taboo: ["India", "left-arm swing", "pace", "reverse swing", "seam"] },
  { word: "KEVIN PIETERSEN",        taboo: ["England", "South African-born", "flamboyant", "KP", "switch hit"] },
  { word: "VIRENDER SEHWAG",        taboo: ["India", "aggressive", "opener", "triple century", "Nawab"] },
  { word: "GAUTAM GAMBHIR",         taboo: ["India", "opener", "World Cup", "2011", "Delhi"] },
  { word: "IRFAN PATHAN",           taboo: ["India", "left-arm", "swing", "hat-trick", "all-rounder"] },
  { word: "ZAHEER ABBAS",           taboo: ["Pakistan", "Asian Bradman", "elegant", "glasses", "batsman"] },
  { word: "RAVI SHASTRI",           taboo: ["India", "all-rounder", "coach", "commentator", "six sixes"] },
  { word: "DIMUTH KARUNARATNE",     taboo: ["Sri Lanka", "captain", "test opener", "gritty", "defensive"] },

  // ── Football Players (hard) ──────────────────────────────────────────────
  { word: "RYAN GIGGS",             taboo: ["Wales", "Manchester United", "winger", "longest service", "assists"] },
  { word: "ERIC CANTONA",           taboo: ["France", "Manchester United", "kung fu kick", "collar up", "King"] },
  { word: "BOBBY CHARLTON",         taboo: ["England", "Munich air crash", "Manchester United", "1966", "Sir"] },
  { word: "STANLEY MATTHEWS",       taboo: ["England", "dribbling", "wizard", "winger", "Sir"] },
  { word: "BOBBY MOORE",            taboo: ["England", "captain", "1966 World Cup", "West Ham", "defender"] },
  { word: "GARY LINEKER",           taboo: ["England", "Golden Boot", "no yellow cards", "presenter", "crisp ads"] },
  { word: "GERD MULLER",            taboo: ["Germany", "goal machine", "striker", "Der Bomber", "1974 World Cup"] },
  { word: "JUERGEN KLINSMANN",      taboo: ["Germany", "striker", "dive", "Tottenham", "blond"] },
  { word: "OLIVER KAHN",            taboo: ["Germany", "goalkeeper", "aggressive", "titan", "Bayern"] },
  { word: "DENNIS BERGKAMP",        taboo: ["Netherlands", "no fly", "Arsenal", "technical", "iconic goal"] },
  { word: "RUUD GULLIT",            taboo: ["Netherlands", "AC Milan", "dreadlocks", "total football", "Ballon d'Or"] },
  { word: "ROMARIO",                taboo: ["Brazil", "striker", "small", "prolific", "1994 World Cup"] },
  { word: "RIVALDO",                taboo: ["Brazil", "Barcelona", "Ballon d'Or", "left foot", "1990s"] },
  { word: "CAFU",                   taboo: ["Brazil", "right back", "AC Milan", "overlapping", "1994 World Cup"] },
  { word: "GARRINCHA",              taboo: ["Brazil", "dribbling", "winger", "disability", "1958 World Cup"] },
  { word: "ZICO",                   taboo: ["Brazil", "free kicks", "Flamengo", "1980s", "attacking"] },
  { word: "SOCRATES",               taboo: ["Brazil", "doctor", "captain", "long hair", "smoking"] },
  { word: "ALFREDO DI STEFANO",     taboo: ["Argentina-Spain", "Real Madrid", "European Cup", "unstoppable", "complete"] },
  { word: "RAUL",                   taboo: ["Spain", "Real Madrid", "record", "loyalty", "goals"] },
  { word: "MICHEL PLATINI",         taboo: ["France", "midfielder", "Juventus", "Ballon d'Or", "UEFA president"] },
  { word: "LEV YASHIN",             taboo: ["USSR", "goalkeeper", "Black Spider", "black kit", "only GK Ballon d'Or"] },
  { word: "DINO ZOFF",              taboo: ["Italy", "goalkeeper", "Juventus", "World Cup 1982", "oldest"] },
  { word: "PAUL SCHOLES",           taboo: ["England", "Manchester United", "ginger", "passing", "tackling"] },
  { word: "ROY KEANE",              taboo: ["Ireland", "Manchester United", "fierce", "captain", "leadership"] },
  { word: "DIMITAR BERBATOV",       taboo: ["Bulgaria", "Manchester United", "elegant", "lazy-looking", "smooth"] },
  { word: "MICHAEL BALLACK",        taboo: ["Germany", "Chelsea", "captain", "goals from midfield", "powerful"] },
  { word: "SEEDORF",                taboo: ["Netherlands", "Clarence", "AC Milan", "three clubs", "Champions League"] },
  { word: "PATRICK VIEIRA",         taboo: ["France", "Arsenal", "Invincibles", "tall", "midfielder"] },
  { word: "JAY-JAY OKOCHA",         taboo: ["Nigeria", "dribbling", "PSG", "tricks", "joy"] },
  { word: "MARTA",                  taboo: ["Brazil", "women's", "Pele in skirts", "dribbling", "goals"] },
  { word: "ABBY WAMBACH",           taboo: ["USA", "women's", "goals", "headers", "World Cup"] },
  { word: "MEGAN RAPINOE",          taboo: ["USA", "women's", "activism", "pink hair", "World Cup"] },
  { word: "PAUL POGBA",             taboo: ["France", "Manchester United", "expensive", "dance celebration", "powerful"] },
  { word: "GABRIEL BATISTUTA",      taboo: ["Argentina", "striker", "Fiorentina", "goals", "Batigol"] },
  { word: "JARI LITMANEN",          taboo: ["Finland", "Ajax", "creative", "respected", "Barcelona"] },
  { word: "ZANETTI",                taboo: ["Argentina", "Inter Milan", "right back", "consistent", "loyal"] },
  { word: "PETER SCHMEICHEL",       taboo: ["Denmark", "goalkeeper", "Manchester United", "imposing", "1999"] },
  { word: "UWE SEELER",             taboo: ["Germany", "Hamburg", "four World Cups", "loyal", "short"] },
  { word: "EUSEBIO",                taboo: ["Portugal", "Mozambique-born", "1966 World Cup", "Benfica", "Golden Boot"] },
  { word: "GEORGE WEAH",            taboo: ["Liberia", "president", "AC Milan", "African Ballon d'Or", "first African"] },
  { word: "DIDIER DESCHAMPS",       taboo: ["France", "1998 World Cup", "captain", "manager won World Cup", "water carrier"] },
  { word: "FRANK RIJKAARD",         taboo: ["Netherlands", "AC Milan", "Barcelona manager", "spitting incident", "dignified"] },
  { word: "NWANKWO KANU",           taboo: ["Nigeria", "Arsenal", "heart surgery", "tall", "African"] },
  { word: "SEPP MAIER",             taboo: ["Germany", "goalkeeper", "1974 World Cup", "cat", "Bayern"] },
  { word: "SAM KERR",               taboo: ["Australia", "women's", "Chelsea", "prolific", "backflip"] },
  { word: "ALEXIA PUTELLAS",        taboo: ["Spain", "women's", "Barcelona", "Ballon d'Or", "midfielder"] },
  { word: "BEBETO",                 taboo: ["Brazil", "1994 World Cup", "baby cradle", "striker", "partner Romario"] },
  { word: "RUDI VOLLER",            taboo: ["Germany", "moustache", "striker", "1986 World Cup", "manager"] },
  { word: "KEVIN KEEGAN",           taboo: ["England", "Hamburg", "Liverpool", "perm", "Mighty Mouse"] },
  { word: "GIANFRANCO ZOLA",        taboo: ["Italy", "Chelsea", "wizard", "small", "magic"] },

  // ── Tennis Players (hard) ────────────────────────────────────────────────
  { word: "MARGARET COURT",         taboo: ["Australia", "most Slams", "24", "all surfaces", "controversial"] },
  { word: "EVONNE GOOLAGONG",       taboo: ["Australia", "Aboriginal", "graceful", "Wimbledon", "inspiring"] },
  { word: "MICHAEL CHANG",          taboo: ["USA", "French Open", "youngest", "Asian-American", "17"] },
  { word: "GORAN IVANISEVIC",       taboo: ["Croatia", "serve", "wild card", "Wimbledon", "emotional"] },
  { word: "GUSTAVO KUERTEN",        taboo: ["Brazil", "Guga", "French Open", "heart", "clay"] },
  { word: "LLEYTON HEWITT",         taboo: ["Australia", "Come On", "aggressive", "Wimbledon", "baseliner"] },
  { word: "ANDY RODDICK",           taboo: ["USA", "serve", "US Open", "Sampras replacement", "big forehand"] },
  { word: "PATRICK RAFTER",         taboo: ["Australia", "serve volley", "US Open", "handsome", "crowd favourite"] },
  { word: "PAT CASH",               taboo: ["Australia", "Wimbledon", "climb stands", "checked headband", "serve volley"] },
  { word: "JOHN NEWCOMBE",          taboo: ["Australia", "moustache", "serve volley", "Wimbledon", "doubles"] },
  { word: "KEN ROSEWALL",           taboo: ["Australia", "Muscles", "backhand", "longevity", "classic"] },
  { word: "FRED PERRY",             taboo: ["UK", "last British", "three-peat Wimbledon", "shirts brand", "1930s"] },
  { word: "SUZANNE LENGLEN",        taboo: ["France", "1920s", "first celebrity", "dominant", "fashion"] },
  { word: "BILL TILDEN",            taboo: ["USA", "first American", "1920s", "serve", "dominant"] },
  { word: "PANCHO GONZALES",        taboo: ["USA", "self-taught", "serve", "dominant 1950s", "Latino"] },
  { word: "ILIE NASTASE",           taboo: ["Romania", "temperamental", "entertaining", "first ATP", "Bucharest"] },
  { word: "GUILLERMO VILAS",        taboo: ["Argentina", "clay", "Roland Garros", "poet", "baseliner"] },
  { word: "ARANTXA SANCHEZ VICARIO",taboo: ["Spain", "clay", "French Open", "aggressive", "consistent"] },
  { word: "GABRIELA SABATINI",      taboo: ["Argentina", "perfume", "beautiful", "Wimbledon", "1990s"] },
  { word: "JENNIFER CAPRIATI",      taboo: ["USA", "prodigy", "comeback", "drugs", "Olympic gold"] },
  { word: "JANA NOVOTNA",           taboo: ["Czech", "crying Duchess", "Wimbledon", "serve volley", "emotional"] },
  { word: "CONCHITA MARTINEZ",      taboo: ["Spain", "Wimbledon", "clay", "consistent", "1994"] },
  { word: "MARY PIERCE",            taboo: ["France", "Canadian-born", "French Open", "powerful", "1995"] },
  { word: "ANNA KOURNIKOVA",        taboo: ["Russia", "pretty", "no Slam", "doubles", "model"] },
  { word: "FRANCESCA SCHIAVONE",    taboo: ["Italy", "French Open", "clay", "warrior", "backhand"] },
  { word: "SVETLANA KUZNETSOVA",    taboo: ["Russia", "two Slams", "French Open", "US Open", "cut hair"] },
  { word: "JELENA JANKOVIC",        taboo: ["Serbia", "world number one", "no Slam", "voluble", "consistent"] },
  { word: "ELENA DEMENTIEVA",       taboo: ["Russia", "double faults", "Olympic gold", "baseliner", "consistent"] },
  { word: "DOMINIC THIEM",          taboo: ["Austria", "US Open", "clay", "one-handed backhand", "mental struggles"] },
  { word: "JO-WILFRIED TSONGA",     taboo: ["France", "Ali G", "Wimbledon", "showman", "entertaining"] },
  { word: "GRIGOR DIMITROV",        taboo: ["Bulgaria", "Baby Federer", "ATP Finals", "elegant", "one-handed"] },
  { word: "MILOS RAONIC",           taboo: ["Canada", "serve", "tall", "Wimbledon", "consistent"] },
  { word: "TAYLOR FRITZ",           taboo: ["USA", "Indian Wells", "serve", "baseliner", "American"] },
  { word: "CASPER RUUD",            taboo: ["Norway", "clay", "French Open", "baseline", "Norwegian"] },
  { word: "TOMMY HAAS",             taboo: ["Germany", "comeback", "injury", "athletic", "fan favourite"] },
  { word: "RICHARD GASQUET",        taboo: ["France", "one-handed backhand", "elegant", "clay", "French"] },
  { word: "DAVID FERRER",           taboo: ["Spain", "warrior", "clay", "honest", "consistent"] },
  { word: "TOMAS BERDYCH",          taboo: ["Czech", "tall", "powerful", "Wimbledon final", "baseliner"] },
  { word: "ANDREY RUBLEV",          taboo: ["Russia", "forehand", "aggressive", "young", "ATP"] },
  { word: "FELIX AUGER-ALIASSIME",  taboo: ["Canada", "young", "athletic", "versatile", "ATP"] },
  { word: "HUBERT HURKACZ",         taboo: ["Poland", "serve", "Wimbledon", "tall", "consistent"] },
  { word: "CAMERON NORRIE",         taboo: ["UK", "Indian Wells", "baseliner", "consistent", "left-handed"] },
  { word: "MADISON KEYS",           taboo: ["USA", "power", "Australian Open", "forehand", "grass"] },
  { word: "BIANCA ANDREESCU",       taboo: ["Canada", "US Open", "injury-prone", "young", "2019"] },
  { word: "JESSICA PEGULA",         taboo: ["USA", "Bills owner daughter", "consistent", "baseliner", "ATP"] },
  { word: "BARBORA KREJCIKOVA",     taboo: ["Czech", "Roland Garros", "doubles expert", "all-court", "2021"] },
  { word: "DARIA KASATKINA",        taboo: ["Russia", "clay", "creative", "LGBTQ open", "French Open"] },
  { word: "KAROLINA PLISKOVA",      taboo: ["Czech", "serve", "tall", "US Open final", "Wimbledon final"] },
  { word: "ELINA SVITOLINA",        taboo: ["Ukraine", "consistent", "Wimbledon semi", "flag", "baseliner"] },
  { word: "BELINDA BENCIC",         taboo: ["Switzerland", "Olympic gold", "fast court", "consistent", "all-round"] },
  { word: "CAROLINE WOZNIACKI",     taboo: ["Denmark", "world number one", "US Open", "retired", "McIlroy ex"] },
  { word: "AMELIE MAURESMO",        taboo: ["France", "Australian Open", "Wimbledon", "aggressive", "coach"] },
  { word: "MARTINA HINGIS",         taboo: ["Switzerland", "prodigy", "number one at 16", "Swiss Miss", "all-court"] },
  { word: "VIRGINIA RUZICI",        taboo: ["Romania", "French Open", "1978", "clay", "old era"] },

  // ── Singers (hard) ──────────────────────────────────────────────────────
  { word: "EDITH PIAF",             taboo: ["France", "Little Sparrow", "Non je ne regrette rien", "Paris", "cabaret"] },
  { word: "ELLA FITZGERALD",        taboo: ["USA", "First Lady of Jazz", "scat", "swing", "timeless"] },
  { word: "BILLIE HOLIDAY",         taboo: ["USA", "Strange Fruit", "blues", "jazz", "tragic"] },
  { word: "LOUIS ARMSTRONG",        taboo: ["USA", "Satchmo", "trumpet", "What a Wonderful World", "jazz"] },
  { word: "JOHN COLTRANE",          taboo: ["USA", "saxophone", "avant-garde", "jazz", "A Love Supreme"] },
  { word: "JONI MITCHELL",          taboo: ["Canada", "Big Yellow Taxi", "folk", "guitar", "poetic"] },
  { word: "NEIL YOUNG",             taboo: ["Canada", "Heart of Gold", "grunge godfather", "folk rock", "harvest"] },
  { word: "PAUL SIMON",             taboo: ["USA", "Simon and Garfunkel", "Graceland", "folk pop", "New York"] },
  { word: "SAM COOKE",              taboo: ["USA", "soul", "A Change is Gonna Come", "smooth", "murdered"] },
  { word: "DEAN MARTIN",            taboo: ["USA", "Rat Pack", "crooner", "That's Amore", "suave"] },
  { word: "KENNY ROGERS",           taboo: ["USA", "country", "The Gambler", "beard", "Dolly duet"] },
  { word: "GARTH BROOKS",           taboo: ["USA", "country", "Friends in Low Places", "stadium", "hat"] },
  { word: "SHANIA TWAIN",           taboo: ["Canada", "country pop", "That Don't Impress Me", "crossover", "hat"] },
  { word: "NICKI MINAJ",            taboo: ["Trinidad", "female rap", "Barbie", "colourful", "Super Bass"] },
  { word: "CARDI B",                taboo: ["USA", "rap", "WAP", "Bronx", "outspoken"] },
  { word: "POST MALONE",            taboo: ["USA", "face tattoos", "mumble rap", "Hollywood's Bleeding", "genre-bending"] },
  { word: "KENDRICK LAMAR",         taboo: ["USA", "rap", "To Pimp a Butterfly", "Compton", "lyrical"] },
  { word: "TRAVIS SCOTT",           taboo: ["USA", "Astroworld", "rap", "Nike collab", "concert tragedy"] },
  { word: "LIL WAYNE",              taboo: ["USA", "Tha Carter", "rap", "New Orleans", "prolific"] },
  { word: "SNOOP DOGG",             taboo: ["USA", "Gin and Juice", "rap", "Doggystyle", "California"] },
  { word: "50 CENT",                taboo: ["USA", "In Da Club", "rap", "shot", "Get Rich or Die Tryin"] },
  { word: "PINK",                   taboo: ["USA", "gymnastics", "Get the Party Started", "rock pop", "powerful"] },
  { word: "LIZZO",                  taboo: ["USA", "body positivity", "flute", "Good as Hell", "pop"] },
  { word: "OLIVIA RODRIGO",         taboo: ["USA", "Drivers License", "young", "pop rock", "Disney"] },
  { word: "LORDE",                  taboo: ["New Zealand", "Royals", "indie pop", "young", "dark"] },
  { word: "JAMES BLUNT",            taboo: ["UK", "You're Beautiful", "army officer", "self-deprecating", "sensitive"] },
  { word: "ENRIQUE IGLESIAS",       taboo: ["Spain", "Hero", "Latin pop", "mole removed", "Julio son"] },
  { word: "JULIO IGLESIAS",         taboo: ["Spain", "Spanish pop", "romantic", "Enrique's father", "Latin legend"] },
  { word: "RICKY MARTIN",           taboo: ["Puerto Rico", "Livin La Vida Loca", "Latin pop", "LGBTQ", "Menudo"] },
  { word: "KISHORE KUMAR",          taboo: ["India", "Bollywood", "humour", "versatile", "golden era"] },
  { word: "MOHAMMAD RAFI",          taboo: ["India", "Bollywood", "golden voice", "1950s-70s", "classical base"] },
  { word: "ASHA BHOSLE",            taboo: ["India", "Bollywood", "Lata's sister", "cabaret songs", "prolific"] },
  { word: "SHREYA GHOSHAL",         taboo: ["India", "Bollywood", "sweet voice", "classical", "South India too"] },
  { word: "PLACIDO DOMINGO",        taboo: ["Spain", "opera", "Three Tenors", "tenor", "baritone too"] },
  { word: "ENYA",                   taboo: ["Ireland", "new age", "Only Time", "ethereal", "solitary"] },
  { word: "YANNI",                  taboo: ["Greece", "instrumental", "new age", "Acropolis", "moustache"] },
  { word: "CHARLES AZNAVOUR",       taboo: ["France", "Armenian", "She", "long career", "crooner"] },
  { word: "JIM MORRISON",           taboo: ["USA", "The Doors", "27 club", "poetry", "Light My Fire"] },
  { word: "JANIS JOPLIN",           taboo: ["USA", "blues rock", "27 club", "Me and Bobby McGee", "freedom"] },
  { word: "NINA SIMONE",            taboo: ["USA", "Feeling Good", "classical trained", "civil rights", "deep voice"] },
  { word: "DIANA ROSS",             taboo: ["USA", "Supremes", "Motown", "Ain't No Mountain High", "glamour"] },
  { word: "TINA TURNER",            taboo: ["USA", "Simply the Best", "powerful", "legs", "Proud Mary"] },
  { word: "CHUCK BERRY",            taboo: ["USA", "Johnny B. Goode", "rock and roll", "guitar", "father of rock"] },
  { word: "MILES DAVIS",            taboo: ["USA", "Kind of Blue", "jazz trumpet", "avant-garde", "cool jazz"] },
  { word: "ENGELBERT HUMPERDINCK",  taboo: ["UK", "Please Release Me", "easy listening", "MOR", "romantic baritone"] },

  // ── Celebrities (hard) ──────────────────────────────────────────────────
  { word: "STEVEN SPIELBERG",       taboo: ["director", "Jaws", "Indiana Jones", "Schindler", "Oscars"] },
  { word: "MARTIN SCORSESE",        taboo: ["director", "Goodfellas", "eyebrows", "mobster films", "De Niro collab"] },
  { word: "ALFRED HITCHCOCK",       taboo: ["director", "Psycho", "suspense", "Birds", "silhouette"] },
  { word: "STANLEY KUBRICK",        taboo: ["director", "2001", "Shining", "perfectionist", "recluse"] },
  { word: "QUENTIN TARANTINO",      taboo: ["director", "Pulp Fiction", "dialogue", "violence", "feet"] },
  { word: "CHRISTOPHER NOLAN",      taboo: ["director", "Inception", "Interstellar", "complex plots", "British"] },
  { word: "JAMES CAMERON",          taboo: ["director", "Titanic", "Avatar", "deep sea", "king of world"] },
  { word: "RIDLEY SCOTT",           taboo: ["director", "Gladiator", "Alien", "British", "prolific"] },
  { word: "ORSON WELLES",           taboo: ["director", "Citizen Kane", "radio panic", "genius", "young"] },
  { word: "BUSTER KEATON",          taboo: ["silent film", "stone face", "comedian", "stunts", "1920s"] },
  { word: "WOODY ALLEN",            taboo: ["director", "Annie Hall", "neurotic", "New York", "jazz"] },
  { word: "AUDREY HEPBURN",         taboo: ["actress", "Breakfast at Tiffany's", "elegant", "icon", "Givenchy"] },
  { word: "GRACE KELLY",            taboo: ["actress", "Princess Monaco", "Hitchcock", "elegant", "became royalty"] },
  { word: "KATHARINE HEPBURN",      taboo: ["actress", "four Oscars", "most wins", "independent", "trousers"] },
  { word: "JAMES DEAN",             taboo: ["actor", "rebel", "young death", "Rebel Without a Cause", "icon"] },
  { word: "MARLON BRANDO",          taboo: ["actor", "Godfather", "cotton in mouth", "mumbling", "method acting"] },
  { word: "HUMPHREY BOGART",        taboo: ["actor", "Casablanca", "film noir", "fedora", "tough guy"] },
  { word: "CLARK GABLE",            taboo: ["actor", "Gone With the Wind", "moustache", "Frankly my dear", "classic"] },
  { word: "CARY GRANT",             taboo: ["actor", "suave", "British-American", "Hitchcock", "charm"] },
  { word: "PAUL NEWMAN",            taboo: ["actor", "blue eyes", "salad dressing", "Butch Cassidy", "racing"] },
  { word: "GREGORY PECK",           taboo: ["actor", "Atticus Finch", "To Kill a Mockingbird", "noble", "tall"] },
  { word: "ELIZABETH TAYLOR",       taboo: ["actress", "violet eyes", "many marriages", "Cleopatra", "diamonds"] },
  { word: "SOPHIA LOREN",           taboo: ["Italy", "actress", "Italian beauty", "Oscar", "timeless"] },
  { word: "BRIGITTE BARDOT",        taboo: ["France", "sex symbol", "animal rights", "bikini", "blond"] },
  { word: "VIVIEN LEIGH",           taboo: ["actress", "Scarlett O'Hara", "Gone With the Wind", "British", "bipolar"] },
  { word: "INGRID BERGMAN",         taboo: ["Sweden", "Casablanca", "actress", "natural beauty", "scandal"] },
  { word: "GRETA GARBO",            taboo: ["Sweden", "recluse", "I want to be alone", "silent era", "classic"] },
  { word: "MARLENE DIETRICH",       taboo: ["Germany", "androgynous", "Blue Angel", "sultry", "WWII entertainer"] },
  { word: "BETTE DAVIS",            taboo: ["actress", "eyes", "Whatever Happened to Baby Jane", "fierce", "rivalry"] },
  { word: "NEIL ARMSTRONG",         taboo: ["USA", "first on moon", "1969", "Apollo 11", "astronaut"] },
  { word: "YURI GAGARIN",           taboo: ["Russia", "first in space", "1961", "Vostok", "cosmonaut"] },
  { word: "AMELIA EARHART",         taboo: ["USA", "first woman", "pilot", "disappeared", "Atlantic"] },
  { word: "CHARLES LINDBERGH",      taboo: ["USA", "first solo Atlantic", "pilot", "Spirit of St Louis", "aviator"] },
  { word: "HARRY HOUDINI",          taboo: ["USA", "magician", "escape artist", "handcuffs", "impossible"] },
  { word: "PABLO PICASSO",          taboo: ["Spain", "Cubism", "Guernica", "artist", "many faces"] },
  { word: "SALVADOR DALI",          taboo: ["Spain", "surrealism", "moustache", "melting clocks", "eccentric"] },
  { word: "FRIDA KAHLO",            taboo: ["Mexico", "self-portrait", "unibrow", "pain art", "iconic"] },
  { word: "FRANK CAPRA",            taboo: ["director", "It's a Wonderful Life", "feel-good", "American", "classic"] },
  { word: "BILLY WILDER",           taboo: ["director", "Some Like It Hot", "Austrian", "Sunset Boulevard", "wit"] },
  { word: "RAQUEL WELCH",           taboo: ["actress", "sex symbol", "One Million Years BC", "bikini", "Hollywood"] },
  { word: "JANE FONDA",             taboo: ["actress", "workout videos", "Vietnam protest", "Barbarella", "fitness"] },
  { word: "SHIRLEY TEMPLE",         taboo: ["child star", "curls", "tap dancing", "ambassador", "cocktail"] },
  { word: "DAVID NIVEN",            taboo: ["UK", "suave", "Around the World", "Oscars", "wit"] },
  { word: "REX HARRISON",           taboo: ["UK", "My Fair Lady", "Professor Higgins", "sophisticated", "charm"] },
  { word: "SAMUEL L JACKSON",       taboo: ["USA", "Pulp Fiction", "swearing", "Marvel", "Jules"] },
  { word: "HARRISON FORD",          taboo: ["USA", "Indiana Jones", "Han Solo", "carpenter", "Hollywood"] },
  { word: "SEAN CONNERY",           taboo: ["Scotland", "Bond", "Bond James Bond", "toupee", "accent"] },
  { word: "PETER SELLERS",          taboo: ["UK", "Pink Panther", "Dr Strangelove", "voices", "comedy"] },
  { word: "BUZZ ALDRIN",            taboo: ["USA", "second moon", "Apollo 11", "punch denier", "astronaut"] },
  { word: "STEPHEN HAWKING",        taboo: ["UK", "wheelchair", "black holes", "Brief History of Time", "synthesized voice"] },

  // ── Politicians (hard) ──────────────────────────────────────────────────
  { word: "GORBACHEV",              taboo: ["USSR", "glasnost", "Cold War end", "perestroika", "birthmark"] },
  { word: "KHRUSHCHEV",             taboo: ["USSR", "shoe at UN", "Cuba missiles", "de-Stalinization", "bald"] },
  { word: "LEON TROTSKY",           taboo: ["Russia", "ice pick", "exile", "communist", "Lenin rival"] },
  { word: "BISMARCK",               taboo: ["Germany", "Iron Chancellor", "unification", "Prussia", "19th century"] },
  { word: "KAISER WILHELM II",      taboo: ["Germany", "WWI", "abdicated", "moustache", "rash"] },
  { word: "MUSSOLINI",              taboo: ["Italy", "fascist", "Il Duce", "WWII", "hung upside down"] },
  { word: "FRANCISCO FRANCO",       taboo: ["Spain", "dictator", "fascist", "Civil War", "long rule"] },
  { word: "WOODROW WILSON",         taboo: ["USA", "League of Nations", "WWI", "idealist", "14 points"] },
  { word: "HARRY TRUMAN",           taboo: ["USA", "atomic bomb", "Korea", "Buck stops here", "president"] },
  { word: "LBJ",                    taboo: ["USA", "Vietnam", "Civil Rights Act", "Great Society", "Texas"] },
  { word: "JIMMY CARTER",           taboo: ["USA", "peanut farmer", "Camp David", "Nobel Peace", "president"] },
  { word: "GEORGE HW BUSH",         taboo: ["USA", "Gulf War", "father", "CIA director", "41st president"] },
  { word: "GEORGE W BUSH",          taboo: ["USA", "Iraq War", "9/11", "pretzel choked", "Texas"] },
  { word: "NICOLAS SARKOZY",        taboo: ["France", "president", "Carla Bruni", "right-wing", "small"] },
  { word: "GERHARD SCHROEDER",      taboo: ["Germany", "chancellor", "Russia friendly", "SPD", "Agenda 2010"] },
  { word: "HELMUT KOHL",            taboo: ["Germany", "reunification", "chancellor", "overweight", "CDU"] },
  { word: "KONRAD ADENAUER",        taboo: ["Germany", "first chancellor", "post-war", "CDU", "oldest chancellor"] },
  { word: "THERESA MAY",            taboo: ["UK", "prime minister", "Brexit", "dancing", "strong and stable"] },
  { word: "BORIS JOHNSON",          taboo: ["UK", "prime minister", "Brexit", "blond", "scandal"] },
  { word: "GORDON BROWN",           taboo: ["UK", "prime minister", "Scottish", "financial crisis", "dour"] },
  { word: "HAROLD WILSON",          taboo: ["UK", "prime minister", "pipe", "white heat technology", "Labour"] },
  { word: "CLEMENT ATTLEE",         taboo: ["UK", "prime minister", "NHS founder", "post-war", "Labour"] },
  { word: "HAROLD MACMILLAN",       taboo: ["UK", "prime minister", "wind of change", "Supermac", "Conservative"] },
  { word: "HAILE SELASSIE",         taboo: ["Ethiopia", "emperor", "Rastafari god", "Lion of Judah", "deposed"] },
  { word: "MUAMMAR GADDAFI",        taboo: ["Libya", "eccentric", "dictator", "killed", "Bedouin tent"] },
  { word: "ROBERT MUGABE",          taboo: ["Zimbabwe", "liberation", "dictator", "inflation", "old"] },
  { word: "KWAME NKRUMAH",          taboo: ["Ghana", "first president", "African independence", "pan-African", "deposed"] },
  { word: "JOMO KENYATTA",          taboo: ["Kenya", "first president", "Mau Mau", "independence", "diplomat"] },
  { word: "JULIUS NYERERE",         taboo: ["Tanzania", "first president", "ujamaa", "Mwalimu teacher", "philosophy"] },
  { word: "THOMAS SANKARA",         taboo: ["Burkina Faso", "captain", "revolutionary", "assassinated", "African Che"] },
  { word: "GAMAL NASSER",           taboo: ["Egypt", "pan-Arab", "Suez Canal", "charismatic", "nationalism"] },
  { word: "ANWAR SADAT",            taboo: ["Egypt", "peace with Israel", "assassinated", "Nobel Peace", "Camp David"] },
  { word: "YASSER ARAFAT",          taboo: ["Palestine", "PLO", "keffiyeh", "Nobel Peace", "peace process"] },
  { word: "ARIEL SHARON",           taboo: ["Israel", "Bulldozer", "settlements", "Gaza withdrawal", "coma"] },
  { word: "DAVID BEN-GURION",       taboo: ["Israel", "founder", "first PM", "independence", "white hair"] },
  { word: "GOLDA MEIR",             taboo: ["Israel", "first woman PM", "Iron Lady", "Yom Kippur War", "Milwaukee"] },
  { word: "LULA",                   taboo: ["Brazil", "worker party", "left", "president", "Lula"] },
  { word: "HUGO CHAVEZ",            taboo: ["Venezuela", "socialist", "oil", "Bolivar", "anti-USA"] },
  { word: "EVO MORALES",            taboo: ["Bolivia", "first indigenous", "coca grower", "socialist", "president"] },
  { word: "AUGUSTO PINOCHET",       taboo: ["Chile", "coup", "tortured", "right-wing dictator", "arrested London"] },
  { word: "RAUL CASTRO",            taboo: ["Cuba", "Fidel's brother", "communist", "military", "transition"] },
  { word: "NICOLAS MADURO",         taboo: ["Venezuela", "Chavez successor", "crisis", "authoritarian", "bus driver"] },
  { word: "POL POT",                taboo: ["Cambodia", "Khmer Rouge", "genocide", "Year Zero", "killing fields"] },
  { word: "KIM IL-SUNG",            taboo: ["North Korea", "founder", "eternal president", "dynastic", "cult"] },
  { word: "KIM JONG-UN",            taboo: ["North Korea", "nuclear", "dictator", "haircut", "missiles"] },
  { word: "FERDINAND MARCOS",       taboo: ["Philippines", "dictator", "Imelda shoes", "martial law", "deposed"] },
  { word: "SUKARNO",                taboo: ["Indonesia", "first president", "independence", "non-aligned", "charismatic"] },
  { word: "RECEP ERDOGAN",          taboo: ["Turkey", "president", "authoritarian", "Islam", "elections"] },
  { word: "AYATOLLAH KHOMEINI",     taboo: ["Iran", "revolution 1979", "Supreme Leader", "fatwa", "cleric"] },
  { word: "SHEIKH MUJIBUR RAHMAN",  taboo: ["Bangladesh", "founder", "Bangabandhu", "independence", "assassinated"] },
  { word: "RAMSAY MACDONALD",       taboo: ["UK", "first Labour PM", "national government", "betrayal", "Scottish"] },
  { word: "MIKHAIL GORBACHEV",      taboo: ["USSR", "glasnost", "Nobel Peace", "Cold War", "dissolution"] },
  { word: "PARK CHUNG-HEE",         taboo: ["South Korea", "economic miracle", "dictator", "assassinated", "father"] },
  { word: "PERVEZ MUSHARRAF",       taboo: ["Pakistan", "general", "coup", "9/11 ally", "dictator"] },
];