// words/hard.js — Hard difficulty word bank (52 cards)
// Abstract and complex concepts — for adults and competitive players

const WORDS_HARD = [
  { word: "DEMOCRACY",            taboo: ["vote", "election", "government", "people", "republic"] },
  { word: "CONSTITUTION",         taboo: ["law", "rights", "document", "India", "fundamental"] },
  { word: "INDEPENDENCE",         taboo: ["freedom", "1947", "British", "partition", "August"] },
  { word: "SECULARISM",           taboo: ["religion", "equal", "state", "neutral", "faith"] },
  { word: "JUDICIARY",            taboo: ["court", "law", "judge", "justice", "supreme"] },
  { word: "PHOTOSYNTHESIS",       taboo: ["plant", "sun", "food", "chlorophyll", "oxygen"] },
  { word: "GRAVITY",              taboo: ["fall", "weight", "Newton", "earth", "force"] },
  { word: "EVOLUTION",            taboo: ["Darwin", "species", "adapt", "change", "survival"] },
  { word: "INFLATION",            taboo: ["price", "rise", "economy", "money", "rate"] },
  { word: "GLOBALISATION",        taboo: ["world", "trade", "connect", "international", "economy"] },
  { word: "ECOSYSTEM",            taboo: ["nature", "balance", "food chain", "environment", "life"] },
  { word: "BUREAUCRACY",          taboo: ["government", "office", "process", "file", "rule"] },
  { word: "PARTITION",            taboo: ["1947", "divide", "India", "Pakistan", "border"] },
  { word: "SOVEREIGNTY",          taboo: ["power", "independent", "country", "authority", "rule"] },
  { word: "GREEN REVOLUTION",     taboo: ["wheat", "farm", "India", "food", "production"] },
  { word: "NUCLEAR ENERGY",       taboo: ["atom", "power", "reactor", "radiation", "bomb"] },
  { word: "ARTIFICIAL INTELLIGENCE", taboo: ["machine", "computer", "smart", "robot", "learn"] },
  { word: "CLIMATE CHANGE",       taboo: ["global", "warm", "carbon", "environment", "crisis"] },
  { word: "BIODIVERSITY",         taboo: ["species", "nature", "variety", "ecosystem", "life"] },
  { word: "QUANTUM PHYSICS",      taboo: ["atom", "particle", "energy", "science", "wave"] },
  { word: "COLONIALISM",          taboo: ["British", "rule", "empire", "exploit", "history"] },
  { word: "RENAISSANCE",          taboo: ["art", "Europe", "rebirth", "culture", "history"] },
  { word: "MYTHOLOGY",            taboo: ["god", "story", "ancient", "legend", "epic"] },
  { word: "ARCHAEOLOGY",          taboo: ["dig", "ancient", "artefact", "history", "fossil"] },
  { word: "PHILOSOPHY",           taboo: ["think", "wisdom", "life", "truth", "question"] },
  { word: "CARTOGRAPHY",          taboo: ["map", "draw", "geography", "explore", "chart"] },
  { word: "EPIDEMIOLOGY",         taboo: ["disease", "spread", "study", "outbreak", "health"] },
  { word: "GEOPOLITICS",          taboo: ["country", "power", "border", "politics", "world"] },
  { word: "INDUSTRIALISATION",    taboo: ["factory", "machine", "produce", "growth", "urban"] },
  { word: "URBANISATION",         taboo: ["city", "migrate", "grow", "rural", "population"] },
  { word: "FEMINISM",             taboo: ["women", "equal", "rights", "movement", "gender"] },
  { word: "LIBERALISATION",       taboo: ["open", "economy", "1991", "reform", "India"] },
  { word: "PRIVATISATION",        taboo: ["company", "sell", "government", "private", "economy"] },
  { word: "RESERVATION SYSTEM",   taboo: ["caste", "quota", "college", "job", "India"] },
  { word: "WELFARE STATE",        taboo: ["government", "care", "provide", "citizen", "service"] },
  { word: "FEDERALISM",           taboo: ["state", "central", "power", "government", "share"] },
  { word: "RECESSION",            taboo: ["money", "fall", "jobs", "crisis", "GDP"] },
  { word: "SUSTAINABLE DEVELOPMENT", taboo: ["future", "green", "resource", "balance", "grow"] },
  { word: "NANOTECHNOLOGY",       taboo: ["tiny", "science", "machine", "atom", "future"] },
  { word: "BIOTECHNOLOGY",        taboo: ["gene", "science", "medicine", "DNA", "life"] },
  { word: "NATIONALISM",          taboo: ["country", "pride", "identity", "patriot", "love"] },
  { word: "CASTE SYSTEM",         taboo: ["hierarchy", "India", "birth", "social", "varna"] },
  { word: "FUNDAMENTAL RIGHTS",   taboo: ["constitution", "freedom", "India", "guarantee", "citizen"] },
  { word: "PANCHAYATI RAJ",       taboo: ["village", "self", "govern", "rural", "India"] },
  { word: "NON-COOPERATION",      taboo: ["Gandhi", "British", "resist", "peaceful", "movement"] },
  { word: "SWADESHI",             taboo: ["Indian", "goods", "boycott", "independence", "Gandhi"] },
  { word: "SEPOY MUTINY",         taboo: ["1857", "British", "soldier", "revolt", "India"] },
  { word: "TECTONIC PLATES",      taboo: ["earth", "move", "earthquake", "crust", "geography"] },
  { word: "ZERO",                 taboo: ["number", "India", "nothing", "mathematics", "Aryabhata"] },
  { word: "AYURVEDA",             taboo: ["ancient", "medicine", "herb", "India", "natural"] },
  { word: "MONSOON ECONOMY",      taboo: ["rain", "farm", "India", "depend", "season"] },
  { word: "SPACE RESEARCH",       taboo: ["ISRO", "rocket", "satellite", "moon", "orbit"] },

  // ── 100 additional hard words ──────────────────────────────────────────
  { word: "EXISTENTIALISM",           taboo: ["philosophy", "existence", "meaning", "Sartre", "choice"] },
  { word: "UTILITARIANISM",           taboo: ["greatest", "good", "happiness", "philosophy", "ethics"] },
  { word: "MARXISM",                  taboo: ["class", "worker", "revolution", "communism", "Karl"] },
  { word: "CAPITALISM",               taboo: ["profit", "market", "private", "wealth", "free"] },
  { word: "COMMUNISM",                taboo: ["equal", "class", "state", "revolution", "Karl"] },
  { word: "SOCIALISM",                taboo: ["equal", "share", "government", "welfare", "people"] },
  { word: "FASCISM",                  taboo: ["authoritarian", "extreme", "nation", "control", "leader"] },
  { word: "TOTALITARIANISM",          taboo: ["absolute", "control", "state", "freedom", "dictator"] },
  { word: "THEOCRACY",                taboo: ["god", "rule", "religion", "state", "law"] },
  { word: "OLIGARCHY",                taboo: ["few", "rule", "power", "elite", "group"] },
  { word: "MERITOCRACY",              taboo: ["merit", "talent", "deserve", "earn", "position"] },
  { word: "SEPARATION OF POWERS",     taboo: ["legislature", "executive", "judiciary", "balance", "government"] },
  { word: "CHECKS AND BALANCES",      taboo: ["power", "limit", "government", "branch", "control"] },
  { word: "REFERENDUM",               taboo: ["people", "vote", "direct", "question", "democracy"] },
  { word: "GERRYMANDERING",           taboo: ["boundary", "manipulate", "vote", "unfair", "district"] },
  { word: "COLD WAR",                 taboo: ["USA", "USSR", "tension", "nuclear", "ideology"] },
  { word: "GLASNOST",                 taboo: ["openness", "Soviet", "Gorbachev", "reform", "transparency"] },
  { word: "PERESTROIKA",              taboo: ["reform", "Soviet", "Gorbachev", "economy", "restructure"] },
  { word: "HEGEMONY",                 taboo: ["dominant", "power", "influence", "control", "leader"] },
  { word: "SOFT POWER",               taboo: ["culture", "influence", "attract", "diplomacy", "non-military"] },
  { word: "REALPOLITIK",              taboo: ["practical", "power", "politics", "interest", "national"] },
  { word: "BALANCE OF POWER",         taboo: ["equal", "nations", "prevent", "dominate", "system"] },
  { word: "DETERRENCE",               taboo: ["prevent", "threaten", "military", "nuclear", "attack"] },
  { word: "ARMS RACE",                taboo: ["weapon", "compete", "build", "Cold War", "military"] },
  { word: "DISARMAMENT",              taboo: ["reduce", "weapon", "military", "peace", "treaty"] },
  { word: "SANCTIONS",                taboo: ["punish", "country", "trade", "restrict", "economy"] },
  { word: "EMBARGO",                  taboo: ["block", "trade", "export", "punish", "restrict"] },
  { word: "TARIFF",                   taboo: ["tax", "import", "trade", "protect", "border"] },
  { word: "FREE TRADE",               taboo: ["no barrier", "import", "export", "global", "WTO"] },
  { word: "PROTECTIONISM",            taboo: ["protect", "domestic", "tariff", "industry", "trade"] },
  { word: "KEYNESIAN ECONOMICS",      taboo: ["government", "spend", "recession", "stimulate", "Keynes"] },
  { word: "FISCAL POLICY",            taboo: ["government", "tax", "spend", "budget", "economy"] },
  { word: "MONETARY POLICY",          taboo: ["RBI", "interest", "inflation", "money", "supply"] },
  { word: "STAGFLATION",              taboo: ["stagnant", "inflation", "economy", "problem", "growth"] },
  { word: "TRADE DEFICIT",            taboo: ["import", "more", "export", "less", "balance"] },
  { word: "FOREIGN DIRECT INVESTMENT",taboo: ["company", "invest", "another", "country", "business"] },
  { word: "HUMAN DEVELOPMENT INDEX",  taboo: ["education", "health", "income", "country", "rank"] },
  { word: "GINI COEFFICIENT",         taboo: ["inequality", "income", "measure", "distribution", "society"] },
  { word: "SOCIAL CONTRACT",          taboo: ["people", "government", "agree", "rights", "Rousseau"] },
  { word: "CIVIL DISOBEDIENCE",       taboo: ["law", "refuse", "peaceful", "Gandhi", "protest"] },
  { word: "SATYAGRAHA",               taboo: ["truth", "force", "Gandhi", "nonviolent", "resistance"] },
  { word: "AHIMSA",                   taboo: ["nonviolence", "Gandhi", "harm", "principle", "life"] },
  { word: "SWARAJ",                   taboo: ["self", "rule", "independence", "Gandhi", "India"] },
  { word: "DANDI MARCH",              taboo: ["salt", "Gandhi", "sea", "walk", "protest"] },
  { word: "QUIT INDIA MOVEMENT",      taboo: ["British", "leave", "India", "Gandhi", "1942"] },
  { word: "ROWLATT ACT",              taboo: ["British", "suppress", "India", "law", "protest"] },
  { word: "JALLIANWALA BAGH",         taboo: ["massacre", "Amritsar", "British", "1919", "General Dyer"] },
  { word: "HOME RULE MOVEMENT",       taboo: ["Tilak", "Besant", "India", "govern", "British"] },
  { word: "LUCKNOW PACT",             taboo: ["Congress", "League", "unity", "1916", "Hindu Muslim"] },
  { word: "POONA PACT",               taboo: ["Ambedkar", "Gandhi", "1932", "separate", "electorate"] },
  { word: "MOUNTBATTEN PLAN",         taboo: ["1947", "partition", "independence", "British", "India"] },
  { word: "INTEGRATION OF PRINCELY STATES", taboo: ["Patel", "unite", "India", "state", "five hundred"] },
  { word: "EMERGENCY 1975",           taboo: ["Indira", "suspend", "rights", "1975", "press"] },
  { word: "MANDAL COMMISSION",        taboo: ["OBC", "reservation", "1990", "India", "caste"] },
  { word: "ECONOMIC REFORMS 1991",    taboo: ["liberalise", "IMF", "India", "open", "economy"] },
  { word: "PREAMBLE",                 taboo: ["constitution", "introduction", "India", "begin", "words"] },
  { word: "DIRECTIVE PRINCIPLES",     taboo: ["constitution", "guide", "state", "policy", "rights"] },
  { word: "AMENDMENT",                taboo: ["change", "constitution", "law", "modify", "parliament"] },
  { word: "PARLIAMENTARY SYSTEM",     taboo: ["PM", "cabinet", "majority", "govern", "Westminster"] },
  { word: "PRESIDENTIAL SYSTEM",      taboo: ["president", "executive", "USA", "separate", "elect"] },
  { word: "BICAMERALISM",             taboo: ["two", "house", "parliament", "Rajya Sabha", "Lok Sabha"] },
  { word: "UNIVERSAL ADULT FRANCHISE",taboo: ["every", "adult", "vote", "election", "right"] },
  { word: "ELECTION COMMISSION",      taboo: ["India", "conduct", "election", "independent", "fair"] },
  { word: "CIVIL SERVICES",           taboo: ["IAS", "IPS", "government", "officer", "exam"] },
  { word: "RTI ACT",                  taboo: ["information", "right", "government", "ask", "India"] },
  { word: "JUDICIAL REVIEW",          taboo: ["court", "check", "law", "constitution", "power"] },
  { word: "PUBLIC INTEREST LITIGATION",taboo: ["court", "public", "petition", "India", "law"] },
  { word: "SEDITION",                 taboo: ["against", "government", "law", "speech", "punish"] },
  { word: "SOVEREIGNTY OF PARLIAMENT",taboo: ["supreme", "law", "parliament", "authority", "constitution"] },
  { word: "RADIOACTIVITY",            taboo: ["atom", "decay", "radiation", "nuclear", "energy"] },
  { word: "ELECTROMAGNETIC SPECTRUM", taboo: ["light", "wave", "radio", "X-ray", "frequency"] },
  { word: "THERMODYNAMICS",           taboo: ["heat", "energy", "law", "physics", "transfer"] },
  { word: "RELATIVITY",               taboo: ["Einstein", "space", "time", "speed", "light"] },
  { word: "DARK MATTER",              taboo: ["space", "invisible", "mass", "universe", "mystery"] },
  { word: "BLACK HOLE",               taboo: ["space", "gravity", "pull", "light", "star"] },
  { word: "CELL THEORY",              taboo: ["biology", "basic", "unit", "life", "Schwann"] },
  { word: "DNA",                      taboo: ["gene", "heredity", "double", "helix", "biological"] },
  { word: "CHROMOSOME",               taboo: ["gene", "cell", "DNA", "number", "biological"] },
  { word: "OSMOSIS",                  taboo: ["water", "membrane", "pass", "concentration", "plant"] },
  { word: "PLATE TECTONICS",          taboo: ["earth", "crust", "move", "earthquake", "continental"] },
  { word: "CARBON CYCLE",             taboo: ["carbon", "dioxide", "plant", "absorb", "atmosphere"] },
  { word: "WATER CYCLE",              taboo: ["evaporate", "rain", "cloud", "river", "nature"] },
  { word: "FOOD CHAIN",               taboo: ["predator", "prey", "eat", "energy", "ecosystem"] },
  { word: "DEFORESTATION",            taboo: ["tree", "cut", "forest", "destroy", "environment"] },
  { word: "ACID RAIN",                taboo: ["pollution", "sulphur", "rain", "damage", "chemical"] },
  { word: "OZONE LAYER",              taboo: ["atmosphere", "protect", "UV", "sun", "deplete"] },
  { word: "GREENHOUSE EFFECT",        taboo: ["carbon", "warm", "trap", "gas", "earth"] },
  { word: "RENEWABLE ENERGY",         taboo: ["solar", "wind", "clean", "infinite", "future"] },
  { word: "BLOCKCHAIN",               taboo: ["crypto", "digital", "chain", "record", "secure"] },
  { word: "MACHINE LEARNING",         taboo: ["computer", "learn", "data", "AI", "pattern"] },
  { word: "INTERNET OF THINGS",       taboo: ["device", "connect", "internet", "smart", "sensor"] },
  { word: "CYBERSECURITY",            taboo: ["hack", "protect", "data", "online", "threat"] },
  { word: "VIRTUAL REALITY",          taboo: ["headset", "digital", "immerse", "game", "simulate"] },
  { word: "GENETIC ENGINEERING",      taboo: ["DNA", "modify", "gene", "science", "organism"] },
  { word: "STEM CELLS",               taboo: ["biology", "regenerate", "medicine", "embryo", "research"] },
  { word: "ANTIBIOTIC RESISTANCE",    taboo: ["bacteria", "drug", "resist", "medicine", "overuse"] },
  { word: "PANDEMIC",                 taboo: ["disease", "global", "spread", "COVID", "outbreak"] },
  { word: "HERD IMMUNITY",            taboo: ["population", "immune", "vaccine", "protect", "disease"] },
  { word: "DEMOGRAPHIC DIVIDEND",     taboo: ["young", "population", "India", "work", "economy"] },
  { word: "BRAIN DRAIN",              taboo: ["skilled", "leave", "country", "migrate", "talent"] },
];
