// words/medium.js — Medium difficulty word bank (52 cards)
// Indian cultural references — great for teens and adults

const WORDS_MEDIUM = [
  { word: "DIWALI",          taboo: ["festival", "lights", "crackers", "sweets", "lamp"] },
  { word: "BIRYANI",         taboo: ["rice", "spicy", "meat", "cook", "dish"] },
  { word: "MONSOON",         taboo: ["rain", "June", "season", "wet", "India"] },
  { word: "RICKSHAW",        taboo: ["three", "wheel", "ride", "road", "pedal"] },
  { word: "YOGA",            taboo: ["stretch", "pose", "breathe", "exercise", "mat"] },
  { word: "BOLLYWOOD",       taboo: ["film", "dance", "Mumbai", "Hindi", "song"] },
  { word: "HOLI",            taboo: ["colour", "festival", "spring", "water", "play"] },
  { word: "SARI",            taboo: ["wear", "cloth", "woman", "drape", "silk"] },
  { word: "CURRY",           taboo: ["spicy", "Indian", "cook", "gravy", "dish"] },
  { word: "RUPEE",           taboo: ["money", "India", "currency", "pay", "coin"] },
  { word: "LOTUS",           taboo: ["flower", "water", "national", "pink", "bloom"] },
  { word: "GANGES",          taboo: ["river", "holy", "India", "bath", "city"] },
  { word: "TABLA",           taboo: ["drum", "music", "beat", "Indian", "rhythm"] },
  { word: "MEHNDI",          taboo: ["hand", "design", "bride", "colour", "henna"] },
  { word: "AUTO",            taboo: ["three", "wheel", "city", "ride", "meter"] },
  { word: "PANEER",          taboo: ["cheese", "Indian", "white", "cook", "milk"] },
  { word: "RANGOLI",         taboo: ["colour", "floor", "design", "festival", "art"] },
  { word: "SUGARCANE",       taboo: ["sweet", "juice", "farm", "tall", "sugar"] },
  { word: "DHOL",            taboo: ["drum", "music", "beat", "dance", "festival"] },
  { word: "NAMASTE",         taboo: ["greet", "fold", "hands", "hello", "Indian"] },
  { word: "COCONUT",         taboo: ["tree", "white", "water", "break", "brown"] },
  { word: "JASMINE",         taboo: ["flower", "white", "smell", "garland", "India"] },
  { word: "PAAN",            taboo: ["leaf", "chew", "mouth", "red", "betel"] },
  { word: "TURBAN",          taboo: ["head", "cloth", "Sikh", "wrap", "colour"] },
  { word: "GARLAND",         taboo: ["flower", "neck", "temple", "welcome", "string"] },
  { word: "DHABA",           taboo: ["roadside", "food", "eat", "truck", "cheap"] },
  { word: "SITAR",           taboo: ["string", "music", "Ravi", "Indian", "play"] },
  { word: "BULLOCK CART",    taboo: ["ox", "pull", "wheel", "village", "road"] },
  { word: "FARMER",          taboo: ["crop", "field", "grow", "harvest", "village"] },
  { word: "TAJ MAHAL",       taboo: ["Agra", "white", "marble", "wonder", "Shah Jahan"] },
  { word: "GANDHI",          taboo: ["freedom", "nonviolence", "India", "glasses", "father"] },
  { word: "IDLI",            taboo: ["South", "breakfast", "rice", "steam", "sambar"] },
  { word: "DOSA",            taboo: ["South", "crispy", "rice", "batter", "breakfast"] },
  { word: "CHAIWALA",        taboo: ["tea", "sell", "street", "cup", "vendor"] },
  { word: "KOLKATA",         taboo: ["city", "Bengal", "river", "culture", "east"] },
  { word: "MUMBAI",          taboo: ["city", "film", "sea", "crowd", "Maharashtra"] },
  { word: "BANGALORE",       taboo: ["tech", "IT", "garden", "Karnataka", "city"] },
  { word: "MASALA",          taboo: ["spice", "flavour", "cook", "hot", "India"] },
  { word: "SANSKRIT",        taboo: ["ancient", "language", "script", "Hindu", "old"] },
  { word: "WEDDING",         taboo: ["bride", "groom", "ceremony", "dance", "celebrate"] },
  { word: "ASTROLOGY",       taboo: ["star", "predict", "horoscope", "planet", "future"] },
  { word: "TIFFIN",          taboo: ["lunchbox", "food", "carry", "office", "school"] },
  { word: "VILLAGE",         taboo: ["rural", "farm", "simple", "India", "panchayat"] },
  { word: "CHAAT",           taboo: ["street", "food", "spicy", "tangy", "snack"] },
  { word: "GULAB JAMUN",     taboo: ["sweet", "brown", "syrup", "round", "dessert"] },
  { word: "LASSI",           taboo: ["drink", "yogurt", "Punjab", "cold", "sweet"] },
  { word: "NAVRATRI",        taboo: ["nine", "dance", "festival", "garba", "Gujarat"] },
  { word: "PONGAL",          taboo: ["South", "harvest", "festival", "rice", "Tamil"] },
  { word: "PARLIAMENT",      taboo: ["government", "Delhi", "vote", "law", "MP"] },
  { word: "RICKSHAW PULLER", taboo: ["pull", "ride", "road", "three", "labour"] },
  { word: "EID",             taboo: ["festival", "Muslim", "prayer", "moon", "feast"] },
  { word: "CRICKET STADIUM", taboo: ["ground", "crowd", "match", "seats", "field"] },
];
