// words/medium.js — Medium difficulty word bank (52 cards)
// Indian cultural references — great for teens and adults

const WORDS_MEDIUM = [
  { word: "DIWALI",          taboo: ["festival", "lights", "crackers", "sweets", "lamp"] },
  { word: "BIRYANI",         taboo: ["rice", "spicy", "meat", "cook", "dish"] },
  { word: "MONSOON",         taboo: ["rain", "June", "season", "wet", "India"] },
  { word: "RICKSHAW",        taboo: ["three", "wheel", "ride", "road", "pedal"] },
  { word: "YOGA",            taboo: ["stretch", "pose", "breathe", "exercise", "mat"] },
  { word: "BOLLYWOOD",       taboo: ["film", "dance", "Mumbai", "Hindi", "song"] },
  { word: "HOLI",            taboo: ["colour", "festival", "spring", "water", "play"] },
  { word: "SARI",            taboo: ["wear", "cloth", "woman", "drape", "silk"] },
  { word: "CURRY",           taboo: ["spicy", "Indian", "cook", "gravy", "dish"] },
  { word: "RUPEE",           taboo: ["money", "India", "currency", "pay", "coin"] },
  { word: "LOTUS",           taboo: ["flower", "water", "national", "pink", "bloom"] },
  { word: "GANGES",          taboo: ["river", "holy", "India", "bath", "city"] },
  { word: "TABLA",           taboo: ["drum", "music", "beat", "Indian", "rhythm"] },
  { word: "MEHNDI",          taboo: ["hand", "design", "bride", "colour", "henna"] },
  { word: "AUTO",            taboo: ["three", "wheel", "city", "ride", "meter"] },
  { word: "PANEER",          taboo: ["cheese", "Indian", "white", "cook", "milk"] },
  { word: "RANGOLI",         taboo: ["colour", "floor", "design", "festival", "art"] },
  { word: "SUGARCANE",       taboo: ["sweet", "juice", "farm", "tall", "sugar"] },
  { word: "DHOL",            taboo: ["drum", "music", "beat", "dance", "festival"] },
  { word: "NAMASTE",         taboo: ["greet", "fold", "hands", "hello", "Indian"] },
  { word: "COCONUT",         taboo: ["tree", "white", "water", "break", "brown"] },
  { word: "JASMINE",         taboo: ["flower", "white", "smell", "garland", "India"] },
  { word: "PAAN",            taboo: ["leaf", "chew", "mouth", "red", "betel"] },
  { word: "TURBAN",          taboo: ["head", "cloth", "Sikh", "wrap", "colour"] },
  { word: "GARLAND",         taboo: ["flower", "neck", "temple", "welcome", "string"] },
  { word: "DHABA",           taboo: ["roadside", "food", "eat", "truck", "cheap"] },
  { word: "SITAR",           taboo: ["string", "music", "Ravi", "Indian", "play"] },
  { word: "BULLOCK CART",    taboo: ["ox", "pull", "wheel", "village", "road"] },
  { word: "FARMER",          taboo: ["crop", "field", "grow", "harvest", "village"] },
  { word: "TAJ MAHAL",       taboo: ["Agra", "white", "marble", "wonder", "Shah Jahan"] },
  { word: "GANDHI",          taboo: ["freedom", "nonviolence", "India", "glasses", "father"] },
  { word: "IDLI",            taboo: ["South", "breakfast", "rice", "steam", "sambar"] },
  { word: "DOSA",            taboo: ["South", "crispy", "rice", "batter", "breakfast"] },
  { word: "CHAIWALA",        taboo: ["tea", "sell", "street", "cup", "vendor"] },
  { word: "KOLKATA",         taboo: ["city", "Bengal", "river", "culture", "east"] },
  { word: "MUMBAI",          taboo: ["city", "film", "sea", "crowd", "Maharashtra"] },
  { word: "BANGALORE",       taboo: ["tech", "IT", "garden", "Karnataka", "city"] },
  { word: "MASALA",          taboo: ["spice", "flavour", "cook", "hot", "India"] },
  { word: "SANSKRIT",        taboo: ["ancient", "language", "script", "Hindu", "old"] },
  { word: "WEDDING",         taboo: ["bride", "groom", "ceremony", "dance", "celebrate"] },
  { word: "ASTROLOGY",       taboo: ["star", "predict", "horoscope", "planet", "future"] },
  { word: "TIFFIN",          taboo: ["lunchbox", "food", "carry", "office", "school"] },
  { word: "VILLAGE",         taboo: ["rural", "farm", "simple", "India", "panchayat"] },
  { word: "CHAAT",           taboo: ["street", "food", "spicy", "tangy", "snack"] },
  { word: "GULAB JAMUN",     taboo: ["sweet", "brown", "syrup", "round", "dessert"] },
  { word: "LASSI",           taboo: ["drink", "yogurt", "Punjab", "cold", "sweet"] },
  { word: "NAVRATRI",        taboo: ["nine", "dance", "festival", "garba", "Gujarat"] },
  { word: "PONGAL",          taboo: ["South", "harvest", "festival", "rice", "Tamil"] },
  { word: "PARLIAMENT",      taboo: ["government", "Delhi", "vote", "law", "MP"] },
  { word: "RICKSHAW PULLER", taboo: ["pull", "ride", "road", "three", "labour"] },
  { word: "EID",             taboo: ["festival", "Muslim", "prayer", "moon", "feast"] },
  { word: "CRICKET STADIUM", taboo: ["ground", "crowd", "match", "seats", "field"] },

  // ── 100 additional medium words ────────────────────────────────────────
  { word: "ASHOKA",             taboo: ["emperor", "India", "lion", "pillar", "peace"] },
  { word: "AKBAR",              taboo: ["Mughal", "emperor", "great", "India", "history"] },
  { word: "SHIVAJI",            taboo: ["Maratha", "warrior", "Maharashtra", "fort", "brave"] },
  { word: "CHANDRAGUPTA",       taboo: ["Maurya", "emperor", "ancient", "India", "Pataliputra"] },
  { word: "RANI LAXMIBAI",      taboo: ["Jhansi", "brave", "queen", "1857", "sword"] },
  { word: "NETAJI",             taboo: ["Subhash", "INA", "freedom", "Bengal", "brave"] },
  { word: "NEHRU",              taboo: ["first", "PM", "India", "rose", "children"] },
  { word: "SARDAR PATEL",       taboo: ["Iron Man", "India", "unite", "Gujarat", "states"] },
  { word: "AMBEDKAR",           taboo: ["constitution", "Dalit", "rights", "law", "India"] },
  { word: "BINDI",              taboo: ["forehead", "red", "woman", "India", "dot"] },
  { word: "BANGLES",            taboo: ["wrist", "wear", "glass", "colour", "woman"] },
  { word: "SINDOOR",            taboo: ["married", "red", "woman", "India", "Hindu"] },
  { word: "MANGALSUTRA",        taboo: ["married", "necklace", "black", "gold", "Hindu"] },
  { word: "PUJA",               taboo: ["worship", "pray", "flower", "incense", "god"] },
  { word: "AARTI",              taboo: ["lamp", "wave", "worship", "temple", "sing"] },
  { word: "PRASAD",             taboo: ["temple", "sweet", "distribute", "god", "eat"] },
  { word: "HAVAN",              taboo: ["fire", "ritual", "smoke", "priest", "Hindu"] },
  { word: "PANDIT",             taboo: ["priest", "Hindu", "ritual", "temple", "Sanskrit"] },
  { word: "GURDWARA",           taboo: ["Sikh", "temple", "worship", "langar", "prayer"] },
  { word: "LANGAR",             taboo: ["Sikh", "free", "food", "serve", "community"] },
  { word: "IFTAR",              taboo: ["break", "fast", "Muslim", "evening", "Ramadan"] },
  { word: "RAMAYANA",           taboo: ["epic", "Ram", "Sita", "Hanuman", "story"] },
  { word: "MAHABHARATA",        taboo: ["epic", "Pandava", "Kaurava", "war", "story"] },
  { word: "BHAGAVAD GITA",      taboo: ["Krishna", "teaching", "Arjuna", "book", "Hindu"] },
  { word: "VEENA",              taboo: ["string", "South", "music", "classical", "play"] },
  { word: "FLUTE",              taboo: ["blow", "music", "Krishna", "bamboo", "melody"] },
  { word: "MRIDANGAM",          taboo: ["drum", "South", "music", "classical", "rhythm"] },
  { word: "KATHAK",             taboo: ["dance", "classical", "North", "spin", "costume"] },
  { word: "BHARATANATYAM",      taboo: ["dance", "South", "classical", "expression", "Tamil"] },
  { word: "GARBA",              taboo: ["dance", "Gujarat", "circle", "Navratri", "festival"] },
  { word: "BHANGRA",            taboo: ["dance", "Punjab", "harvest", "lively", "dhol"] },
  { word: "BIHU",               taboo: ["dance", "Assam", "festival", "harvest", "northeast"] },
  { word: "CARNATIC MUSIC",     taboo: ["South", "classical", "vocal", "rhythm", "Madras"] },
  { word: "HINDUSTANI MUSIC",   taboo: ["North", "classical", "raga", "vocal", "tabla"] },
  { word: "FOLK SONG",          taboo: ["village", "traditional", "language", "sing", "culture"] },
  { word: "RAMLEELA",           taboo: ["play", "Ram", "drama", "Dussehra", "stage"] },
  { word: "NALANDA",            taboo: ["ancient", "university", "Bihar", "Buddhist", "knowledge"] },
  { word: "AJANTA CAVES",       taboo: ["Buddhist", "painting", "cave", "ancient", "Maharashtra"] },
  { word: "ELLORA CAVES",       taboo: ["cave", "rock", "ancient", "Maharashtra", "temple"] },
  { word: "KONARK",             taboo: ["sun", "temple", "Odisha", "stone", "wheel"] },
  { word: "HAMPI",              taboo: ["ancient", "Karnataka", "Vijayanagara", "ruins", "history"] },
  { word: "QUTUB MINAR",        taboo: ["tall", "Delhi", "stone", "minaret", "ancient"] },
  { word: "RED FORT",           taboo: ["Delhi", "Mughal", "red", "stone", "independence"] },
  { word: "GOLDEN TEMPLE",      taboo: ["Sikh", "Amritsar", "gold", "sacred", "Punjab"] },
  { word: "INDIA GATE",         taboo: ["Delhi", "war", "memorial", "arch", "national"] },
  { word: "CHARMINAR",          taboo: ["Hyderabad", "mosque", "four", "tower", "landmark"] },
  { word: "GATEWAY OF INDIA",   taboo: ["Mumbai", "arch", "British", "sea", "landmark"] },
  { word: "VICTORIA MEMORIAL",  taboo: ["Kolkata", "white", "British", "marble", "museum"] },
  { word: "KUMBH MELA",         taboo: ["river", "holy", "crowd", "pilgrimage", "huge"] },
  { word: "PUSHKAR FAIR",       taboo: ["camel", "Rajasthan", "festival", "colourful", "trade"] },
  { word: "SUNDARBANS",         taboo: ["mangrove", "Bengal", "tiger", "forest", "delta"] },
  { word: "KAZIRANGA",          taboo: ["rhino", "Assam", "wildlife", "park", "reserve"] },
  { word: "KERALA BACKWATERS",  taboo: ["boat", "Kerala", "water", "calm", "coconut"] },
  { word: "RANN OF KUTCH",      taboo: ["salt", "Gujarat", "white", "vast", "desert"] },
  { word: "BRAHMAPUTRA",        taboo: ["river", "Assam", "long", "northeast", "flood"] },
  { word: "YAMUNA",             taboo: ["river", "Delhi", "holy", "long", "pollution"] },
  { word: "NARMADA",            taboo: ["river", "central", "India", "holy", "dam"] },
  { word: "GODAVARI",           taboo: ["river", "Andhra", "South", "long", "holy"] },
  { word: "KAVERI",             taboo: ["river", "South", "sacred", "Tamil Nadu", "dam"] },
  { word: "CHILIKA LAKE",       taboo: ["Odisha", "lake", "bird", "largest", "migratory"] },
  { word: "DAL LAKE",           taboo: ["Kashmir", "houseboat", "Srinagar", "boat", "beauty"] },
  { word: "BINDI",              taboo: ["forehead", "dot", "woman", "India", "mark"] },
  { word: "DURGA PUJA",         taboo: ["Bengal", "goddess", "festival", "worship", "pandal"] },
  { word: "ONAM",               taboo: ["Kerala", "harvest", "festival", "flower", "boat"] },
  { word: "BAISAKHI",           taboo: ["Punjab", "harvest", "Sikh", "festival", "dance"] },
  { word: "UGADI",              taboo: ["New Year", "Karnataka", "Andhra", "festival", "neem"] },
  { word: "GUDI PADWA",         taboo: ["Maharashtra", "New Year", "festival", "flag", "celebrate"] },
  { word: "MAKAR SANKRANTI",    taboo: ["kite", "festival", "harvest", "January", "sesame"] },
  { word: "RAKSHA BANDHAN",     taboo: ["brother", "sister", "thread", "tie", "festival"] },
  { word: "JANMASHTAMI",        taboo: ["Krishna", "birth", "festival", "celebrate", "dahi handi"] },
  { word: "GANESH CHATURTHI",   taboo: ["Ganesh", "festival", "Maharashtra", "idol", "immerse"] },
  { word: "DHANTERAS",          taboo: ["gold", "buy", "Diwali", "wealth", "festival"] },
  { word: "LOHRI",              taboo: ["Punjab", "fire", "winter", "festival", "harvest"] },
  { word: "PONGAL RICE",        taboo: ["sweet", "cook", "South", "festival", "new pot"] },
  { word: "VADA PAV",           taboo: ["Mumbai", "bread", "potato", "street", "snack"] },
  { word: "PAV BHAJI",          taboo: ["bread", "vegetable", "Mumbai", "street", "butter"] },
  { word: "CHOLE BHATURE",      taboo: ["Punjab", "chickpea", "fried", "bread", "North"] },
  { word: "RAJMA CHAWAL",       taboo: ["kidney", "bean", "rice", "North", "cook"] },
  { word: "THALI",              taboo: ["plate", "round", "meal", "full", "Indian"] },
  { word: "STREET FOOD",        taboo: ["outside", "sell", "eat", "cheap", "tasty"] },
  { word: "BAZAAR",             taboo: ["market", "buy", "sell", "shop", "crowd"] },
  { word: "DARJEELING",         taboo: ["tea", "hill", "West Bengal", "train", "mountain"] },
  { word: "SHIMLA",             taboo: ["hill", "Himachal", "cool", "British, capital", "snow"] },
  { word: "GULMARG",            taboo: ["snow", "Kashmir", "ski", "hill", "meadow"] },
  { word: "VARANASI",           taboo: ["holy", "Ganga", "temple", "city", "Shiva"] },
  { word: "AMRITSAR",           taboo: ["Punjab", "Golden Temple", "city", "border", "Sikh"] },
  { word: "JAIPUR",             taboo: ["pink", "city", "Rajasthan", "fort", "palace"] },
  { word: "UDAIPUR",            taboo: ["lake", "palace", "Rajasthan", "royal", "city"] },
  { word: "MYSORE",             taboo: ["palace", "Karnataka", "sandalwood", "city", "royal"] },
  { word: "PONDICHERRY",        taboo: ["French", "South", "coastal", "quiet", "city"] },
  { word: "LAKSHADWEEP",        taboo: ["island", "coral", "sea", "tiny", "Union Territory"] },
  { word: "ANDAMAN ISLANDS",    taboo: ["island", "sea", "blue", "prison", "British"] },
  { word: "NORTH EAST INDIA",   taboo: ["seven sisters", "tribal", "forest", "remote", "India"] },
  { word: "STATUE OF UNITY",    taboo: ["Patel", "Gujarat", "tall", "statue", "river"] },
  { word: "CHHATRAPATI",        taboo: ["title", "Shivaji", "Maratha", "king", "honour"] },
  { word: "LOKPAL",             taboo: ["ombudsman", "India", "corruption", "investigate", "law"] },
  { word: "PANCHAYAT",          taboo: ["village", "council", "govern", "rural", "elected"] },
  { word: "ANGANWADI",          taboo: ["child", "village", "nutrition", "care", "government"] },
  { word: "RATION SHOP",        taboo: ["food", "government", "cheap", "card", "supply"] },
  { word: "KHADI",              taboo: ["cloth", "Gandhi", "hand", "spin", "Indian"] },
];
