// words/medium.js — Medium difficulty word bank (52 cards)
// Indian cultural references — great for teens and adults

const WORDS_MEDIUM = [
  { word: "DIWALI",          taboo: ["festival", "lights", "crackers", "sweets", "lamp"] },
  { word: "BIRYANI",         taboo: ["rice", "spicy", "meat", "cook", "dish"] },
  { word: "MONSOON",         taboo: ["rain", "June", "season", "wet", "India"] },
  { word: "RICKSHAW",        taboo: ["three", "wheel", "ride", "road", "pedal"] },
  { word: "YOGA",            taboo: ["stretch", "pose", "breathe", "exercise", "mat"] },
  { word: "BOLLYWOOD",       taboo: ["film", "dance", "Mumbai", "Hindi", "song"] },
  { word: "HOLI",            taboo: ["colour", "festival", "spring", "water", "play"] },
  { word: "SARI",            taboo: ["wear", "cloth", "woman", "drape", "silk"] },
  { word: "CURRY",           taboo: ["spicy", "Indian", "cook", "gravy", "dish"] },
  { word: "RUPEE",           taboo: ["money", "India", "currency", "pay", "coin"] },
  { word: "LOTUS",           taboo: ["flower", "water", "national", "pink", "bloom"] },
  { word: "GANGES",          taboo: ["river", "holy", "India", "bath", "city"] },
  { word: "TABLA",           taboo: ["drum", "music", "beat", "Indian", "rhythm"] },
  { word: "MEHNDI",          taboo: ["hand", "design", "bride", "colour", "henna"] },
  { word: "AUTO",            taboo: ["three", "wheel", "city", "ride", "meter"] },
  { word: "PANEER",          taboo: ["cheese", "Indian", "white", "cook", "milk"] },
  { word: "RANGOLI",         taboo: ["colour", "floor", "design", "festival", "art"] },
  { word: "SUGARCANE",       taboo: ["sweet", "juice", "farm", "tall", "sugar"] },
  { word: "DHOL",            taboo: ["drum", "music", "beat", "dance", "festival"] },
  { word: "NAMASTE",         taboo: ["greet", "fold", "hands", "hello", "Indian"] },
  { word: "COCONUT",         taboo: ["tree", "white", "water", "break", "brown"] },
  { word: "JASMINE",         taboo: ["flower", "white", "smell", "garland", "India"] },
  { word: "PAAN",            taboo: ["leaf", "chew", "mouth", "red", "betel"] },
  { word: "TURBAN",          taboo: ["head", "cloth", "Sikh", "wrap", "colour"] },
  { word: "GARLAND",         taboo: ["flower", "neck", "temple", "welcome", "string"] },
  { word: "DHABA",           taboo: ["roadside", "food", "eat", "truck", "cheap"] },
  { word: "SITAR",           taboo: ["string", "music", "Ravi", "Indian", "play"] },
  { word: "BULLOCK CART",    taboo: ["ox", "pull", "wheel", "village", "road"] },
  { word: "FARMER",          taboo: ["crop", "field", "grow", "harvest", "village"] },
  { word: "TAJ MAHAL",       taboo: ["Agra", "white", "marble", "wonder", "Shah Jahan"] },
  { word: "GANDHI",          taboo: ["freedom", "nonviolence", "India", "glasses", "father"] },
  { word: "IDLI",            taboo: ["South", "breakfast", "rice", "steam", "sambar"] },
  { word: "DOSA",            taboo: ["South", "crispy", "rice", "batter", "breakfast"] },
  { word: "CHAIWALA",        taboo: ["tea", "sell", "street", "cup", "vendor"] },
  { word: "KOLKATA",         taboo: ["city", "Bengal", "river", "culture", "east"] },
  { word: "MUMBAI",          taboo: ["city", "film", "sea", "crowd", "Maharashtra"] },
  { word: "BANGALORE",       taboo: ["tech", "IT", "garden", "Karnataka", "city"] },
  { word: "MASALA",          taboo: ["spice", "flavour", "cook", "hot", "India"] },
  { word: "SANSKRIT",        taboo: ["ancient", "language", "script", "Hindu", "old"] },
  { word: "WEDDING",         taboo: ["bride", "groom", "ceremony", "dance", "celebrate"] },
  { word: "ASTROLOGY",       taboo: ["star", "predict", "horoscope", "planet", "future"] },
  { word: "TIFFIN",          taboo: ["lunchbox", "food", "carry", "office", "school"] },
  { word: "VILLAGE",         taboo: ["rural", "farm", "simple", "India", "panchayat"] },
  { word: "CHAAT",           taboo: ["street", "food", "spicy", "tangy", "snack"] },
  { word: "GULAB JAMUN",     taboo: ["sweet", "brown", "syrup", "round", "dessert"] },
  { word: "LASSI",           taboo: ["drink", "yogurt", "Punjab", "cold", "sweet"] },
  { word: "NAVRATRI",        taboo: ["nine", "dance", "festival", "garba", "Gujarat"] },
  { word: "PONGAL",          taboo: ["South", "harvest", "festival", "rice", "Tamil"] },
  { word: "PARLIAMENT",      taboo: ["government", "Delhi", "vote", "law", "MP"] },
  { word: "RICKSHAW PULLER", taboo: ["pull", "ride", "road", "three", "labour"] },
  { word: "EID",             taboo: ["festival", "Muslim", "prayer", "moon", "feast"] },
  { word: "CRICKET STADIUM", taboo: ["ground", "crowd", "match", "seats", "field"] },

  // ── 100 additional medium words ────────────────────────────────────────
  { word: "ASHOKA",             taboo: ["emperor", "India", "lion", "pillar", "peace"] },
  { word: "AKBAR",              taboo: ["Mughal", "emperor", "great", "India", "history"] },
  { word: "SHIVAJI",            taboo: ["Maratha", "warrior", "Maharashtra", "fort", "brave"] },
  { word: "CHANDRAGUPTA",       taboo: ["Maurya", "emperor", "ancient", "India", "Pataliputra"] },
  { word: "RANI LAXMIBAI",      taboo: ["Jhansi", "brave", "queen", "1857", "sword"] },
  { word: "NETAJI",             taboo: ["Subhash", "INA", "freedom", "Bengal", "brave"] },
  { word: "NEHRU",              taboo: ["first", "PM", "India", "rose", "children"] },
  { word: "SARDAR PATEL",       taboo: ["Iron Man", "India", "unite", "Gujarat", "states"] },
  { word: "AMBEDKAR",           taboo: ["constitution", "Dalit", "rights", "law", "India"] },
  { word: "BINDI",              taboo: ["forehead", "red", "woman", "India", "dot"] },
  { word: "BANGLES",            taboo: ["wrist", "wear", "glass", "colour", "woman"] },
  { word: "SINDOOR",            taboo: ["married", "red", "woman", "India", "Hindu"] },
  { word: "MANGALSUTRA",        taboo: ["married", "necklace", "black", "gold", "Hindu"] },
  { word: "PUJA",               taboo: ["worship", "pray", "flower", "incense", "god"] },
  { word: "AARTI",              taboo: ["lamp", "wave", "worship", "temple", "sing"] },
  { word: "PRASAD",             taboo: ["temple", "sweet", "distribute", "god", "eat"] },
  { word: "HAVAN",              taboo: ["fire", "ritual", "smoke", "priest", "Hindu"] },
  { word: "PANDIT",             taboo: ["priest", "Hindu", "ritual", "temple", "Sanskrit"] },
  { word: "GURDWARA",           taboo: ["Sikh", "temple", "worship", "langar", "prayer"] },
  { word: "LANGAR",             taboo: ["Sikh", "free", "food", "serve", "community"] },
  { word: "IFTAR",              taboo: ["break", "fast", "Muslim", "evening", "Ramadan"] },
  { word: "RAMAYANA",           taboo: ["epic", "Ram", "Sita", "Hanuman", "story"] },
  { word: "MAHABHARATA",        taboo: ["epic", "Pandava", "Kaurava", "war", "story"] },
  { word: "BHAGAVAD GITA",      taboo: ["Krishna", "teaching", "Arjuna", "book", "Hindu"] },
  { word: "VEENA",              taboo: ["string", "South", "music", "classical", "play"] },
  { word: "FLUTE",              taboo: ["blow", "music", "Krishna", "bamboo", "melody"] },
  { word: "MRIDANGAM",          taboo: ["drum", "South", "music", "classical", "rhythm"] },
  { word: "KATHAK",             taboo: ["dance", "classical", "North", "spin", "costume"] },
  { word: "BHARATANATYAM",      taboo: ["dance", "South", "classical", "expression", "Tamil"] },
  { word: "GARBA",              taboo: ["dance", "Gujarat", "circle", "Navratri", "festival"] },
  { word: "BHANGRA",            taboo: ["dance", "Punjab", "harvest", "lively", "dhol"] },
  { word: "BIHU",               taboo: ["dance", "Assam", "festival", "harvest", "northeast"] },
  { word: "CARNATIC MUSIC",     taboo: ["South", "classical", "vocal", "rhythm", "Madras"] },
  { word: "HINDUSTANI MUSIC",   taboo: ["North", "classical", "raga", "vocal", "tabla"] },
  { word: "FOLK SONG",          taboo: ["village", "traditional", "language", "sing", "culture"] },
  { word: "RAMLEELA",           taboo: ["play", "Ram", "drama", "Dussehra", "stage"] },
  { word: "NALANDA",            taboo: ["ancient", "university", "Bihar", "Buddhist", "knowledge"] },
  { word: "AJANTA CAVES",       taboo: ["Buddhist", "painting", "cave", "ancient", "Maharashtra"] },
  { word: "ELLORA CAVES",       taboo: ["cave", "rock", "ancient", "Maharashtra", "temple"] },
  { word: "KONARK",             taboo: ["sun", "temple", "Odisha", "stone", "wheel"] },
  { word: "HAMPI",              taboo: ["ancient", "Karnataka", "Vijayanagara", "ruins", "history"] },
  { word: "QUTUB MINAR",        taboo: ["tall", "Delhi", "stone", "minaret", "ancient"] },
  { word: "RED FORT",           taboo: ["Delhi", "Mughal", "red", "stone", "independence"] },
  { word: "GOLDEN TEMPLE",      taboo: ["Sikh", "Amritsar", "gold", "sacred", "Punjab"] },
  { word: "INDIA GATE",         taboo: ["Delhi", "war", "memorial", "arch", "national"] },
  { word: "CHARMINAR",          taboo: ["Hyderabad", "mosque", "four", "tower", "landmark"] },
  { word: "GATEWAY OF INDIA",   taboo: ["Mumbai", "arch", "British", "sea", "landmark"] },
  { word: "VICTORIA MEMORIAL",  taboo: ["Kolkata", "white", "British", "marble", "museum"] },
  { word: "KUMBH MELA",         taboo: ["river", "holy", "crowd", "pilgrimage", "huge"] },
  { word: "PUSHKAR FAIR",       taboo: ["camel", "Rajasthan", "festival", "colourful", "trade"] },
  { word: "SUNDARBANS",         taboo: ["mangrove", "Bengal", "tiger", "forest", "delta"] },
  { word: "KAZIRANGA",          taboo: ["rhino", "Assam", "wildlife", "park", "reserve"] },
  { word: "KERALA BACKWATERS",  taboo: ["boat", "Kerala", "water", "calm", "coconut"] },
  { word: "RANN OF KUTCH",      taboo: ["salt", "Gujarat", "white", "vast", "desert"] },
  { word: "BRAHMAPUTRA",        taboo: ["river", "Assam", "long", "northeast", "flood"] },
  { word: "YAMUNA",             taboo: ["river", "Delhi", "holy", "long", "pollution"] },
  { word: "NARMADA",            taboo: ["river", "central", "India", "holy", "dam"] },
  { word: "GODAVARI",           taboo: ["river", "Andhra", "South", "long", "holy"] },
  { word: "KAVERI",             taboo: ["river", "South", "sacred", "Tamil Nadu", "dam"] },
  { word: "CHILIKA LAKE",       taboo: ["Odisha", "lake", "bird", "largest", "migratory"] },
  { word: "DAL LAKE",           taboo: ["Kashmir", "houseboat", "Srinagar", "boat", "beauty"] },
  { word: "DURGA PUJA",         taboo: ["Bengal", "goddess", "festival", "worship", "pandal"] },
  { word: "ONAM",               taboo: ["Kerala", "harvest", "festival", "flower", "boat"] },
  { word: "BAISAKHI",           taboo: ["Punjab", "harvest", "Sikh", "festival", "dance"] },
  { word: "UGADI",              taboo: ["New Year", "Karnataka", "Andhra", "festival", "neem"] },
  { word: "GUDI PADWA",         taboo: ["Maharashtra", "New Year", "festival", "flag", "celebrate"] },
  { word: "MAKAR SANKRANTI",    taboo: ["kite", "festival", "harvest", "January", "sesame"] },
  { word: "RAKSHA BANDHAN",     taboo: ["brother", "sister", "thread", "tie", "festival"] },
  { word: "JANMASHTAMI",        taboo: ["Krishna", "birth", "festival", "celebrate", "dahi handi"] },
  { word: "GANESH CHATURTHI",   taboo: ["Ganesh", "festival", "Maharashtra", "idol", "immerse"] },
  { word: "DHANTERAS",          taboo: ["gold", "buy", "Diwali", "wealth", "festival"] },
  { word: "LOHRI",              taboo: ["Punjab", "fire", "winter", "festival", "harvest"] },
  { word: "PONGAL RICE",        taboo: ["sweet", "cook", "South", "festival", "new pot"] },
  { word: "VADA PAV",           taboo: ["Mumbai", "bread", "potato", "street", "snack"] },
  { word: "PAV BHAJI",          taboo: ["bread", "vegetable", "Mumbai", "street", "butter"] },
  { word: "CHOLE BHATURE",      taboo: ["Punjab", "chickpea", "fried", "bread", "North"] },
  { word: "RAJMA CHAWAL",       taboo: ["kidney", "bean", "rice", "North", "cook"] },
  { word: "THALI",              taboo: ["plate", "round", "meal", "full", "Indian"] },
  { word: "STREET FOOD",        taboo: ["outside", "sell", "eat", "cheap", "tasty"] },
  { word: "BAZAAR",             taboo: ["market", "buy", "sell", "shop", "crowd"] },
  { word: "DARJEELING",         taboo: ["tea", "hill", "West Bengal", "train", "mountain"] },
  { word: "SHIMLA",             taboo: ["hill", "Himachal", "cool", "British, capital", "snow"] },
  { word: "GULMARG",            taboo: ["snow", "Kashmir", "ski", "hill", "meadow"] },
  { word: "VARANASI",           taboo: ["holy", "Ganga", "temple", "city", "Shiva"] },
  { word: "AMRITSAR",           taboo: ["Punjab", "Golden Temple", "city", "border", "Sikh"] },
  { word: "JAIPUR",             taboo: ["pink", "city", "Rajasthan", "fort", "palace"] },
  { word: "UDAIPUR",            taboo: ["lake", "palace", "Rajasthan", "royal", "city"] },
  { word: "MYSORE",             taboo: ["palace", "Karnataka", "sandalwood", "city", "royal"] },
  { word: "PONDICHERRY",        taboo: ["French", "South", "coastal", "quiet", "city"] },
  { word: "LAKSHADWEEP",        taboo: ["island", "coral", "sea", "tiny", "Union Territory"] },
  { word: "ANDAMAN ISLANDS",    taboo: ["island", "sea", "blue", "prison", "British"] },
  { word: "NORTH EAST INDIA",   taboo: ["seven sisters", "tribal", "forest", "remote", "India"] },
  { word: "STATUE OF UNITY",    taboo: ["Patel", "Gujarat", "tall", "statue", "river"] },
  { word: "CHHATRAPATI",        taboo: ["title", "Shivaji", "Maratha", "king", "honour"] },
  { word: "LOKPAL",             taboo: ["ombudsman", "India", "corruption", "investigate", "law"] },
  { word: "PANCHAYAT",          taboo: ["village", "council", "govern", "rural", "elected"] },
  { word: "ANGANWADI",          taboo: ["child", "village", "nutrition", "care", "government"] },
  { word: "RATION SHOP",        taboo: ["food", "government", "cheap", "card", "supply"] },
  { word: "KHADI",              taboo: ["cloth", "Gandhi", "hand", "spin", "Indian"] },

  // ── 300 additional medium words (Indian context) ────────────────────────

  // Indian Cities
  { word: "DELHI",               taboo: ["capital", "North", "PM", "metro", "Yamuna"] },
  { word: "CHENNAI",             taboo: ["South", "Tamil", "coastal", "music", "film"] },
  { word: "PUNE",                taboo: ["Maharashtra", "IT", "student city", "Shivaji", "cultural"] },
  { word: "AHMEDABAD",           taboo: ["Gujarat", "business", "Gandhi", "heritage", "Sabarmati"] },
  { word: "SURAT",               taboo: ["Gujarat", "diamond", "textile", "trade", "coastal"] },
  { word: "LUCKNOW",             taboo: ["UP", "nawab", "kebab", "cultural", "tehzeeb"] },
  { word: "PATNA",               taboo: ["Bihar", "Ganga", "east", "history", "Patliputra"] },
  { word: "NAGPUR",              taboo: ["orange", "central", "Maharashtra", "geography", "RSS"] },
  { word: "COIMBATORE",          taboo: ["Tamil Nadu", "cotton", "industry", "South", "city"] },
  { word: "GUWAHATI",            taboo: ["Assam", "northeast", "Brahmaputra", "gateway", "city"] },
  { word: "DEHRADUN",            taboo: ["Uttarakhand", "capital", "cool", "hill", "IMA"] },
  { word: "KOCHI",               taboo: ["Kerala", "port", "sea", "modern", "spice trade"] },
  { word: "MADURAI",             taboo: ["Tamil Nadu", "temple city", "ancient", "South", "Meenakshi"] },
  { word: "TIRUPATI",            taboo: ["Andhra", "temple", "hill", "devotion", "famous"] },
  { word: "RANCHI",              taboo: ["Jharkhand", "capital", "Dhoni", "hill", "city"] },
  { word: "BHOPAL",              taboo: ["MP", "lake city", "capital", "gas tragedy", "city"] },
  { word: "INDORE",              taboo: ["MP", "food", "cleanest city", "Holkar", "central"] },
  { word: "THIRUVANANTHAPURAM",  taboo: ["Kerala", "capital", "south", "temple", "coast"] },
  { word: "MANGALURU",           taboo: ["Karnataka", "coastal", "South", "port", "Konkani"] },
  { word: "VIZAG",               taboo: ["Andhra", "coastal", "steel", "port", "Araku"] },
  { word: "BHUBANESWAR",         taboo: ["Odisha", "temple", "capital", "east", "city"] },

  // Monuments & Sites
  { word: "MEENAKSHI TEMPLE",    taboo: ["Madurai", "Tamil Nadu", "ancient", "gopuram", "colourful"] },
  { word: "SHORE TEMPLE",        taboo: ["Mahabalipuram", "Tamil Nadu", "sea", "stone", "ancient"] },
  { word: "KHAJURAHO",           taboo: ["MP", "temple", "sculpture", "ancient", "UNESCO"] },
  { word: "SANCHI STUPA",        taboo: ["MP", "Buddhist", "dome", "Ashoka", "ancient"] },
  { word: "SOMNATH TEMPLE",      taboo: ["Gujarat", "Shiva", "coastal", "ancient", "holy"] },
  { word: "DWARKA",              taboo: ["Gujarat", "Krishna", "holy", "sea", "city"] },
  { word: "MATHURA",             taboo: ["UP", "Krishna", "holy", "birth", "ancient"] },
  { word: "VRINDAVAN",           taboo: ["UP", "Krishna", "temple", "holy", "colour"] },
  { word: "AYODHYA",             taboo: ["UP", "Ram", "holy", "ancient", "Ram Mandir"] },
  { word: "SHIRDI",              taboo: ["Maharashtra", "Sai Baba", "devotion", "pilgrimage", "holy"] },
  { word: "VAISHNO DEVI",        taboo: ["Jammu", "mountain", "cave", "temple", "trek"] },
  { word: "CHAR DHAM",           taboo: ["four", "pilgrimage", "Hindu", "Uttarakhand", "holy"] },
  { word: "RISHIKESH",           taboo: ["yoga", "Ganga", "spiritual", "Uttarakhand", "adventure"] },
  { word: "HARIDWAR",            taboo: ["Ganga", "holy", "ghat", "bath", "Uttarakhand"] },
  { word: "BODH GAYA",           taboo: ["Buddha", "enlightenment", "Bihar", "tree", "peace"] },
  { word: "SARNATH",             taboo: ["Buddha", "first sermon", "UP", "deer", "stupa"] },
  { word: "BRIHADEESWARAR",      taboo: ["Thanjavur", "Tamil Nadu", "ancient", "large", "granite"] },
  { word: "LOTHAL",              taboo: ["Harappan", "Gujarat", "ancient", "port", "excavation"] },
  { word: "FATEHPUR SIKRI",      taboo: ["Akbar", "Agra", "Mughal", "abandoned", "stone"] },
  { word: "MAHABALESHWAR",       taboo: ["hill station", "Maharashtra", "strawberry", "cool", "valley"] },
  { word: "KODAIKANAL",          taboo: ["hill station", "Tamil Nadu", "cool", "lake", "fog"] },
  { word: "OOTY",                taboo: ["hill", "Tamil Nadu", "train", "cool", "garden"] },
  { word: "MUNNAR",              taboo: ["Kerala", "tea", "hill", "green", "cool"] },
  { word: "COORG",               taboo: ["Karnataka", "coffee", "hills", "misty", "green"] },
  { word: "KONKAN",              taboo: ["coastal", "Maharashtra", "Goa", "beach", "fish"] },

  // Famous Indians
  { word: "RABINDRANATH TAGORE", taboo: ["poet", "Nobel", "Bengal", "Gitanjali", "song"] },
  { word: "APJ ABDUL KALAM",     taboo: ["missile", "ISRO", "president", "inspire", "Wings of Fire"] },
  { word: "VISWANATHAN ANAND",   taboo: ["chess", "world", "champion", "India", "grandmaster"] },
  { word: "SACHIN TENDULKAR",    taboo: ["cricket", "hundred", "bat", "god of cricket", "records"] },
  { word: "MS DHONI",            taboo: ["captain", "cricket", "Ranchi", "cool", "last ball"] },
  { word: "AMITABH BACHCHAN",    taboo: ["actor", "Bollywood", "tall", "baritone", "megastar"] },
  { word: "LATA MANGESHKAR",     taboo: ["singer", "nightingale", "India", "melody", "Bharat Ratna"] },
  { word: "AR RAHMAN",           taboo: ["music", "Oscar", "Chennai", "composer", "Jai Ho"] },
  { word: "RAVI SHANKAR",        taboo: ["sitar", "classical", "Indian", "world", "musician"] },
  { word: "SWAMI VIVEKANANDA",   taboo: ["Chicago", "speech", "monk", "Bengal", "Ramakrishna"] },
  { word: "RAMANUJAN",           taboo: ["mathematics", "genius", "Tamil Nadu", "infinite", "Cambridge"] },
  { word: "CV RAMAN",            taboo: ["Nobel", "physics", "light", "Bengal", "scattering"] },
  { word: "SAROJINI NAIDU",      taboo: ["poet", "freedom", "India", "nightingale", "woman"] },
  { word: "MOTHER TERESA",       taboo: ["Kolkata", "service", "poor", "Nobel", "nun"] },
  { word: "BIRSA MUNDA",         taboo: ["tribal", "Jharkhand", "freedom", "brave", "hero"] },
  { word: "TIPU SULTAN",         taboo: ["Mysore", "brave", "tiger", "British", "rockets"] },
  { word: "PRITHVIRAJ CHAUHAN",  taboo: ["king", "Delhi", "Rajput", "brave", "last Hindu emperor"] },
  { word: "KRISHNADEVA RAYA",    taboo: ["Vijayanagara", "king", "patron", "Telugu", "strong"] },
  { word: "SANIA MIRZA",         taboo: ["tennis", "woman", "India", "doubles", "champion"] },
  { word: "MARY KOM",            taboo: ["boxing", "Manipur", "woman", "champion", "India"] },
  { word: "PT USHA",             taboo: ["runner", "Kerala", "golden girl", "athlete", "India"] },
  { word: "KAPIL DEV",           taboo: ["cricket", "captain", "1983", "all-rounder", "World Cup"] },
  { word: "MILKHA SINGH",        taboo: ["runner", "Punjab", "flying", "athlete", "partition"] },
  { word: "SAINA NEHWAL",        taboo: ["badminton", "woman", "India", "Olympic", "top ranked"] },
  { word: "PV SINDHU",           taboo: ["badminton", "woman", "India", "Olympic", "tall"] },
  { word: "ABHINAV BINDRA",      taboo: ["shooting", "Olympic gold", "India", "alone", "first"] },
  { word: "LEANDER PAES",        taboo: ["tennis", "Davis Cup", "India", "doubles", "champion"] },

  // Indian Arts & Crafts
  { word: "WARLI ART",           taboo: ["Maharashtra", "tribal", "white", "stick figure", "painting"] },
  { word: "MADHUBANI PAINTING",  taboo: ["Bihar", "colourful", "intricate", "woman", "art"] },
  { word: "PATTACHITRA",         taboo: ["Odisha", "scroll", "painting", "folk", "story"] },
  { word: "KALAMKARI",           taboo: ["Andhra", "hand painted", "cloth", "natural dye", "traditional"] },
  { word: "GOND ART",            taboo: ["tribal", "MP", "colourful", "animals", "dots"] },
  { word: "PHULKARI",            taboo: ["Punjab", "embroidery", "flower", "bright", "cloth"] },
  { word: "CHIKANKARI",          taboo: ["Lucknow", "white", "embroidery", "delicate", "cloth"] },
  { word: "ZARDOZI",             taboo: ["golden", "embroidery", "heavy", "wedding", "Lucknow"] },
  { word: "BANDHANI",            taboo: ["Gujarat", "tie-dye", "colourful", "dots", "cloth"] },
  { word: "KANTHA",              taboo: ["Bengali", "stitch", "quilt", "old", "cloth"] },
  { word: "PASHMINA",            taboo: ["Kashmir", "shawl", "fine", "soft", "luxury"] },
  { word: "IKAT",                taboo: ["weave", "Odisha", "Andhra", "pattern", "cloth"] },
  { word: "BLUE POTTERY",        taboo: ["Jaipur", "blue", "round", "Persian", "craft"] },
  { word: "TERRACOTTA",          taboo: ["clay", "baked", "craft", "Bengal", "red"] },
  { word: "KONDAPALLI TOY",      taboo: ["AP", "wood", "painted", "toy", "craft"] },
  { word: "BRASSWARE",           taboo: ["metal", "Moradabad", "craft", "etched", "decorate"] },

  // More Festivals
  { word: "BONALU",              taboo: ["Telangana", "goddess", "festival", "pot", "procession"] },
  { word: "BATHUKAMMA",          taboo: ["Telangana", "flower", "stack", "women", "festival"] },
  { word: "HORNBILL FESTIVAL",   taboo: ["Nagaland", "tribal", "culture", "northeast", "December"] },
  { word: "HEMIS FESTIVAL",      taboo: ["Ladakh", "Buddhist", "monastery", "mask", "dance"] },
  { word: "THRISSUR POORAM",     taboo: ["Kerala", "elephant", "temple", "festival", "May"] },
  { word: "MYSORE DASARA",       taboo: ["Karnataka", "royal", "Navratri", "procession", "grand"] },
  { word: "RANN UTSAV",          taboo: ["Gujarat", "salt", "desert", "night", "festival"] },
  { word: "CHERRY BLOSSOM",      taboo: ["Shillong", "spring", "pink", "flower", "festival"] },
  { word: "AMBUBACHI MELA",      taboo: ["Assam", "Kamakhya", "monsoon", "festival", "pilgrimage"] },
  { word: "CHAPCHAR KUT",        taboo: ["Mizoram", "spring", "bamboo", "festival", "dance"] },
  { word: "WANGALA FESTIVAL",    taboo: ["Meghalaya", "Garo", "harvest", "drum", "festival"] },
  { word: "LOSAR",               taboo: ["Tibetan", "New Year", "Ladakh", "festival", "Buddhist"] },
  { word: "VISHU",               taboo: ["Kerala", "New Year", "April", "festival", "Kani"] },
  { word: "BIHU DANCE",          taboo: ["Assam", "harvest", "festival", "pair", "traditional"] },
  { word: "CHHAT PUJA",          taboo: ["Bihar", "sun", "river", "woman", "festival"] },
  { word: "TEEJ",                taboo: ["Rajasthan", "woman", "monsoon", "festival", "swing"] },
  { word: "KARVA CHAUTH",        taboo: ["fast", "woman", "husband", "moon", "North India"] },
  { word: "VAISAKHI",            taboo: ["Punjab", "harvest", "Sikh", "April", "dance"] },

  // Indian Geography
  { word: "HIMALAYAN RANGE",     taboo: ["mountain", "north", "snow", "tall", "border"] },
  { word: "WESTERN GHATS",       taboo: ["range", "Kerala", "Karnataka", "forest", "rain"] },
  { word: "EASTERN GHATS",       taboo: ["range", "east coast", "hill", "forest", "India"] },
  { word: "DECCAN PLATEAU",      taboo: ["flat", "high", "south", "central", "rocky"] },
  { word: "THAR DESERT",         taboo: ["hot", "sandy", "Rajasthan", "dry", "large"] },
  { word: "GANGA PLAIN",         taboo: ["fertile", "North", "flat", "river", "vast"] },
  { word: "KANCHENJUNGA",        taboo: ["mountain", "third tallest", "Sikkim", "snow", "peak"] },
  { word: "NANDA DEVI",          taboo: ["mountain", "Uttarakhand", "snow", "tall", "reserve"] },
  { word: "SIACHEN GLACIER",     taboo: ["glacier", "highest", "military", "cold", "Kashmir"] },
  { word: "ARAVALLIS",           taboo: ["old", "mountain", "Rajasthan", "range", "west"] },
  { word: "LOKTAK LAKE",         taboo: ["Manipur", "floating island", "northeast", "unique", "large"] },
  { word: "VEMBANAD LAKE",       taboo: ["Kerala", "longest", "backwater", "houseboat", "peaceful"] },
  { word: "WULAR LAKE",          taboo: ["Kashmir", "large", "north", "freshwater", "beauty"] },
  { word: "RAIN SHADOW",         taboo: ["mountain", "block", "dry", "one side", "wind"] },

  // Indian Economy & Institutions
  { word: "TATA GROUP",          taboo: ["company", "India", "steel", "salt", "Jamsetji"] },
  { word: "INFOSYS",             taboo: ["IT", "Bangalore", "Narayana Murthy", "software", "global"] },
  { word: "RELIANCE",            taboo: ["oil", "Ambani", "largest", "India", "Mumbai"] },
  { word: "AMUL",                taboo: ["milk", "Gujarat", "cooperative", "butter", "dairy"] },
  { word: "IIT",                 taboo: ["engineering", "exam", "prestigious", "India", "JEE"] },
  { word: "IIM",                 taboo: ["management", "MBA", "prestigious", "India", "CAT"] },
  { word: "AIIMS",               taboo: ["medical", "Delhi", "prestigious", "hospital", "India"] },
  { word: "UPSC",                taboo: ["exam", "Delhi", "government", "IAS", "officer"] },
  { word: "ELECTION COMMISSION", taboo: ["India", "conduct", "election", "independent", "fair"] },
  { word: "RESERVE BANK",        taboo: ["RBI", "central bank", "rupee", "governor", "monetary"] },
  { word: "NITI AAYOG",          taboo: ["policy", "India", "replace", "Planning Commission", "development"] },
  { word: "ISRO",                taboo: ["space", "India", "satellite", "Bangalore", "rocket"] },
  { word: "DRDO",                taboo: ["defence", "research", "India", "weapon", "develop"] },

  // More Indian Food
  { word: "KEBAB",               taboo: ["meat", "grill", "North", "smoky", "skewer"] },
  { word: "HALEEM",              taboo: ["meat", "wheat", "slow cook", "Hyderabad", "rich"] },
  { word: "NIHARI",              taboo: ["meat", "slow cook", "North", "morning", "rich"] },
  { word: "BUTTER CHICKEN",      taboo: ["cream", "tomato", "Punjab", "mild", "popular"] },
  { word: "CHICKEN TIKKA",       taboo: ["marinate", "grill", "red", "spice", "skewer"] },
  { word: "ROGAN JOSH",          taboo: ["Kashmir", "lamb", "red", "spicy", "aromatic"] },
  { word: "KORMA",               taboo: ["mild", "creamy", "cook", "North", "nuts"] },
  { word: "FISH CURRY",          taboo: ["fish", "gravy", "Kerala", "coastal", "eat"] },
  { word: "MASALA DOSA",         taboo: ["crispy", "potato", "South", "large", "breakfast"] },
  { word: "SABUDANA KHICHDI",    taboo: ["fasting", "Maharashtra", "soft", "sago", "peanut"] },
  { word: "PHIRNI",              taboo: ["Delhi", "rice", "milk", "sweet", "clay pot"] },
  { word: "BESAN LADOO",         taboo: ["gram flour", "sweet", "round", "festival", "Diwali"] },
  { word: "GUJIYA",              taboo: ["North", "stuffed", "sweet", "Holi", "fried"] },
  { word: "MALPUA",              taboo: ["sweet", "fried", "pancake", "North", "festival"] },
  { word: "TILGUL",              taboo: ["sesame", "sweet", "Makar Sankranti", "Maharashtra", "gift"] },
  { word: "CHIROTE",             taboo: ["Maharashtra", "fried", "sweet", "crispy", "festival"] },
  { word: "SATTU",               taboo: ["roasted", "flour", "Bihar", "cool", "drink"] },
  { word: "CHAAS",               taboo: ["buttermilk", "cool", "summer", "drink", "Gujarat"] },
  { word: "PAPAD",               taboo: ["thin", "crispy", "round", "fried", "eat with meal"] },
  { word: "ACHAAR",              taboo: ["sour", "spicy", "jar", "preserve", "tangy"] },
  { word: "PURI BHAJI",          taboo: ["puffed", "fried", "vegetable", "breakfast", "North"] },
  { word: "SHEER KORMA",         taboo: ["Eid", "vermicelli", "milk", "sweet", "Muslim festival"] },

  // Indian States
  { word: "RAJASTHAN",           taboo: ["desert", "fort", "colourful", "camel", "Jaipur"] },
  { word: "GUJARAT",             taboo: ["Gandhi", "business", "vegetarian", "west", "Surat"] },
  { word: "KARNATAKA",           taboo: ["Bangalore", "coffee", "south", "Mysore", "Kaveri"] },
  { word: "KERALA",              taboo: ["backwater", "coconut", "spice", "south", "literacy"] },
  { word: "TAMIL NADU",          taboo: ["temple", "south", "Chennai", "classical", "Kaveri"] },
  { word: "ODISHA",              taboo: ["temple", "tribal", "east", "coast", "Puri"] },
  { word: "WEST BENGAL",         taboo: ["Kolkata", "culture", "east", "fish", "Tagore"] },
  { word: "BIHAR",               taboo: ["history", "Ganga", "east", "Patna", "Nalanda"] },
  { word: "UTTAR PRADESH",       taboo: ["holy", "largest", "Ganga", "Hindi", "Agra"] },
  { word: "PUNJAB",              taboo: ["wheat", "Sikh", "fertile", "north", "bhangra"] },
  { word: "ASSAM",               taboo: ["tea", "northeast", "rhino", "silk", "Brahmaputra"] },
  { word: "MEGHALAYA",           taboo: ["cloud", "rain", "northeast", "green", "tribal"] },
  { word: "MANIPUR",             taboo: ["dance", "northeast", "tribal", "Polo", "India"] },
  { word: "SIKKIM",              taboo: ["Kanchenjunga", "small", "mountain", "northeast", "organic"] },
  { word: "CHHATTISGARH",        taboo: ["forest", "tribal", "central", "mineral", "Raipur"] },
  { word: "MADHYA PRADESH",      taboo: ["heart of India", "Bhopal", "tiger", "temples", "central"] },
  { word: "HIMACHAL PRADESH",    taboo: ["hill", "apple", "snow", "north", "Shimla"] },
  { word: "UTTARAKHAND",         taboo: ["Ganga", "mountain", "north", "forest", "Dehradun"] },
  { word: "JHARKHAND",           taboo: ["tribal", "forest", "east", "mineral", "Ranchi"] },
  { word: "TELANGANA",           taboo: ["Hyderabad", "IT", "new state", "south", "Bhagya Lakshmi"] },
  { word: "GOA",                 taboo: ["beach", "Portuguese", "tourist", "coastal", "state"] },

  // More Personalities (Historical)
  { word: "INDIRA GANDHI",       taboo: ["India", "PM", "woman", "powerful", "Emergency"] },
  { word: "ATAL BIHARI VAJPAYEE",taboo: ["PM", "poet", "India", "BJP", "statesman"] },
  { word: "MANMOHAN SINGH",      taboo: ["economist", "PM", "India", "reforms", "Sikh"] },
  { word: "JAWAHARLAL NEHRU",    taboo: ["first PM", "rose", "children's day", "Kashmir", "India"] },
  { word: "PV NARASIMHA RAO",    taboo: ["reforms", "PM", "India", "1991", "Telugu"] },
  { word: "LAL BAHADUR SHASTRI", taboo: ["PM", "Jai Jawan", "India", "modest", "Tashkent"] },
  { word: "BABASAHEB AMBEDKAR",  taboo: ["constitution", "Dalit", "rights", "law", "Bharat Ratna"] },
  { word: "LOKMANYA TILAK",      taboo: ["freedom", "Swaraj", "Pune", "Ganesh festival", "newspaper"] },
  { word: "ANNIE BESANT",        taboo: ["Home Rule", "theosophist", "India", "woman", "Irish"] },
  { word: "SUBHASH BOSE",        taboo: ["INA", "freedom", "Bengal", "brave", "Netaji"] },

  // Cultural Practices
  { word: "ATITHI DEVO BHAVA",   taboo: ["guest", "god", "India", "welcome", "hospitality"] },
  { word: "GURU SHISHYA",        taboo: ["teacher", "disciple", "tradition", "India", "learn"] },
  { word: "THREAD CEREMONY",     taboo: ["Brahmin", "boy", "sacred", "Hindu", "ritual"] },
  { word: "MUHURATAM",           taboo: ["auspicious", "time", "Hindu", "ceremony", "plan"] },
  { word: "VEDIC CHANT",         taboo: ["ancient", "Sanskrit", "pray", "Vedas", "priest"] },
  { word: "PUJA THALI",          taboo: ["plate", "worship", "round", "lamp", "flower"] },
  { word: "GOTRA",               taboo: ["lineage", "Hindu", "clan", "identity", "family"] },

  // Bollywood & Cinema
  { word: "SHOLAY",              taboo: ["Bollywood", "classic", "action", "Dharmendra", "Gabbar"] },
  { word: "LAGAAN",              taboo: ["cricket", "British", "film", "Oscar", "village"] },
  { word: "MUGHAL-E-AZAM",       taboo: ["classic", "Bollywood", "Mughal", "love", "black white"] },
  { word: "DILWALE DULHANIA",    taboo: ["Bollywood", "love", "train", "Shahrukh", "classic"] },
  { word: "THREE IDIOTS",        taboo: ["college", "comedy", "Aamir", "film", "engineer"] },
  { word: "DANGAL",              taboo: ["wrestling", "Aamir", "daughters", "Haryana", "sport film"] },
  { word: "BAAHUBALI",           taboo: ["Telugu", "epic", "action", "blockbuster", "Prabhas"] },
  { word: "PATHER PANCHALI",     taboo: ["Bengali", "Satyajit Ray", "classic", "rural", "film"] },
  { word: "DEVDAS",              taboo: ["tragic", "Bollywood", "love", "classic", "Sarat"] },
  { word: "GUIDE",               taboo: ["Bollywood", "Dev Anand", "classic", "journey", "film"] },

  // Indian Media
  { word: "DOORDARSHAN",         taboo: ["TV", "government", "India", "channel", "old"] },
  { word: "ALL INDIA RADIO",     taboo: ["radio", "government", "India", "broadcast", "news"] },
  { word: "TIMES OF INDIA",      taboo: ["newspaper", "English", "India", "oldest", "print"] },
  { word: "THE HINDU",           taboo: ["newspaper", "South", "India", "Chennai", "English"] },

  // Communities & Religions
  { word: "JAINISM",             taboo: ["nonviolence", "India", "religion", "Gujarat", "vegetarian"] },
  { word: "SIKHISM",             taboo: ["Punjab", "turban", "brave", "Gurdwara", "Khalsa"] },
  { word: "ZOROASTRIAN",         taboo: ["Parsi", "Gujarat", "fire", "small", "community"] },
  { word: "BUDDHISM",            taboo: ["Buddha", "peace", "India", "meditation", "eight fold path"] },
  { word: "SUFI TRADITION",      taboo: ["Muslim", "mystic", "song", "India", "dargah"] },
  { word: "DARGAH",              taboo: ["Muslim", "saint", "grave", "shrine", "pilgrimage"] },
  { word: "VIPASSANA",           taboo: ["meditation", "Buddha", "silent", "ten days", "centre"] },
  { word: "GURU GRANTH SAHIB",   taboo: ["Sikh", "holy", "scripture", "Gurdwara", "respect"] },

  // Epics & Literature
  { word: "VEDAS",               taboo: ["ancient", "Hindu", "sacred", "four", "Sanskrit"] },
  { word: "UPANISHADS",          taboo: ["philosophy", "Hindu", "ancient", "knowledge", "Sanskrit"] },
  { word: "ARTHASHASTRA",        taboo: ["Chanakya", "politics", "ancient", "statecraft", "India"] },
  { word: "PANCHATANTRA",        taboo: ["animal", "story", "ancient", "fable", "India"] },
  { word: "SHAKUNTALA",          taboo: ["Kalidasa", "play", "love", "ancient", "Sanskrit"] },
  { word: "RAMCHARITMANAS",      taboo: ["Tulsidas", "Ram", "Avadhi", "Hindi", "poem"] },
  { word: "MANUSMRITI",          taboo: ["ancient", "Hindu", "law", "text", "controversial"] },
  { word: "THIRUKKURAL",         taboo: ["Tamil", "Thiruvalluvar", "couplet", "wisdom", "ancient"] },

  // More Cultural / Society
  { word: "CORBETT PARK",        taboo: ["tiger", "Uttarakhand", "oldest", "park", "Jim"] },
  { word: "GUNDLUPET",           taboo: ["elephant", "Karnataka", "Bandipur", "forest", "wildlife"] },
  { word: "PROJECT TIGER",       taboo: ["India", "protect", "tiger", "reserve", "conservation"] },
  { word: "BHITARKANIKA",        taboo: ["Odisha", "mangrove", "crocodile", "east", "coast"] },

  // More Food (Regional)
  { word: "LITTI CHOKHA",        taboo: ["Bihar", "roasted", "stuffed", "gram", "vegetable"] },
  { word: "THUKPA",              taboo: ["northeast", "noodle", "soup", "hot", "Tibetan"] },
  { word: "KOSHA MANGSHO",       taboo: ["Bengali", "mutton", "dry", "slow cook", "Durga Puja"] },
  { word: "MACHHER JHOL",        taboo: ["Bengali", "fish", "curry", "light", "everyday"] },
  { word: "BAMBOO SHOOT CURRY",  taboo: ["northeast", "cook", "bamboo", "vegetable", "tribal"] },
  { word: "SMOKED PORK",         taboo: ["northeast", "Nagaland", "smoky", "meat", "spicy"] },
  { word: "SOL KADHI",           taboo: ["Konkan", "kokum", "coconut", "pink", "cool drink"] },
  { word: "PURAN POLI",          taboo: ["Maharashtra", "sweet", "flat", "festival", "chana dal"] },
  { word: "HANDVO",              taboo: ["Gujarat", "bake", "savoury", "cake", "mixed"] },
  { word: "KHAMAN",              taboo: ["Gujarat", "yellow", "steam", "soft", "snack"] },

  // Geographical Passes & Natural Features
  { word: "KHARDUNG LA",         taboo: ["Ladakh", "high pass", "road", "cold", "altitude"] },
  { word: "ROHTANG PASS",        taboo: ["Himachal", "mountain", "road", "snow", "Manali"] },
  { word: "BANIHAL PASS",        taboo: ["Kashmir", "pass", "road", "connect", "Jammu"] },
  { word: "VALLEY OF FLOWERS",   taboo: ["Uttarakhand", "flowers", "beautiful", "national park", "trek"] },
  { word: "SPITI VALLEY",        taboo: ["cold", "Himachal", "desert", "high", "remote"] },
  { word: "ZANSKAR",             taboo: ["cold", "Ladakh", "river", "frozen", "trek"] },
  { word: "SHILLONG",            taboo: ["northeast", "Meghalaya", "Scotland of East", "hill", "music"] },
  { word: "TAWANG",              taboo: ["Arunachal", "monastery", "Buddhist", "high", "northeast"] },
  { word: "DZUKOU VALLEY",       taboo: ["Nagaland", "flower", "valley", "trek", "northeast"] },
  { word: "BRAHMAPUTRA VALLEY",  taboo: ["Assam", "river", "flat", "fertile", "northeast"] },

  // ── Top-up additions (unique Indian context) ───────────────────────────

  // More Indian Cities
  { word: "JODHPUR",             taboo: ["blue city", "Rajasthan", "fort", "clock tower", "Mehrangarh"] },
  { word: "JAISALMER",           taboo: ["golden city", "Rajasthan", "fort", "desert", "Sam sand dunes"] },
  { word: "AJMER",               taboo: ["Rajasthan", "dargah", "spiritual", "Pushkar near", "city"] },
  { word: "BIKANER",             taboo: ["Rajasthan", "camel", "fort", "desert", "Karni Mata"] },
  { word: "UJJAIN",              taboo: ["MP", "holy", "Mahakal", "12 jyotirlinga", "ancient"] },
  { word: "GWALIOR",             taboo: ["MP", "fort", "Tansen", "Scindia", "city"] },
  { word: "NASHIK",              taboo: ["Maharashtra", "Kumbh", "wine", "grape", "Godavari"] },
  { word: "TRICHY",              taboo: ["Tamil Nadu", "rock fort", "temple", "Kaveri", "city"] },
  { word: "PRAYAGRAJ",           taboo: ["UP", "Sangam", "confluence", "Kumbh", "holy"] },
  { word: "VIJAYWADA",           taboo: ["Andhra", "Krishna river", "rice", "Kanaka Durga", "city"] },
  { word: "AGRA",                taboo: ["UP", "Taj Mahal", "Mughal", "city", "fort"] },
  { word: "AURANGABAD",          taboo: ["Maharashtra", "Ajanta Ellora near", "Aurangzeb", "cave", "city"] },
  { word: "WARANGAL",            taboo: ["Telangana", "Kakatiya", "fort", "ancient", "city"] },

  // Classical Dance Forms (new)
  { word: "ODISSI",              taboo: ["classical", "Odisha", "temple", "graceful", "Mahari"] },
  { word: "MANIPURI DANCE",      taboo: ["classical", "northeast", "soft", "gentle", "Ras Leela"] },
  { word: "KUCHIPUDI",           taboo: ["classical", "Andhra", "village", "performance", "ancient"] },
  { word: "MOHINIYATTAM",        taboo: ["classical", "Kerala", "white", "gentle", "graceful"] },
  { word: "SATTRIYA",            taboo: ["classical", "Assam", "Vaishnavite", "monastery", "ancient"] },
  { word: "CHHAU DANCE",         taboo: ["mask", "tribal", "Bengal", "martial", "folk dance"] },
  { word: "KALARIPAYATTU",       taboo: ["martial art", "Kerala", "oldest", "flexible", "weapon"] },
  { word: "LAVANI",              taboo: ["Maharashtra", "folk", "energetic", "woman", "song dance"] },

  // Indian Music Forms
  { word: "GHAZAL",              taboo: ["Urdu", "love poetry", "soft", "singer", "couplet"] },
  { word: "QAWWALI",             taboo: ["Sufi", "devotional", "group", "Muslim", "energetic"] },
  { word: "THUMRI",              taboo: ["North", "semi-classical", "love", "expressive", "Krishna"] },
  { word: "DHRUPAD",             taboo: ["oldest", "Hindustani", "serious", "meditative", "North"] },
  { word: "BHAJAN",              taboo: ["devotional", "sing", "simple", "Indian", "god"] },
  { word: "KIRTAN",              taboo: ["chanting", "Sikh", "devotional", "group", "sing"] },

  // Indian Textiles
  { word: "BANARASI SILK",       taboo: ["Varanasi", "silk", "heavy", "wedding", "gold thread"] },
  { word: "KANJEEVARAM",         taboo: ["Tamil Nadu", "silk", "heavy", "colourful", "wedding"] },
  { word: "JAMDANI",             taboo: ["Bengal", "fine", "cotton", "pattern", "UNESCO"] },
  { word: "POCHAMPALLI",         taboo: ["Andhra", "ikat", "silk", "weave", "geometric"] },
  { word: "CHANDERI",            taboo: ["MP", "lightweight", "silk", "cotton", "transparent"] },
  { word: "SAMBALPURI",          taboo: ["Odisha", "ikat", "weave", "traditional", "colourful"] },
  { word: "TANT",                taboo: ["Bengal", "cotton", "light", "white", "handloom"] },

  // Indian Personalities (Social Reformers)
  { word: "RAJA RAM MOHAN ROY",  taboo: ["Bengal", "reform", "sati", "Brahmo Samaj", "women rights"] },
  { word: "JYOTIRAO PHULE",      taboo: ["Maharashtra", "reformer", "lower caste", "women", "education"] },
  { word: "PERIYAR",             taboo: ["Tamil", "rationalist", "self-respect", "Dravidian", "reformer"] },
  { word: "NARAYANA GURU",       taboo: ["Kerala", "reformer", "caste", "social", "saint"] },
  { word: "ISHWAR CHANDRA VIDYASAGAR",taboo:["Bengal", "reform", "widow remarriage", "Sanskrit", "education"] },
  { word: "SWAMI DAYANANDA",     taboo: ["Arya Samaj", "reform", "Vedas", "Hindi", "19th century"] },
  { word: "PANDITA RAMABAI",     taboo: ["Maharashtra", "woman", "reformer", "Christian", "education"] },
  { word: "DHANRAJ PILLAY",      taboo: ["hockey", "captain", "India", "goal", "legend"] },
  { word: "PULLELA GOPICHAND",   taboo: ["badminton", "coach", "Hyderabad", "champion", "India"] },
  { word: "BAJRANG PUNIA",       taboo: ["wrestling", "India", "Olympic", "champion", "Haryana"] },

  // More Festivals
  { word: "BUDDHA PURNIMA",      taboo: ["Buddha", "birth", "enlightenment", "May", "festival"] },
  { word: "GURU NANAK JAYANTI",  taboo: ["Sikh", "Guru Nanak", "birth", "November", "gurdwara"] },
  { word: "MAHAVIR JAYANTI",     taboo: ["Jain", "Mahavir", "birth", "festival", "nonviolence"] },
  { word: "AADI PERUKKU",        taboo: ["Tamil Nadu", "river", "offering", "monsoon", "women"] },
  { word: "POORAM",              taboo: ["Kerala", "elephant", "temple", "competition", "Thrissur"] },
  { word: "NARAK CHATURDASHI",   taboo: ["Diwali", "fourth day", "demon", "oil bath", "festival"] },

  // Indian Rivers (new)
  { word: "TUNGABHADRA",         taboo: ["Karnataka", "Hampi", "Andhra", "river", "south"] },
  { word: "MAHANADI",            taboo: ["Odisha", "river", "east", "Chhattisgarh", "long"] },
  { word: "INDUS",               taboo: ["northwest", "Pakistan", "ancient", "Harappa", "long river"] },
  { word: "CHENAB",              taboo: ["Punjab", "Kashmir", "north", "Indus tributary", "river"] },
  { word: "BEAS",                taboo: ["Punjab", "river", "Alexander stopped", "north", "Himachal"] },
  { word: "PERIYAR RIVER",       taboo: ["Kerala", "longest", "dam", "tiger reserve", "river"] },
  { word: "BETWA",               taboo: ["MP", "UP", "river", "tributary", "Yamuna"] },

  // Indian Arts
  { word: "TANJORE PAINTING",    taboo: ["Tamil Nadu", "gold", "god", "jewelled", "traditional"] },
  { word: "MUGHAL MINIATURE",    taboo: ["small", "detailed", "Mughal", "painting", "historical"] },
  { word: "KERALA MURAL",        taboo: ["wall", "temple", "Kerala", "large", "colourful"] },
  { word: "PALM LEAF ENGRAVING", taboo: ["Odisha", "old", "write", "leaf", "traditional"] },
  { word: "DHOKRA CRAFT",        taboo: ["tribal", "metal", "bell metal", "Bihar", "Odisha"] },

  // Indian Traditional Knowledge
  { word: "JUGAAD",              taboo: ["hack", "India", "clever", "frugal", "workaround"] },
  { word: "VASTU SHASTRA",       taboo: ["science", "design", "house", "direction", "Hindu"] },
  { word: "PANCHANGA",           taboo: ["calendar", "Hindu", "almanac", "date", "auspicious"] },
  { word: "SIDDHA MEDICINE",     taboo: ["South India", "Tamil", "ancient", "herb", "traditional"] },
  { word: "UNANI MEDICINE",      taboo: ["Greek", "Muslim", "herb", "India", "alternative"] },
  { word: "JYOTISH",             taboo: ["Indian astrology", "stars", "future", "chart", "Vedic"] },
  { word: "NATUROPATHY",         taboo: ["natural", "cure", "no medicine", "holistic", "treatment"] },
];
